// Code generated by ent, DO NOT EDIT.

package dashboardagent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContainsFold(FieldID, id))
}

// DisplayName applies equality check predicate on the "display_name" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldDisplayName, v))
}

// Category applies equality check predicate on the "category" field. It's identical to CategoryEQ.
func Category(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldCategory, v))
}

// Instructions applies equality check predicate on the "instructions" field. It's identical to InstructionsEQ.
func Instructions(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldInstructions, v))
}

// PermissionMode applies equality check predicate on the "permission_mode" field. It's identical to PermissionModeEQ.
func PermissionMode(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldPermissionMode, v))
}

// Cwd applies equality check predicate on the "cwd" field. It's identical to CwdEQ.
func Cwd(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldCwd, v))
}

// ProjectID applies equality check predicate on the "project_id" field. It's identical to ProjectIDEQ.
func ProjectID(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldProjectID, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldRole, v))
}

// SessionID applies equality check predicate on the "session_id" field. It's identical to SessionIDEQ.
func SessionID(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldSessionID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldUpdatedAt, v))
}

// DisplayNameEQ applies the EQ predicate on the "display_name" field.
func DisplayNameEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "display_name" field.
func DisplayNameNEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "display_name" field.
func DisplayNameIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "display_name" field.
func DisplayNameNotIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "display_name" field.
func DisplayNameGT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "display_name" field.
func DisplayNameGTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "display_name" field.
func DisplayNameLT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "display_name" field.
func DisplayNameLTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "display_name" field.
func DisplayNameContains(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "display_name" field.
func DisplayNameHasPrefix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "display_name" field.
func DisplayNameHasSuffix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "display_name" field.
func DisplayNameEqualFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "display_name" field.
func DisplayNameContainsFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContainsFold(FieldDisplayName, v))
}

// CategoryEQ applies the EQ predicate on the "category" field.
func CategoryEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldCategory, v))
}

// CategoryNEQ applies the NEQ predicate on the "category" field.
func CategoryNEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldCategory, v))
}

// CategoryIn applies the In predicate on the "category" field.
func CategoryIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldCategory, vs...))
}

// CategoryNotIn applies the NotIn predicate on the "category" field.
func CategoryNotIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldCategory, vs...))
}

// CategoryGT applies the GT predicate on the "category" field.
func CategoryGT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldCategory, v))
}

// CategoryGTE applies the GTE predicate on the "category" field.
func CategoryGTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldCategory, v))
}

// CategoryLT applies the LT predicate on the "category" field.
func CategoryLT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldCategory, v))
}

// CategoryLTE applies the LTE predicate on the "category" field.
func CategoryLTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldCategory, v))
}

// CategoryContains applies the Contains predicate on the "category" field.
func CategoryContains(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContains(FieldCategory, v))
}

// CategoryHasPrefix applies the HasPrefix predicate on the "category" field.
func CategoryHasPrefix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasPrefix(FieldCategory, v))
}

// CategoryHasSuffix applies the HasSuffix predicate on the "category" field.
func CategoryHasSuffix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasSuffix(FieldCategory, v))
}

// CategoryEqualFold applies the EqualFold predicate on the "category" field.
func CategoryEqualFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEqualFold(FieldCategory, v))
}

// CategoryContainsFold applies the ContainsFold predicate on the "category" field.
func CategoryContainsFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContainsFold(FieldCategory, v))
}

// InstructionsEQ applies the EQ predicate on the "instructions" field.
func InstructionsEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldInstructions, v))
}

// InstructionsNEQ applies the NEQ predicate on the "instructions" field.
func InstructionsNEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldInstructions, v))
}

// InstructionsIn applies the In predicate on the "instructions" field.
func InstructionsIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldInstructions, vs...))
}

// InstructionsNotIn applies the NotIn predicate on the "instructions" field.
func InstructionsNotIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldInstructions, vs...))
}

// InstructionsGT applies the GT predicate on the "instructions" field.
func InstructionsGT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldInstructions, v))
}

// InstructionsGTE applies the GTE predicate on the "instructions" field.
func InstructionsGTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldInstructions, v))
}

// InstructionsLT applies the LT predicate on the "instructions" field.
func InstructionsLT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldInstructions, v))
}

// InstructionsLTE applies the LTE predicate on the "instructions" field.
func InstructionsLTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldInstructions, v))
}

// InstructionsContains applies the Contains predicate on the "instructions" field.
func InstructionsContains(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContains(FieldInstructions, v))
}

// InstructionsHasPrefix applies the HasPrefix predicate on the "instructions" field.
func InstructionsHasPrefix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasPrefix(FieldInstructions, v))
}

// InstructionsHasSuffix applies the HasSuffix predicate on the "instructions" field.
func InstructionsHasSuffix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasSuffix(FieldInstructions, v))
}

// InstructionsEqualFold applies the EqualFold predicate on the "instructions" field.
func InstructionsEqualFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEqualFold(FieldInstructions, v))
}

// InstructionsContainsFold applies the ContainsFold predicate on the "instructions" field.
func InstructionsContainsFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContainsFold(FieldInstructions, v))
}

// PermissionModeEQ applies the EQ predicate on the "permission_mode" field.
func PermissionModeEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldPermissionMode, v))
}

// PermissionModeNEQ applies the NEQ predicate on the "permission_mode" field.
func PermissionModeNEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldPermissionMode, v))
}

// PermissionModeIn applies the In predicate on the "permission_mode" field.
func PermissionModeIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldPermissionMode, vs...))
}

// PermissionModeNotIn applies the NotIn predicate on the "permission_mode" field.
func PermissionModeNotIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldPermissionMode, vs...))
}

// PermissionModeGT applies the GT predicate on the "permission_mode" field.
func PermissionModeGT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldPermissionMode, v))
}

// PermissionModeGTE applies the GTE predicate on the "permission_mode" field.
func PermissionModeGTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldPermissionMode, v))
}

// PermissionModeLT applies the LT predicate on the "permission_mode" field.
func PermissionModeLT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldPermissionMode, v))
}

// PermissionModeLTE applies the LTE predicate on the "permission_mode" field.
func PermissionModeLTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldPermissionMode, v))
}

// PermissionModeContains applies the Contains predicate on the "permission_mode" field.
func PermissionModeContains(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContains(FieldPermissionMode, v))
}

// PermissionModeHasPrefix applies the HasPrefix predicate on the "permission_mode" field.
func PermissionModeHasPrefix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasPrefix(FieldPermissionMode, v))
}

// PermissionModeHasSuffix applies the HasSuffix predicate on the "permission_mode" field.
func PermissionModeHasSuffix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasSuffix(FieldPermissionMode, v))
}

// PermissionModeEqualFold applies the EqualFold predicate on the "permission_mode" field.
func PermissionModeEqualFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEqualFold(FieldPermissionMode, v))
}

// PermissionModeContainsFold applies the ContainsFold predicate on the "permission_mode" field.
func PermissionModeContainsFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContainsFold(FieldPermissionMode, v))
}

// CwdEQ applies the EQ predicate on the "cwd" field.
func CwdEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldCwd, v))
}

// CwdNEQ applies the NEQ predicate on the "cwd" field.
func CwdNEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldCwd, v))
}

// CwdIn applies the In predicate on the "cwd" field.
func CwdIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldCwd, vs...))
}

// CwdNotIn applies the NotIn predicate on the "cwd" field.
func CwdNotIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldCwd, vs...))
}

// CwdGT applies the GT predicate on the "cwd" field.
func CwdGT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldCwd, v))
}

// CwdGTE applies the GTE predicate on the "cwd" field.
func CwdGTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldCwd, v))
}

// CwdLT applies the LT predicate on the "cwd" field.
func CwdLT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldCwd, v))
}

// CwdLTE applies the LTE predicate on the "cwd" field.
func CwdLTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldCwd, v))
}

// CwdContains applies the Contains predicate on the "cwd" field.
func CwdContains(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContains(FieldCwd, v))
}

// CwdHasPrefix applies the HasPrefix predicate on the "cwd" field.
func CwdHasPrefix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasPrefix(FieldCwd, v))
}

// CwdHasSuffix applies the HasSuffix predicate on the "cwd" field.
func CwdHasSuffix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasSuffix(FieldCwd, v))
}

// CwdEqualFold applies the EqualFold predicate on the "cwd" field.
func CwdEqualFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEqualFold(FieldCwd, v))
}

// CwdContainsFold applies the ContainsFold predicate on the "cwd" field.
func CwdContainsFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContainsFold(FieldCwd, v))
}

// ProjectIDEQ applies the EQ predicate on the "project_id" field.
func ProjectIDEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldProjectID, v))
}

// ProjectIDNEQ applies the NEQ predicate on the "project_id" field.
func ProjectIDNEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldProjectID, v))
}

// ProjectIDIn applies the In predicate on the "project_id" field.
func ProjectIDIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldProjectID, vs...))
}

// ProjectIDNotIn applies the NotIn predicate on the "project_id" field.
func ProjectIDNotIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldProjectID, vs...))
}

// ProjectIDGT applies the GT predicate on the "project_id" field.
func ProjectIDGT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldProjectID, v))
}

// ProjectIDGTE applies the GTE predicate on the "project_id" field.
func ProjectIDGTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldProjectID, v))
}

// ProjectIDLT applies the LT predicate on the "project_id" field.
func ProjectIDLT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldProjectID, v))
}

// ProjectIDLTE applies the LTE predicate on the "project_id" field.
func ProjectIDLTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldProjectID, v))
}

// ProjectIDContains applies the Contains predicate on the "project_id" field.
func ProjectIDContains(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContains(FieldProjectID, v))
}

// ProjectIDHasPrefix applies the HasPrefix predicate on the "project_id" field.
func ProjectIDHasPrefix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasPrefix(FieldProjectID, v))
}

// ProjectIDHasSuffix applies the HasSuffix predicate on the "project_id" field.
func ProjectIDHasSuffix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasSuffix(FieldProjectID, v))
}

// ProjectIDEqualFold applies the EqualFold predicate on the "project_id" field.
func ProjectIDEqualFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEqualFold(FieldProjectID, v))
}

// ProjectIDContainsFold applies the ContainsFold predicate on the "project_id" field.
func ProjectIDContainsFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContainsFold(FieldProjectID, v))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContainsFold(FieldRole, v))
}

// SessionIDEQ applies the EQ predicate on the "session_id" field.
func SessionIDEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldSessionID, v))
}

// SessionIDNEQ applies the NEQ predicate on the "session_id" field.
func SessionIDNEQ(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldSessionID, v))
}

// SessionIDIn applies the In predicate on the "session_id" field.
func SessionIDIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldSessionID, vs...))
}

// SessionIDNotIn applies the NotIn predicate on the "session_id" field.
func SessionIDNotIn(vs ...string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldSessionID, vs...))
}

// SessionIDGT applies the GT predicate on the "session_id" field.
func SessionIDGT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldSessionID, v))
}

// SessionIDGTE applies the GTE predicate on the "session_id" field.
func SessionIDGTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldSessionID, v))
}

// SessionIDLT applies the LT predicate on the "session_id" field.
func SessionIDLT(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldSessionID, v))
}

// SessionIDLTE applies the LTE predicate on the "session_id" field.
func SessionIDLTE(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldSessionID, v))
}

// SessionIDContains applies the Contains predicate on the "session_id" field.
func SessionIDContains(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContains(FieldSessionID, v))
}

// SessionIDHasPrefix applies the HasPrefix predicate on the "session_id" field.
func SessionIDHasPrefix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasPrefix(FieldSessionID, v))
}

// SessionIDHasSuffix applies the HasSuffix predicate on the "session_id" field.
func SessionIDHasSuffix(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldHasSuffix(FieldSessionID, v))
}

// SessionIDEqualFold applies the EqualFold predicate on the "session_id" field.
func SessionIDEqualFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEqualFold(FieldSessionID, v))
}

// SessionIDContainsFold applies the ContainsFold predicate on the "session_id" field.
func SessionIDContainsFold(v string) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldContainsFold(FieldSessionID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.DashboardAgent) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.DashboardAgent) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.DashboardAgent) predicate.DashboardAgent {
	return predicate.DashboardAgent(sql.NotPredicates(p))
}
