// Code generated by ent, DO NOT EDIT.

package roadmapitem

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContainsFold(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldTitle, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldStatus, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldPosition, v))
}

// Provenance applies equality check predicate on the "provenance" field. It's identical to ProvenanceEQ.
func Provenance(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldProvenance, v))
}

// BlockedReason applies equality check predicate on the "blocked_reason" field. It's identical to BlockedReasonEQ.
func BlockedReason(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldBlockedReason, v))
}

// TaskID applies equality check predicate on the "task_id" field. It's identical to TaskIDEQ.
func TaskID(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldTaskID, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContainsFold(FieldTitle, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContainsFold(FieldStatus, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLTE(FieldPosition, v))
}

// ProvenanceEQ applies the EQ predicate on the "provenance" field.
func ProvenanceEQ(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldProvenance, v))
}

// ProvenanceNEQ applies the NEQ predicate on the "provenance" field.
func ProvenanceNEQ(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNEQ(FieldProvenance, v))
}

// ProvenanceIn applies the In predicate on the "provenance" field.
func ProvenanceIn(vs ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldIn(FieldProvenance, vs...))
}

// ProvenanceNotIn applies the NotIn predicate on the "provenance" field.
func ProvenanceNotIn(vs ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNotIn(FieldProvenance, vs...))
}

// ProvenanceGT applies the GT predicate on the "provenance" field.
func ProvenanceGT(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGT(FieldProvenance, v))
}

// ProvenanceGTE applies the GTE predicate on the "provenance" field.
func ProvenanceGTE(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGTE(FieldProvenance, v))
}

// ProvenanceLT applies the LT predicate on the "provenance" field.
func ProvenanceLT(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLT(FieldProvenance, v))
}

// ProvenanceLTE applies the LTE predicate on the "provenance" field.
func ProvenanceLTE(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLTE(FieldProvenance, v))
}

// ProvenanceContains applies the Contains predicate on the "provenance" field.
func ProvenanceContains(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContains(FieldProvenance, v))
}

// ProvenanceHasPrefix applies the HasPrefix predicate on the "provenance" field.
func ProvenanceHasPrefix(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldHasPrefix(FieldProvenance, v))
}

// ProvenanceHasSuffix applies the HasSuffix predicate on the "provenance" field.
func ProvenanceHasSuffix(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldHasSuffix(FieldProvenance, v))
}

// ProvenanceEqualFold applies the EqualFold predicate on the "provenance" field.
func ProvenanceEqualFold(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEqualFold(FieldProvenance, v))
}

// ProvenanceContainsFold applies the ContainsFold predicate on the "provenance" field.
func ProvenanceContainsFold(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContainsFold(FieldProvenance, v))
}

// BlockedReasonEQ applies the EQ predicate on the "blocked_reason" field.
func BlockedReasonEQ(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldBlockedReason, v))
}

// BlockedReasonNEQ applies the NEQ predicate on the "blocked_reason" field.
func BlockedReasonNEQ(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNEQ(FieldBlockedReason, v))
}

// BlockedReasonIn applies the In predicate on the "blocked_reason" field.
func BlockedReasonIn(vs ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldIn(FieldBlockedReason, vs...))
}

// BlockedReasonNotIn applies the NotIn predicate on the "blocked_reason" field.
func BlockedReasonNotIn(vs ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNotIn(FieldBlockedReason, vs...))
}

// BlockedReasonGT applies the GT predicate on the "blocked_reason" field.
func BlockedReasonGT(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGT(FieldBlockedReason, v))
}

// BlockedReasonGTE applies the GTE predicate on the "blocked_reason" field.
func BlockedReasonGTE(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGTE(FieldBlockedReason, v))
}

// BlockedReasonLT applies the LT predicate on the "blocked_reason" field.
func BlockedReasonLT(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLT(FieldBlockedReason, v))
}

// BlockedReasonLTE applies the LTE predicate on the "blocked_reason" field.
func BlockedReasonLTE(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLTE(FieldBlockedReason, v))
}

// BlockedReasonContains applies the Contains predicate on the "blocked_reason" field.
func BlockedReasonContains(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContains(FieldBlockedReason, v))
}

// BlockedReasonHasPrefix applies the HasPrefix predicate on the "blocked_reason" field.
func BlockedReasonHasPrefix(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldHasPrefix(FieldBlockedReason, v))
}

// BlockedReasonHasSuffix applies the HasSuffix predicate on the "blocked_reason" field.
func BlockedReasonHasSuffix(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldHasSuffix(FieldBlockedReason, v))
}

// BlockedReasonEqualFold applies the EqualFold predicate on the "blocked_reason" field.
func BlockedReasonEqualFold(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEqualFold(FieldBlockedReason, v))
}

// BlockedReasonContainsFold applies the ContainsFold predicate on the "blocked_reason" field.
func BlockedReasonContainsFold(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContainsFold(FieldBlockedReason, v))
}

// TaskIDEQ applies the EQ predicate on the "task_id" field.
func TaskIDEQ(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldTaskID, v))
}

// TaskIDNEQ applies the NEQ predicate on the "task_id" field.
func TaskIDNEQ(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNEQ(FieldTaskID, v))
}

// TaskIDIn applies the In predicate on the "task_id" field.
func TaskIDIn(vs ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldIn(FieldTaskID, vs...))
}

// TaskIDNotIn applies the NotIn predicate on the "task_id" field.
func TaskIDNotIn(vs ...string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNotIn(FieldTaskID, vs...))
}

// TaskIDGT applies the GT predicate on the "task_id" field.
func TaskIDGT(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGT(FieldTaskID, v))
}

// TaskIDGTE applies the GTE predicate on the "task_id" field.
func TaskIDGTE(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGTE(FieldTaskID, v))
}

// TaskIDLT applies the LT predicate on the "task_id" field.
func TaskIDLT(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLT(FieldTaskID, v))
}

// TaskIDLTE applies the LTE predicate on the "task_id" field.
func TaskIDLTE(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLTE(FieldTaskID, v))
}

// TaskIDContains applies the Contains predicate on the "task_id" field.
func TaskIDContains(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContains(FieldTaskID, v))
}

// TaskIDHasPrefix applies the HasPrefix predicate on the "task_id" field.
func TaskIDHasPrefix(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldHasPrefix(FieldTaskID, v))
}

// TaskIDHasSuffix applies the HasSuffix predicate on the "task_id" field.
func TaskIDHasSuffix(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldHasSuffix(FieldTaskID, v))
}

// TaskIDIsNil applies the IsNil predicate on the "task_id" field.
func TaskIDIsNil() predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldIsNull(FieldTaskID))
}

// TaskIDNotNil applies the NotNil predicate on the "task_id" field.
func TaskIDNotNil() predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNotNull(FieldTaskID))
}

// TaskIDEqualFold applies the EqualFold predicate on the "task_id" field.
func TaskIDEqualFold(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEqualFold(FieldTaskID, v))
}

// TaskIDContainsFold applies the ContainsFold predicate on the "task_id" field.
func TaskIDContainsFold(v string) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldContainsFold(FieldTaskID, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasPhase applies the HasEdge predicate on the "phase" edge.
func HasPhase() predicate.RoadmapItem {
	return predicate.RoadmapItem(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, PhaseTable, PhaseColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPhaseWith applies the HasEdge predicate on the "phase" edge with a given conditions (other predicates).
func HasPhaseWith(preds ...predicate.RoadmapPhase) predicate.RoadmapItem {
	return predicate.RoadmapItem(func(s *sql.Selector) {
		step := newPhaseStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoadmapItem) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoadmapItem) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoadmapItem) predicate.RoadmapItem {
	return predicate.RoadmapItem(sql.NotPredicates(p))
}
