// Code generated by ent, DO NOT EDIT.

package hook

import (
	"context"
	"fmt"

	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent"
)

// The AgentCostTrendFunc type is an adapter to allow the use of ordinary
// function as AgentCostTrend mutator.
type AgentCostTrendFunc func(context.Context, *ent.AgentCostTrendMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentCostTrendFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentCostTrendMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentCostTrendMutation", m)
}

// The AgentProfileFunc type is an adapter to allow the use of ordinary
// function as AgentProfile mutator.
type AgentProfileFunc func(context.Context, *ent.AgentProfileMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AgentProfileFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AgentProfileMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AgentProfileMutation", m)
}

// The ApiKeyFunc type is an adapter to allow the use of ordinary
// function as ApiKey mutator.
type ApiKeyFunc func(context.Context, *ent.ApiKeyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ApiKeyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ApiKeyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ApiKeyMutation", m)
}

// The AppSettingFunc type is an adapter to allow the use of ordinary
// function as AppSetting mutator.
type AppSettingFunc func(context.Context, *ent.AppSettingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AppSettingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AppSettingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AppSettingMutation", m)
}

// The AuditEventFunc type is an adapter to allow the use of ordinary
// function as AuditEvent mutator.
type AuditEventFunc func(context.Context, *ent.AuditEventMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f AuditEventFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.AuditEventMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.AuditEventMutation", m)
}

// The CapabilityFunc type is an adapter to allow the use of ordinary
// function as Capability mutator.
type CapabilityFunc func(context.Context, *ent.CapabilityMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CapabilityFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CapabilityMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CapabilityMutation", m)
}

// The CheckpointFunc type is an adapter to allow the use of ordinary
// function as Checkpoint mutator.
type CheckpointFunc func(context.Context, *ent.CheckpointMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CheckpointFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CheckpointMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CheckpointMutation", m)
}

// The CoordLockFunc type is an adapter to allow the use of ordinary
// function as CoordLock mutator.
type CoordLockFunc func(context.Context, *ent.CoordLockMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f CoordLockFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.CoordLockMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.CoordLockMutation", m)
}

// The DriftAlertFunc type is an adapter to allow the use of ordinary
// function as DriftAlert mutator.
type DriftAlertFunc func(context.Context, *ent.DriftAlertMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f DriftAlertFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.DriftAlertMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.DriftAlertMutation", m)
}

// The EvalMetricSnapshotFunc type is an adapter to allow the use of ordinary
// function as EvalMetricSnapshot mutator.
type EvalMetricSnapshotFunc func(context.Context, *ent.EvalMetricSnapshotMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f EvalMetricSnapshotFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.EvalMetricSnapshotMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.EvalMetricSnapshotMutation", m)
}

// The GrantFunc type is an adapter to allow the use of ordinary
// function as Grant mutator.
type GrantFunc func(context.Context, *ent.GrantMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GrantFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GrantMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GrantMutation", m)
}

// The GrantUsageFunc type is an adapter to allow the use of ordinary
// function as GrantUsage mutator.
type GrantUsageFunc func(context.Context, *ent.GrantUsageMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f GrantUsageFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.GrantUsageMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.GrantUsageMutation", m)
}

// The ManagedAgentFunc type is an adapter to allow the use of ordinary
// function as ManagedAgent mutator.
type ManagedAgentFunc func(context.Context, *ent.ManagedAgentMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ManagedAgentFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ManagedAgentMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ManagedAgentMutation", m)
}

// The MaterializationFunc type is an adapter to allow the use of ordinary
// function as Materialization mutator.
type MaterializationFunc func(context.Context, *ent.MaterializationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MaterializationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MaterializationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MaterializationMutation", m)
}

// The MemoryEntryFunc type is an adapter to allow the use of ordinary
// function as MemoryEntry mutator.
type MemoryEntryFunc func(context.Context, *ent.MemoryEntryMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MemoryEntryFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MemoryEntryMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MemoryEntryMutation", m)
}

// The MemoryInjectionFunc type is an adapter to allow the use of ordinary
// function as MemoryInjection mutator.
type MemoryInjectionFunc func(context.Context, *ent.MemoryInjectionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f MemoryInjectionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.MemoryInjectionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.MemoryInjectionMutation", m)
}

// The PermissionPresetFunc type is an adapter to allow the use of ordinary
// function as PermissionPreset mutator.
type PermissionPresetFunc func(context.Context, *ent.PermissionPresetMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PermissionPresetFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PermissionPresetMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PermissionPresetMutation", m)
}

// The PermissionRequestFunc type is an adapter to allow the use of ordinary
// function as PermissionRequest mutator.
type PermissionRequestFunc func(context.Context, *ent.PermissionRequestMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PermissionRequestFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PermissionRequestMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PermissionRequestMutation", m)
}

// The PipelineConfigFunc type is an adapter to allow the use of ordinary
// function as PipelineConfig mutator.
type PipelineConfigFunc func(context.Context, *ent.PipelineConfigMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PipelineConfigFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PipelineConfigMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PipelineConfigMutation", m)
}

// The PluginFunc type is an adapter to allow the use of ordinary
// function as Plugin mutator.
type PluginFunc func(context.Context, *ent.PluginMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PluginFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PluginMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PluginMutation", m)
}

// The PluginSettingFunc type is an adapter to allow the use of ordinary
// function as PluginSetting mutator.
type PluginSettingFunc func(context.Context, *ent.PluginSettingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PluginSettingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PluginSettingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PluginSettingMutation", m)
}

// The ProjectFunc type is an adapter to allow the use of ordinary
// function as Project mutator.
type ProjectFunc func(context.Context, *ent.ProjectMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ProjectFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ProjectMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ProjectMutation", m)
}

// The ProjectFolderFunc type is an adapter to allow the use of ordinary
// function as ProjectFolder mutator.
type ProjectFolderFunc func(context.Context, *ent.ProjectFolderMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ProjectFolderFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ProjectFolderMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ProjectFolderMutation", m)
}

// The PromptTemplateFunc type is an adapter to allow the use of ordinary
// function as PromptTemplate mutator.
type PromptTemplateFunc func(context.Context, *ent.PromptTemplateMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f PromptTemplateFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.PromptTemplateMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.PromptTemplateMutation", m)
}

// The ProviderSettingFunc type is an adapter to allow the use of ordinary
// function as ProviderSetting mutator.
type ProviderSettingFunc func(context.Context, *ent.ProviderSettingMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ProviderSettingFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ProviderSettingMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ProviderSettingMutation", m)
}

// The RefinementTurnFunc type is an adapter to allow the use of ordinary
// function as RefinementTurn mutator.
type RefinementTurnFunc func(context.Context, *ent.RefinementTurnMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RefinementTurnFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RefinementTurnMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RefinementTurnMutation", m)
}

// The RemoteRegistrationFunc type is an adapter to allow the use of ordinary
// function as RemoteRegistration mutator.
type RemoteRegistrationFunc func(context.Context, *ent.RemoteRegistrationMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RemoteRegistrationFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RemoteRegistrationMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RemoteRegistrationMutation", m)
}

// The ResourceFunc type is an adapter to allow the use of ordinary
// function as Resource mutator.
type ResourceFunc func(context.Context, *ent.ResourceMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ResourceFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ResourceMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ResourceMutation", m)
}

// The RoadmapItemFunc type is an adapter to allow the use of ordinary
// function as RoadmapItem mutator.
type RoadmapItemFunc func(context.Context, *ent.RoadmapItemMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoadmapItemFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoadmapItemMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoadmapItemMutation", m)
}

// The RoadmapPhaseFunc type is an adapter to allow the use of ordinary
// function as RoadmapPhase mutator.
type RoadmapPhaseFunc func(context.Context, *ent.RoadmapPhaseMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoadmapPhaseFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoadmapPhaseMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoadmapPhaseMutation", m)
}

// The RoadmapProposalFunc type is an adapter to allow the use of ordinary
// function as RoadmapProposal mutator.
type RoadmapProposalFunc func(context.Context, *ent.RoadmapProposalMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f RoadmapProposalFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.RoadmapProposalMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.RoadmapProposalMutation", m)
}

// The ScratchpadFunc type is an adapter to allow the use of ordinary
// function as Scratchpad mutator.
type ScratchpadFunc func(context.Context, *ent.ScratchpadMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f ScratchpadFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.ScratchpadMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.ScratchpadMutation", m)
}

// The SkillFunc type is an adapter to allow the use of ordinary
// function as Skill mutator.
type SkillFunc func(context.Context, *ent.SkillMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SkillFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SkillMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SkillMutation", m)
}

// The SpawnerFunc type is an adapter to allow the use of ordinary
// function as Spawner mutator.
type SpawnerFunc func(context.Context, *ent.SpawnerMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SpawnerFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SpawnerMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SpawnerMutation", m)
}

// The StageRunFunc type is an adapter to allow the use of ordinary
// function as StageRun mutator.
type StageRunFunc func(context.Context, *ent.StageRunMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f StageRunFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.StageRunMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.StageRunMutation", m)
}

// The SystemPromptFunc type is an adapter to allow the use of ordinary
// function as SystemPrompt mutator.
type SystemPromptFunc func(context.Context, *ent.SystemPromptMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f SystemPromptFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.SystemPromptMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.SystemPromptMutation", m)
}

// The TaskFunc type is an adapter to allow the use of ordinary
// function as Task mutator.
type TaskFunc func(context.Context, *ent.TaskMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TaskFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TaskMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TaskMutation", m)
}

// The TaskDependencyFunc type is an adapter to allow the use of ordinary
// function as TaskDependency mutator.
type TaskDependencyFunc func(context.Context, *ent.TaskDependencyMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TaskDependencyFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TaskDependencyMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TaskDependencyMutation", m)
}

// The TaskPermissionFunc type is an adapter to allow the use of ordinary
// function as TaskPermission mutator.
type TaskPermissionFunc func(context.Context, *ent.TaskPermissionMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TaskPermissionFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TaskPermissionMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TaskPermissionMutation", m)
}

// The TaskScheduleFunc type is an adapter to allow the use of ordinary
// function as TaskSchedule mutator.
type TaskScheduleFunc func(context.Context, *ent.TaskScheduleMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f TaskScheduleFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.TaskScheduleMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.TaskScheduleMutation", m)
}

// The UserFunc type is an adapter to allow the use of ordinary
// function as User mutator.
type UserFunc func(context.Context, *ent.UserMutation) (ent.Value, error)

// Mutate calls f(ctx, m).
func (f UserFunc) Mutate(ctx context.Context, m ent.Mutation) (ent.Value, error) {
	if mv, ok := m.(*ent.UserMutation); ok {
		return f(ctx, mv)
	}
	return nil, fmt.Errorf("unexpected mutation type %T. expect *ent.UserMutation", m)
}

// Condition is a hook condition function.
type Condition func(context.Context, ent.Mutation) bool

// And groups conditions with the AND operator.
func And(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if !first(ctx, m) || !second(ctx, m) {
			return false
		}
		for _, cond := range rest {
			if !cond(ctx, m) {
				return false
			}
		}
		return true
	}
}

// Or groups conditions with the OR operator.
func Or(first, second Condition, rest ...Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		if first(ctx, m) || second(ctx, m) {
			return true
		}
		for _, cond := range rest {
			if cond(ctx, m) {
				return true
			}
		}
		return false
	}
}

// Not negates a given condition.
func Not(cond Condition) Condition {
	return func(ctx context.Context, m ent.Mutation) bool {
		return !cond(ctx, m)
	}
}

// HasOp is a condition testing mutation operation.
func HasOp(op ent.Op) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		return m.Op().Is(op)
	}
}

// HasAddedFields is a condition validating `.AddedField` on fields.
func HasAddedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.AddedField(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.AddedField(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasClearedFields is a condition validating `.FieldCleared` on fields.
func HasClearedFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if exists := m.FieldCleared(field); !exists {
			return false
		}
		for _, field := range fields {
			if exists := m.FieldCleared(field); !exists {
				return false
			}
		}
		return true
	}
}

// HasFields is a condition validating `.Field` on fields.
func HasFields(field string, fields ...string) Condition {
	return func(_ context.Context, m ent.Mutation) bool {
		if _, exists := m.Field(field); !exists {
			return false
		}
		for _, field := range fields {
			if _, exists := m.Field(field); !exists {
				return false
			}
		}
		return true
	}
}

// If executes the given hook under condition.
//
//	hook.If(ComputeAverage, And(HasFields(...), HasAddedFields(...)))
func If(hk ent.Hook, cond Condition) ent.Hook {
	return func(next ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(ctx context.Context, m ent.Mutation) (ent.Value, error) {
			if cond(ctx, m) {
				return hk(next).Mutate(ctx, m)
			}
			return next.Mutate(ctx, m)
		})
	}
}

// On executes the given hook only for the given operation.
//
//	hook.On(Log, ent.Delete|ent.Create)
func On(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, HasOp(op))
}

// Unless skips the given hook only for the given operation.
//
//	hook.Unless(Log, ent.Update|ent.UpdateOne)
func Unless(hk ent.Hook, op ent.Op) ent.Hook {
	return If(hk, Not(HasOp(op)))
}

// FixedError is a hook returning a fixed error.
func FixedError(err error) ent.Hook {
	return func(ent.Mutator) ent.Mutator {
		return ent.MutateFunc(func(context.Context, ent.Mutation) (ent.Value, error) {
			return nil, err
		})
	}
}

// Reject returns a hook that rejects all operations that match op.
//
//	func (T) Hooks() []ent.Hook {
//		return []ent.Hook{
//			Reject(ent.Delete|ent.Update),
//		}
//	}
func Reject(op ent.Op) ent.Hook {
	hk := FixedError(fmt.Errorf("%s operation is not allowed", op))
	return On(hk, op)
}

// Chain acts as a list of hooks and is effectively immutable.
// Once created, it will always hold the same set of hooks in the same order.
type Chain struct {
	hooks []ent.Hook
}

// NewChain creates a new chain of hooks.
func NewChain(hooks ...ent.Hook) Chain {
	return Chain{append([]ent.Hook(nil), hooks...)}
}

// Hook chains the list of hooks and returns the final hook.
func (c Chain) Hook() ent.Hook {
	return func(mutator ent.Mutator) ent.Mutator {
		for i := len(c.hooks) - 1; i >= 0; i-- {
			mutator = c.hooks[i](mutator)
		}
		return mutator
	}
}

// Append extends a chain, adding the specified hook
// as the last ones in the mutation flow.
func (c Chain) Append(hooks ...ent.Hook) Chain {
	newHooks := make([]ent.Hook, 0, len(c.hooks)+len(hooks))
	newHooks = append(newHooks, c.hooks...)
	newHooks = append(newHooks, hooks...)
	return Chain{newHooks}
}

// Extend extends a chain, adding the specified chain
// as the last ones in the mutation flow.
func (c Chain) Extend(chain Chain) Chain {
	return c.Append(chain.hooks...)
}
