// Code generated by ent, DO NOT EDIT.

package stagerun

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the stagerun type in the database.
	Label = "stage_run"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTaskID holds the string denoting the task_id field in the database.
	FieldTaskID = "task_id"
	// FieldStage holds the string denoting the stage field in the database.
	FieldStage = "stage"
	// FieldSessionID holds the string denoting the session_id field in the database.
	FieldSessionID = "session_id"
	// FieldSessionName holds the string denoting the session_name field in the database.
	FieldSessionName = "session_name"
	// FieldPid holds the string denoting the pid field in the database.
	FieldPid = "pid"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldIteration holds the string denoting the iteration field in the database.
	FieldIteration = "iteration"
	// FieldOutput holds the string denoting the output field in the database.
	FieldOutput = "output"
	// FieldTokensUsed holds the string denoting the tokens_used field in the database.
	FieldTokensUsed = "tokens_used"
	// FieldCostCents holds the string denoting the cost_cents field in the database.
	FieldCostCents = "cost_cents"
	// FieldStartedAt holds the string denoting the started_at field in the database.
	FieldStartedAt = "started_at"
	// FieldEndedAt holds the string denoting the ended_at field in the database.
	FieldEndedAt = "ended_at"
	// FieldLastGrantAt holds the string denoting the last_grant_at field in the database.
	FieldLastGrantAt = "last_grant_at"
	// FieldRetryCount holds the string denoting the retry_count field in the database.
	FieldRetryCount = "retry_count"
	// FieldNextRetryAt holds the string denoting the next_retry_at field in the database.
	FieldNextRetryAt = "next_retry_at"
	// FieldPendingUserPrompt holds the string denoting the pending_user_prompt field in the database.
	FieldPendingUserPrompt = "pending_user_prompt"
	// FieldFailureCategory holds the string denoting the failure_category field in the database.
	FieldFailureCategory = "failure_category"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeTask holds the string denoting the task edge name in mutations.
	EdgeTask = "task"
	// EdgePermissionRequests holds the string denoting the permission_requests edge name in mutations.
	EdgePermissionRequests = "permission_requests"
	// Table holds the table name of the stagerun in the database.
	Table = "stage_runs"
	// TaskTable is the table that holds the task relation/edge.
	TaskTable = "stage_runs"
	// TaskInverseTable is the table name for the Task entity.
	// It exists in this package in order to avoid circular dependency with the "task" package.
	TaskInverseTable = "tasks"
	// TaskColumn is the table column denoting the task relation/edge.
	TaskColumn = "task_id"
	// PermissionRequestsTable is the table that holds the permission_requests relation/edge.
	PermissionRequestsTable = "permission_requests"
	// PermissionRequestsInverseTable is the table name for the PermissionRequest entity.
	// It exists in this package in order to avoid circular dependency with the "permissionrequest" package.
	PermissionRequestsInverseTable = "permission_requests"
	// PermissionRequestsColumn is the table column denoting the permission_requests relation/edge.
	PermissionRequestsColumn = "stage_run_id"
)

// Columns holds all SQL columns for stagerun fields.
var Columns = []string{
	FieldID,
	FieldTaskID,
	FieldStage,
	FieldSessionID,
	FieldSessionName,
	FieldPid,
	FieldStatus,
	FieldIteration,
	FieldOutput,
	FieldTokensUsed,
	FieldCostCents,
	FieldStartedAt,
	FieldEndedAt,
	FieldLastGrantAt,
	FieldRetryCount,
	FieldNextRetryAt,
	FieldPendingUserPrompt,
	FieldFailureCategory,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultStatus holds the default value on creation for the "status" field.
	DefaultStatus string
	// DefaultIteration holds the default value on creation for the "iteration" field.
	DefaultIteration int
	// DefaultTokensUsed holds the default value on creation for the "tokens_used" field.
	DefaultTokensUsed int
	// DefaultCostCents holds the default value on creation for the "cost_cents" field.
	DefaultCostCents int
	// DefaultRetryCount holds the default value on creation for the "retry_count" field.
	DefaultRetryCount int
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
)

// OrderOption defines the ordering options for the StageRun queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTaskID orders the results by the task_id field.
func ByTaskID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTaskID, opts...).ToFunc()
}

// ByStage orders the results by the stage field.
func ByStage(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStage, opts...).ToFunc()
}

// BySessionID orders the results by the session_id field.
func BySessionID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionID, opts...).ToFunc()
}

// BySessionName orders the results by the session_name field.
func BySessionName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSessionName, opts...).ToFunc()
}

// ByPid orders the results by the pid field.
func ByPid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPid, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByIteration orders the results by the iteration field.
func ByIteration(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIteration, opts...).ToFunc()
}

// ByTokensUsed orders the results by the tokens_used field.
func ByTokensUsed(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTokensUsed, opts...).ToFunc()
}

// ByCostCents orders the results by the cost_cents field.
func ByCostCents(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCostCents, opts...).ToFunc()
}

// ByStartedAt orders the results by the started_at field.
func ByStartedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStartedAt, opts...).ToFunc()
}

// ByEndedAt orders the results by the ended_at field.
func ByEndedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEndedAt, opts...).ToFunc()
}

// ByLastGrantAt orders the results by the last_grant_at field.
func ByLastGrantAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastGrantAt, opts...).ToFunc()
}

// ByRetryCount orders the results by the retry_count field.
func ByRetryCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRetryCount, opts...).ToFunc()
}

// ByNextRetryAt orders the results by the next_retry_at field.
func ByNextRetryAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldNextRetryAt, opts...).ToFunc()
}

// ByPendingUserPrompt orders the results by the pending_user_prompt field.
func ByPendingUserPrompt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPendingUserPrompt, opts...).ToFunc()
}

// ByFailureCategory orders the results by the failure_category field.
func ByFailureCategory(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFailureCategory, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByTaskField orders the results by task field.
func ByTaskField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newTaskStep(), sql.OrderByField(field, opts...))
	}
}

// ByPermissionRequestsCount orders the results by permission_requests count.
func ByPermissionRequestsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPermissionRequestsStep(), opts...)
	}
}

// ByPermissionRequests orders the results by permission_requests terms.
func ByPermissionRequests(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPermissionRequestsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newTaskStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(TaskInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, TaskTable, TaskColumn),
	)
}
func newPermissionRequestsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PermissionRequestsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, PermissionRequestsTable, PermissionRequestsColumn),
	)
}
