// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/dashboardagent"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
)

// DashboardAgentUpdate is the builder for updating DashboardAgent entities.
type DashboardAgentUpdate struct {
	config
	hooks    []Hook
	mutation *DashboardAgentMutation
}

// Where appends a list predicates to the DashboardAgentUpdate builder.
func (_u *DashboardAgentUpdate) Where(ps ...predicate.DashboardAgent) *DashboardAgentUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetDisplayName sets the "display_name" field.
func (_u *DashboardAgentUpdate) SetDisplayName(v string) *DashboardAgentUpdate {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *DashboardAgentUpdate) SetNillableDisplayName(v *string) *DashboardAgentUpdate {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *DashboardAgentUpdate) SetCategory(v string) *DashboardAgentUpdate {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *DashboardAgentUpdate) SetNillableCategory(v *string) *DashboardAgentUpdate {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetInstructions sets the "instructions" field.
func (_u *DashboardAgentUpdate) SetInstructions(v string) *DashboardAgentUpdate {
	_u.mutation.SetInstructions(v)
	return _u
}

// SetNillableInstructions sets the "instructions" field if the given value is not nil.
func (_u *DashboardAgentUpdate) SetNillableInstructions(v *string) *DashboardAgentUpdate {
	if v != nil {
		_u.SetInstructions(*v)
	}
	return _u
}

// SetPermissionMode sets the "permission_mode" field.
func (_u *DashboardAgentUpdate) SetPermissionMode(v string) *DashboardAgentUpdate {
	_u.mutation.SetPermissionMode(v)
	return _u
}

// SetNillablePermissionMode sets the "permission_mode" field if the given value is not nil.
func (_u *DashboardAgentUpdate) SetNillablePermissionMode(v *string) *DashboardAgentUpdate {
	if v != nil {
		_u.SetPermissionMode(*v)
	}
	return _u
}

// SetCwd sets the "cwd" field.
func (_u *DashboardAgentUpdate) SetCwd(v string) *DashboardAgentUpdate {
	_u.mutation.SetCwd(v)
	return _u
}

// SetNillableCwd sets the "cwd" field if the given value is not nil.
func (_u *DashboardAgentUpdate) SetNillableCwd(v *string) *DashboardAgentUpdate {
	if v != nil {
		_u.SetCwd(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *DashboardAgentUpdate) SetProjectID(v string) *DashboardAgentUpdate {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *DashboardAgentUpdate) SetNillableProjectID(v *string) *DashboardAgentUpdate {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *DashboardAgentUpdate) SetRole(v string) *DashboardAgentUpdate {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *DashboardAgentUpdate) SetNillableRole(v *string) *DashboardAgentUpdate {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *DashboardAgentUpdate) SetSessionID(v string) *DashboardAgentUpdate {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *DashboardAgentUpdate) SetNillableSessionID(v *string) *DashboardAgentUpdate {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DashboardAgentUpdate) SetUpdatedAt(v time.Time) *DashboardAgentUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DashboardAgentMutation object of the builder.
func (_u *DashboardAgentUpdate) Mutation() *DashboardAgentMutation {
	return _u.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *DashboardAgentUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DashboardAgentUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *DashboardAgentUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DashboardAgentUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DashboardAgentUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dashboardagent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DashboardAgentUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(dashboardagent.Table, dashboardagent.Columns, sqlgraph.NewFieldSpec(dashboardagent.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(dashboardagent.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(dashboardagent.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Instructions(); ok {
		_spec.SetField(dashboardagent.FieldInstructions, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionMode(); ok {
		_spec.SetField(dashboardagent.FieldPermissionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cwd(); ok {
		_spec.SetField(dashboardagent.FieldCwd, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(dashboardagent.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(dashboardagent.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(dashboardagent.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dashboardagent.FieldUpdatedAt, field.TypeTime, value)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dashboardagent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// DashboardAgentUpdateOne is the builder for updating a single DashboardAgent entity.
type DashboardAgentUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *DashboardAgentMutation
}

// SetDisplayName sets the "display_name" field.
func (_u *DashboardAgentUpdateOne) SetDisplayName(v string) *DashboardAgentUpdateOne {
	_u.mutation.SetDisplayName(v)
	return _u
}

// SetNillableDisplayName sets the "display_name" field if the given value is not nil.
func (_u *DashboardAgentUpdateOne) SetNillableDisplayName(v *string) *DashboardAgentUpdateOne {
	if v != nil {
		_u.SetDisplayName(*v)
	}
	return _u
}

// SetCategory sets the "category" field.
func (_u *DashboardAgentUpdateOne) SetCategory(v string) *DashboardAgentUpdateOne {
	_u.mutation.SetCategory(v)
	return _u
}

// SetNillableCategory sets the "category" field if the given value is not nil.
func (_u *DashboardAgentUpdateOne) SetNillableCategory(v *string) *DashboardAgentUpdateOne {
	if v != nil {
		_u.SetCategory(*v)
	}
	return _u
}

// SetInstructions sets the "instructions" field.
func (_u *DashboardAgentUpdateOne) SetInstructions(v string) *DashboardAgentUpdateOne {
	_u.mutation.SetInstructions(v)
	return _u
}

// SetNillableInstructions sets the "instructions" field if the given value is not nil.
func (_u *DashboardAgentUpdateOne) SetNillableInstructions(v *string) *DashboardAgentUpdateOne {
	if v != nil {
		_u.SetInstructions(*v)
	}
	return _u
}

// SetPermissionMode sets the "permission_mode" field.
func (_u *DashboardAgentUpdateOne) SetPermissionMode(v string) *DashboardAgentUpdateOne {
	_u.mutation.SetPermissionMode(v)
	return _u
}

// SetNillablePermissionMode sets the "permission_mode" field if the given value is not nil.
func (_u *DashboardAgentUpdateOne) SetNillablePermissionMode(v *string) *DashboardAgentUpdateOne {
	if v != nil {
		_u.SetPermissionMode(*v)
	}
	return _u
}

// SetCwd sets the "cwd" field.
func (_u *DashboardAgentUpdateOne) SetCwd(v string) *DashboardAgentUpdateOne {
	_u.mutation.SetCwd(v)
	return _u
}

// SetNillableCwd sets the "cwd" field if the given value is not nil.
func (_u *DashboardAgentUpdateOne) SetNillableCwd(v *string) *DashboardAgentUpdateOne {
	if v != nil {
		_u.SetCwd(*v)
	}
	return _u
}

// SetProjectID sets the "project_id" field.
func (_u *DashboardAgentUpdateOne) SetProjectID(v string) *DashboardAgentUpdateOne {
	_u.mutation.SetProjectID(v)
	return _u
}

// SetNillableProjectID sets the "project_id" field if the given value is not nil.
func (_u *DashboardAgentUpdateOne) SetNillableProjectID(v *string) *DashboardAgentUpdateOne {
	if v != nil {
		_u.SetProjectID(*v)
	}
	return _u
}

// SetRole sets the "role" field.
func (_u *DashboardAgentUpdateOne) SetRole(v string) *DashboardAgentUpdateOne {
	_u.mutation.SetRole(v)
	return _u
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_u *DashboardAgentUpdateOne) SetNillableRole(v *string) *DashboardAgentUpdateOne {
	if v != nil {
		_u.SetRole(*v)
	}
	return _u
}

// SetSessionID sets the "session_id" field.
func (_u *DashboardAgentUpdateOne) SetSessionID(v string) *DashboardAgentUpdateOne {
	_u.mutation.SetSessionID(v)
	return _u
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_u *DashboardAgentUpdateOne) SetNillableSessionID(v *string) *DashboardAgentUpdateOne {
	if v != nil {
		_u.SetSessionID(*v)
	}
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *DashboardAgentUpdateOne) SetUpdatedAt(v time.Time) *DashboardAgentUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// Mutation returns the DashboardAgentMutation object of the builder.
func (_u *DashboardAgentUpdateOne) Mutation() *DashboardAgentMutation {
	return _u.mutation
}

// Where appends a list predicates to the DashboardAgentUpdate builder.
func (_u *DashboardAgentUpdateOne) Where(ps ...predicate.DashboardAgent) *DashboardAgentUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *DashboardAgentUpdateOne) Select(field string, fields ...string) *DashboardAgentUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated DashboardAgent entity.
func (_u *DashboardAgentUpdateOne) Save(ctx context.Context) (*DashboardAgent, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *DashboardAgentUpdateOne) SaveX(ctx context.Context) *DashboardAgent {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *DashboardAgentUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *DashboardAgentUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *DashboardAgentUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := dashboardagent.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

func (_u *DashboardAgentUpdateOne) sqlSave(ctx context.Context) (_node *DashboardAgent, err error) {
	_spec := sqlgraph.NewUpdateSpec(dashboardagent.Table, dashboardagent.Columns, sqlgraph.NewFieldSpec(dashboardagent.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "DashboardAgent.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, dashboardagent.FieldID)
		for _, f := range fields {
			if !dashboardagent.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != dashboardagent.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.DisplayName(); ok {
		_spec.SetField(dashboardagent.FieldDisplayName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Category(); ok {
		_spec.SetField(dashboardagent.FieldCategory, field.TypeString, value)
	}
	if value, ok := _u.mutation.Instructions(); ok {
		_spec.SetField(dashboardagent.FieldInstructions, field.TypeString, value)
	}
	if value, ok := _u.mutation.PermissionMode(); ok {
		_spec.SetField(dashboardagent.FieldPermissionMode, field.TypeString, value)
	}
	if value, ok := _u.mutation.Cwd(); ok {
		_spec.SetField(dashboardagent.FieldCwd, field.TypeString, value)
	}
	if value, ok := _u.mutation.ProjectID(); ok {
		_spec.SetField(dashboardagent.FieldProjectID, field.TypeString, value)
	}
	if value, ok := _u.mutation.Role(); ok {
		_spec.SetField(dashboardagent.FieldRole, field.TypeString, value)
	}
	if value, ok := _u.mutation.SessionID(); ok {
		_spec.SetField(dashboardagent.FieldSessionID, field.TypeString, value)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(dashboardagent.FieldUpdatedAt, field.TypeTime, value)
	}
	_node = &DashboardAgent{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{dashboardagent.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
