// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/managedagent"
)

// ManagedAgent is the model entity for the ManagedAgent schema.
type ManagedAgent struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Pid holds the value of the "pid" field.
	Pid int `json:"pid,omitempty"`
	// Cwd holds the value of the "cwd" field.
	Cwd string `json:"cwd,omitempty"`
	// WorkspaceCreated holds the value of the "workspace_created" field.
	WorkspaceCreated bool `json:"workspace_created,omitempty"`
	// AllowedFolder holds the value of the "allowed_folder" field.
	AllowedFolder string `json:"allowed_folder,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt    time.Time `json:"updated_at,omitempty"`
	selectValues sql.SelectValues
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ManagedAgent) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case managedagent.FieldWorkspaceCreated:
			values[i] = new(sql.NullBool)
		case managedagent.FieldPid:
			values[i] = new(sql.NullInt64)
		case managedagent.FieldID, managedagent.FieldCwd, managedagent.FieldAllowedFolder:
			values[i] = new(sql.NullString)
		case managedagent.FieldCreatedAt, managedagent.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ManagedAgent fields.
func (_m *ManagedAgent) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case managedagent.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case managedagent.FieldPid:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field pid", values[i])
			} else if value.Valid {
				_m.Pid = int(value.Int64)
			}
		case managedagent.FieldCwd:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field cwd", values[i])
			} else if value.Valid {
				_m.Cwd = value.String
			}
		case managedagent.FieldWorkspaceCreated:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field workspace_created", values[i])
			} else if value.Valid {
				_m.WorkspaceCreated = value.Bool
			}
		case managedagent.FieldAllowedFolder:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field allowed_folder", values[i])
			} else if value.Valid {
				_m.AllowedFolder = value.String
			}
		case managedagent.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case managedagent.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ManagedAgent.
// This includes values selected through modifiers, order, etc.
func (_m *ManagedAgent) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// Update returns a builder for updating this ManagedAgent.
// Note that you need to call ManagedAgent.Unwrap() before calling this method if this ManagedAgent
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ManagedAgent) Update() *ManagedAgentUpdateOne {
	return NewManagedAgentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ManagedAgent entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ManagedAgent) Unwrap() *ManagedAgent {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ManagedAgent is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ManagedAgent) String() string {
	var builder strings.Builder
	builder.WriteString("ManagedAgent(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("pid=")
	builder.WriteString(fmt.Sprintf("%v", _m.Pid))
	builder.WriteString(", ")
	builder.WriteString("cwd=")
	builder.WriteString(_m.Cwd)
	builder.WriteString(", ")
	builder.WriteString("workspace_created=")
	builder.WriteString(fmt.Sprintf("%v", _m.WorkspaceCreated))
	builder.WriteString(", ")
	builder.WriteString("allowed_folder=")
	builder.WriteString(_m.AllowedFolder)
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// ManagedAgents is a parsable slice of ManagedAgent.
type ManagedAgents []*ManagedAgent
