// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/managedagent"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
)

// ManagedAgentDelete is the builder for deleting a ManagedAgent entity.
type ManagedAgentDelete struct {
	config
	hooks    []Hook
	mutation *ManagedAgentMutation
}

// Where appends a list predicates to the ManagedAgentDelete builder.
func (_d *ManagedAgentDelete) Where(ps ...predicate.ManagedAgent) *ManagedAgentDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *ManagedAgentDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ManagedAgentDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *ManagedAgentDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(managedagent.Table, sqlgraph.NewFieldSpec(managedagent.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// ManagedAgentDeleteOne is the builder for deleting a single ManagedAgent entity.
type ManagedAgentDeleteOne struct {
	_d *ManagedAgentDelete
}

// Where appends a list predicates to the ManagedAgentDelete builder.
func (_d *ManagedAgentDeleteOne) Where(ps ...predicate.ManagedAgent) *ManagedAgentDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *ManagedAgentDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{managedagent.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *ManagedAgentDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
