// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/project"
)

// Project is the model entity for the Project schema.
type Project struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Slug holds the value of the "slug" field.
	Slug string `json:"slug,omitempty"`
	// Name holds the value of the "name" field.
	Name string `json:"name,omitempty"`
	// Description holds the value of the "description" field.
	Description *string `json:"description,omitempty"`
	// Color holds the value of the "color" field.
	Color *string `json:"color,omitempty"`
	// DefaultSpawnerID holds the value of the "default_spawner_id" field.
	DefaultSpawnerID *string `json:"default_spawner_id,omitempty"`
	// SetupCommand holds the value of the "setup_command" field.
	SetupCommand *string `json:"setup_command,omitempty"`
	// Objective holds the value of the "objective" field.
	Objective *string `json:"objective,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ProjectQuery when eager-loading is set.
	Edges        ProjectEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ProjectEdges holds the relations/edges for other nodes in the graph.
type ProjectEdges struct {
	// Folders holds the value of the folders edge.
	Folders []*ProjectFolder `json:"folders,omitempty"`
	// RoadmapPhases holds the value of the roadmap_phases edge.
	RoadmapPhases []*RoadmapPhase `json:"roadmap_phases,omitempty"`
	// RoadmapProposals holds the value of the roadmap_proposals edge.
	RoadmapProposals []*RoadmapProposal `json:"roadmap_proposals,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// FoldersOrErr returns the Folders value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) FoldersOrErr() ([]*ProjectFolder, error) {
	if e.loadedTypes[0] {
		return e.Folders, nil
	}
	return nil, &NotLoadedError{edge: "folders"}
}

// RoadmapPhasesOrErr returns the RoadmapPhases value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) RoadmapPhasesOrErr() ([]*RoadmapPhase, error) {
	if e.loadedTypes[1] {
		return e.RoadmapPhases, nil
	}
	return nil, &NotLoadedError{edge: "roadmap_phases"}
}

// RoadmapProposalsOrErr returns the RoadmapProposals value or an error if the edge
// was not loaded in eager-loading.
func (e ProjectEdges) RoadmapProposalsOrErr() ([]*RoadmapProposal, error) {
	if e.loadedTypes[2] {
		return e.RoadmapProposals, nil
	}
	return nil, &NotLoadedError{edge: "roadmap_proposals"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Project) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case project.FieldID, project.FieldSlug, project.FieldName, project.FieldDescription, project.FieldColor, project.FieldDefaultSpawnerID, project.FieldSetupCommand, project.FieldObjective:
			values[i] = new(sql.NullString)
		case project.FieldCreatedAt, project.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Project fields.
func (_m *Project) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case project.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case project.FieldSlug:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field slug", values[i])
			} else if value.Valid {
				_m.Slug = value.String
			}
		case project.FieldName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field name", values[i])
			} else if value.Valid {
				_m.Name = value.String
			}
		case project.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = new(string)
				*_m.Description = value.String
			}
		case project.FieldColor:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field color", values[i])
			} else if value.Valid {
				_m.Color = new(string)
				*_m.Color = value.String
			}
		case project.FieldDefaultSpawnerID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field default_spawner_id", values[i])
			} else if value.Valid {
				_m.DefaultSpawnerID = new(string)
				*_m.DefaultSpawnerID = value.String
			}
		case project.FieldSetupCommand:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field setup_command", values[i])
			} else if value.Valid {
				_m.SetupCommand = new(string)
				*_m.SetupCommand = value.String
			}
		case project.FieldObjective:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field objective", values[i])
			} else if value.Valid {
				_m.Objective = new(string)
				*_m.Objective = value.String
			}
		case project.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case project.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Project.
// This includes values selected through modifiers, order, etc.
func (_m *Project) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFolders queries the "folders" edge of the Project entity.
func (_m *Project) QueryFolders() *ProjectFolderQuery {
	return NewProjectClient(_m.config).QueryFolders(_m)
}

// QueryRoadmapPhases queries the "roadmap_phases" edge of the Project entity.
func (_m *Project) QueryRoadmapPhases() *RoadmapPhaseQuery {
	return NewProjectClient(_m.config).QueryRoadmapPhases(_m)
}

// QueryRoadmapProposals queries the "roadmap_proposals" edge of the Project entity.
func (_m *Project) QueryRoadmapProposals() *RoadmapProposalQuery {
	return NewProjectClient(_m.config).QueryRoadmapProposals(_m)
}

// Update returns a builder for updating this Project.
// Note that you need to call Project.Unwrap() before calling this method if this Project
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Project) Update() *ProjectUpdateOne {
	return NewProjectClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Project entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Project) Unwrap() *Project {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Project is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Project) String() string {
	var builder strings.Builder
	builder.WriteString("Project(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("slug=")
	builder.WriteString(_m.Slug)
	builder.WriteString(", ")
	builder.WriteString("name=")
	builder.WriteString(_m.Name)
	builder.WriteString(", ")
	if v := _m.Description; v != nil {
		builder.WriteString("description=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Color; v != nil {
		builder.WriteString("color=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.DefaultSpawnerID; v != nil {
		builder.WriteString("default_spawner_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.SetupCommand; v != nil {
		builder.WriteString("setup_command=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Objective; v != nil {
		builder.WriteString("objective=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Projects is a parsable slice of Project.
type Projects []*Project
