// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/project"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/roadmapproposal"
)

// RoadmapProposal is the model entity for the RoadmapProposal schema.
type RoadmapProposal struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Source holds the value of the "source" field.
	Source string `json:"source,omitempty"`
	// AgentSessionID holds the value of the "agent_session_id" field.
	AgentSessionID *string `json:"agent_session_id,omitempty"`
	// Summary holds the value of the "summary" field.
	Summary string `json:"summary,omitempty"`
	// Payload holds the value of the "payload" field.
	Payload map[string]interface{} `json:"payload,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// DecidedAt holds the value of the "decided_at" field.
	DecidedAt *time.Time `json:"decided_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoadmapProposalQuery when eager-loading is set.
	Edges                     RoadmapProposalEdges `json:"edges"`
	project_roadmap_proposals *string
	selectValues              sql.SelectValues
}

// RoadmapProposalEdges holds the relations/edges for other nodes in the graph.
type RoadmapProposalEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RoadmapProposalEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RoadmapProposal) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case roadmapproposal.FieldPayload:
			values[i] = new([]byte)
		case roadmapproposal.FieldID, roadmapproposal.FieldStatus, roadmapproposal.FieldSource, roadmapproposal.FieldAgentSessionID, roadmapproposal.FieldSummary:
			values[i] = new(sql.NullString)
		case roadmapproposal.FieldCreatedAt, roadmapproposal.FieldDecidedAt:
			values[i] = new(sql.NullTime)
		case roadmapproposal.ForeignKeys[0]: // project_roadmap_proposals
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RoadmapProposal fields.
func (_m *RoadmapProposal) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case roadmapproposal.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case roadmapproposal.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case roadmapproposal.FieldSource:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field source", values[i])
			} else if value.Valid {
				_m.Source = value.String
			}
		case roadmapproposal.FieldAgentSessionID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field agent_session_id", values[i])
			} else if value.Valid {
				_m.AgentSessionID = new(string)
				*_m.AgentSessionID = value.String
			}
		case roadmapproposal.FieldSummary:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field summary", values[i])
			} else if value.Valid {
				_m.Summary = value.String
			}
		case roadmapproposal.FieldPayload:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field payload", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.Payload); err != nil {
					return fmt.Errorf("unmarshal field payload: %w", err)
				}
			}
		case roadmapproposal.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case roadmapproposal.FieldDecidedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field decided_at", values[i])
			} else if value.Valid {
				_m.DecidedAt = new(time.Time)
				*_m.DecidedAt = value.Time
			}
		case roadmapproposal.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_roadmap_proposals", values[i])
			} else if value.Valid {
				_m.project_roadmap_proposals = new(string)
				*_m.project_roadmap_proposals = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RoadmapProposal.
// This includes values selected through modifiers, order, etc.
func (_m *RoadmapProposal) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the RoadmapProposal entity.
func (_m *RoadmapProposal) QueryProject() *ProjectQuery {
	return NewRoadmapProposalClient(_m.config).QueryProject(_m)
}

// Update returns a builder for updating this RoadmapProposal.
// Note that you need to call RoadmapProposal.Unwrap() before calling this method if this RoadmapProposal
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RoadmapProposal) Update() *RoadmapProposalUpdateOne {
	return NewRoadmapProposalClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RoadmapProposal entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RoadmapProposal) Unwrap() *RoadmapProposal {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RoadmapProposal is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RoadmapProposal) String() string {
	var builder strings.Builder
	builder.WriteString("RoadmapProposal(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("source=")
	builder.WriteString(_m.Source)
	builder.WriteString(", ")
	if v := _m.AgentSessionID; v != nil {
		builder.WriteString("agent_session_id=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("summary=")
	builder.WriteString(_m.Summary)
	builder.WriteString(", ")
	builder.WriteString("payload=")
	builder.WriteString(fmt.Sprintf("%v", _m.Payload))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.DecidedAt; v != nil {
		builder.WriteString("decided_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteByte(')')
	return builder.String()
}

// RoadmapProposals is a parsable slice of RoadmapProposal.
type RoadmapProposals []*RoadmapProposal
