// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/project"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/roadmapproposal"
)

// RoadmapProposalUpdate is the builder for updating RoadmapProposal entities.
type RoadmapProposalUpdate struct {
	config
	hooks    []Hook
	mutation *RoadmapProposalMutation
}

// Where appends a list predicates to the RoadmapProposalUpdate builder.
func (_u *RoadmapProposalUpdate) Where(ps ...predicate.RoadmapProposal) *RoadmapProposalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetStatus sets the "status" field.
func (_u *RoadmapProposalUpdate) SetStatus(v string) *RoadmapProposalUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RoadmapProposalUpdate) SetNillableStatus(v *string) *RoadmapProposalUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *RoadmapProposalUpdate) SetSource(v string) *RoadmapProposalUpdate {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *RoadmapProposalUpdate) SetNillableSource(v *string) *RoadmapProposalUpdate {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetAgentSessionID sets the "agent_session_id" field.
func (_u *RoadmapProposalUpdate) SetAgentSessionID(v string) *RoadmapProposalUpdate {
	_u.mutation.SetAgentSessionID(v)
	return _u
}

// SetNillableAgentSessionID sets the "agent_session_id" field if the given value is not nil.
func (_u *RoadmapProposalUpdate) SetNillableAgentSessionID(v *string) *RoadmapProposalUpdate {
	if v != nil {
		_u.SetAgentSessionID(*v)
	}
	return _u
}

// ClearAgentSessionID clears the value of the "agent_session_id" field.
func (_u *RoadmapProposalUpdate) ClearAgentSessionID() *RoadmapProposalUpdate {
	_u.mutation.ClearAgentSessionID()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *RoadmapProposalUpdate) SetSummary(v string) *RoadmapProposalUpdate {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *RoadmapProposalUpdate) SetNillableSummary(v *string) *RoadmapProposalUpdate {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RoadmapProposalUpdate) SetPayload(v map[string]interface{}) *RoadmapProposalUpdate {
	_u.mutation.SetPayload(v)
	return _u
}

// SetDecidedAt sets the "decided_at" field.
func (_u *RoadmapProposalUpdate) SetDecidedAt(v time.Time) *RoadmapProposalUpdate {
	_u.mutation.SetDecidedAt(v)
	return _u
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_u *RoadmapProposalUpdate) SetNillableDecidedAt(v *time.Time) *RoadmapProposalUpdate {
	if v != nil {
		_u.SetDecidedAt(*v)
	}
	return _u
}

// ClearDecidedAt clears the value of the "decided_at" field.
func (_u *RoadmapProposalUpdate) ClearDecidedAt() *RoadmapProposalUpdate {
	_u.mutation.ClearDecidedAt()
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *RoadmapProposalUpdate) SetProjectID(id string) *RoadmapProposalUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *RoadmapProposalUpdate) SetProject(v *Project) *RoadmapProposalUpdate {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the RoadmapProposalMutation object of the builder.
func (_u *RoadmapProposalUpdate) Mutation() *RoadmapProposalMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *RoadmapProposalUpdate) ClearProject() *RoadmapProposalUpdate {
	_u.mutation.ClearProject()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoadmapProposalUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoadmapProposalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoadmapProposalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoadmapProposalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoadmapProposalUpdate) check() error {
	if v, ok := _u.mutation.Summary(); ok {
		if err := roadmapproposal.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "RoadmapProposal.summary": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoadmapProposal.project"`)
	}
	return nil
}

func (_u *RoadmapProposalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(roadmapproposal.Table, roadmapproposal.Columns, sqlgraph.NewFieldSpec(roadmapproposal.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(roadmapproposal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(roadmapproposal.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentSessionID(); ok {
		_spec.SetField(roadmapproposal.FieldAgentSessionID, field.TypeString, value)
	}
	if _u.mutation.AgentSessionIDCleared() {
		_spec.ClearField(roadmapproposal.FieldAgentSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(roadmapproposal.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(roadmapproposal.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.DecidedAt(); ok {
		_spec.SetField(roadmapproposal.FieldDecidedAt, field.TypeTime, value)
	}
	if _u.mutation.DecidedAtCleared() {
		_spec.ClearField(roadmapproposal.FieldDecidedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roadmapproposal.ProjectTable,
			Columns: []string{roadmapproposal.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roadmapproposal.ProjectTable,
			Columns: []string{roadmapproposal.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roadmapproposal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoadmapProposalUpdateOne is the builder for updating a single RoadmapProposal entity.
type RoadmapProposalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoadmapProposalMutation
}

// SetStatus sets the "status" field.
func (_u *RoadmapProposalUpdateOne) SetStatus(v string) *RoadmapProposalUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RoadmapProposalUpdateOne) SetNillableStatus(v *string) *RoadmapProposalUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetSource sets the "source" field.
func (_u *RoadmapProposalUpdateOne) SetSource(v string) *RoadmapProposalUpdateOne {
	_u.mutation.SetSource(v)
	return _u
}

// SetNillableSource sets the "source" field if the given value is not nil.
func (_u *RoadmapProposalUpdateOne) SetNillableSource(v *string) *RoadmapProposalUpdateOne {
	if v != nil {
		_u.SetSource(*v)
	}
	return _u
}

// SetAgentSessionID sets the "agent_session_id" field.
func (_u *RoadmapProposalUpdateOne) SetAgentSessionID(v string) *RoadmapProposalUpdateOne {
	_u.mutation.SetAgentSessionID(v)
	return _u
}

// SetNillableAgentSessionID sets the "agent_session_id" field if the given value is not nil.
func (_u *RoadmapProposalUpdateOne) SetNillableAgentSessionID(v *string) *RoadmapProposalUpdateOne {
	if v != nil {
		_u.SetAgentSessionID(*v)
	}
	return _u
}

// ClearAgentSessionID clears the value of the "agent_session_id" field.
func (_u *RoadmapProposalUpdateOne) ClearAgentSessionID() *RoadmapProposalUpdateOne {
	_u.mutation.ClearAgentSessionID()
	return _u
}

// SetSummary sets the "summary" field.
func (_u *RoadmapProposalUpdateOne) SetSummary(v string) *RoadmapProposalUpdateOne {
	_u.mutation.SetSummary(v)
	return _u
}

// SetNillableSummary sets the "summary" field if the given value is not nil.
func (_u *RoadmapProposalUpdateOne) SetNillableSummary(v *string) *RoadmapProposalUpdateOne {
	if v != nil {
		_u.SetSummary(*v)
	}
	return _u
}

// SetPayload sets the "payload" field.
func (_u *RoadmapProposalUpdateOne) SetPayload(v map[string]interface{}) *RoadmapProposalUpdateOne {
	_u.mutation.SetPayload(v)
	return _u
}

// SetDecidedAt sets the "decided_at" field.
func (_u *RoadmapProposalUpdateOne) SetDecidedAt(v time.Time) *RoadmapProposalUpdateOne {
	_u.mutation.SetDecidedAt(v)
	return _u
}

// SetNillableDecidedAt sets the "decided_at" field if the given value is not nil.
func (_u *RoadmapProposalUpdateOne) SetNillableDecidedAt(v *time.Time) *RoadmapProposalUpdateOne {
	if v != nil {
		_u.SetDecidedAt(*v)
	}
	return _u
}

// ClearDecidedAt clears the value of the "decided_at" field.
func (_u *RoadmapProposalUpdateOne) ClearDecidedAt() *RoadmapProposalUpdateOne {
	_u.mutation.ClearDecidedAt()
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *RoadmapProposalUpdateOne) SetProjectID(id string) *RoadmapProposalUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *RoadmapProposalUpdateOne) SetProject(v *Project) *RoadmapProposalUpdateOne {
	return _u.SetProjectID(v.ID)
}

// Mutation returns the RoadmapProposalMutation object of the builder.
func (_u *RoadmapProposalUpdateOne) Mutation() *RoadmapProposalMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *RoadmapProposalUpdateOne) ClearProject() *RoadmapProposalUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// Where appends a list predicates to the RoadmapProposalUpdate builder.
func (_u *RoadmapProposalUpdateOne) Where(ps ...predicate.RoadmapProposal) *RoadmapProposalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoadmapProposalUpdateOne) Select(field string, fields ...string) *RoadmapProposalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RoadmapProposal entity.
func (_u *RoadmapProposalUpdateOne) Save(ctx context.Context) (*RoadmapProposal, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoadmapProposalUpdateOne) SaveX(ctx context.Context) *RoadmapProposal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoadmapProposalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoadmapProposalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoadmapProposalUpdateOne) check() error {
	if v, ok := _u.mutation.Summary(); ok {
		if err := roadmapproposal.SummaryValidator(v); err != nil {
			return &ValidationError{Name: "summary", err: fmt.Errorf(`ent: validator failed for field "RoadmapProposal.summary": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoadmapProposal.project"`)
	}
	return nil
}

func (_u *RoadmapProposalUpdateOne) sqlSave(ctx context.Context) (_node *RoadmapProposal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(roadmapproposal.Table, roadmapproposal.Columns, sqlgraph.NewFieldSpec(roadmapproposal.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoadmapProposal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roadmapproposal.FieldID)
		for _, f := range fields {
			if !roadmapproposal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != roadmapproposal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(roadmapproposal.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Source(); ok {
		_spec.SetField(roadmapproposal.FieldSource, field.TypeString, value)
	}
	if value, ok := _u.mutation.AgentSessionID(); ok {
		_spec.SetField(roadmapproposal.FieldAgentSessionID, field.TypeString, value)
	}
	if _u.mutation.AgentSessionIDCleared() {
		_spec.ClearField(roadmapproposal.FieldAgentSessionID, field.TypeString)
	}
	if value, ok := _u.mutation.Summary(); ok {
		_spec.SetField(roadmapproposal.FieldSummary, field.TypeString, value)
	}
	if value, ok := _u.mutation.Payload(); ok {
		_spec.SetField(roadmapproposal.FieldPayload, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.DecidedAt(); ok {
		_spec.SetField(roadmapproposal.FieldDecidedAt, field.TypeTime, value)
	}
	if _u.mutation.DecidedAtCleared() {
		_spec.ClearField(roadmapproposal.FieldDecidedAt, field.TypeTime)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roadmapproposal.ProjectTable,
			Columns: []string{roadmapproposal.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roadmapproposal.ProjectTable,
			Columns: []string{roadmapproposal.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RoadmapProposal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roadmapproposal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
