// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/project"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/roadmapphase"
)

// RoadmapPhase is the model entity for the RoadmapPhase schema.
type RoadmapPhase struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Title holds the value of the "title" field.
	Title string `json:"title,omitempty"`
	// Description holds the value of the "description" field.
	Description string `json:"description,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// Position holds the value of the "position" field.
	Position int `json:"position,omitempty"`
	// IsCurrent holds the value of the "is_current" field.
	IsCurrent bool `json:"is_current,omitempty"`
	// Provenance holds the value of the "provenance" field.
	Provenance string `json:"provenance,omitempty"`
	// BlockedReason holds the value of the "blocked_reason" field.
	BlockedReason string `json:"blocked_reason,omitempty"`
	// Decisions holds the value of the "decisions" field.
	Decisions string `json:"decisions,omitempty"`
	// DependsOn holds the value of the "depends_on" field.
	DependsOn []string `json:"depends_on,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the RoadmapPhaseQuery when eager-loading is set.
	Edges                  RoadmapPhaseEdges `json:"edges"`
	project_roadmap_phases *string
	selectValues           sql.SelectValues
}

// RoadmapPhaseEdges holds the relations/edges for other nodes in the graph.
type RoadmapPhaseEdges struct {
	// Project holds the value of the project edge.
	Project *Project `json:"project,omitempty"`
	// Items holds the value of the items edge.
	Items []*RoadmapItem `json:"items,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ProjectOrErr returns the Project value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e RoadmapPhaseEdges) ProjectOrErr() (*Project, error) {
	if e.Project != nil {
		return e.Project, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: project.Label}
	}
	return nil, &NotLoadedError{edge: "project"}
}

// ItemsOrErr returns the Items value or an error if the edge
// was not loaded in eager-loading.
func (e RoadmapPhaseEdges) ItemsOrErr() ([]*RoadmapItem, error) {
	if e.loadedTypes[1] {
		return e.Items, nil
	}
	return nil, &NotLoadedError{edge: "items"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*RoadmapPhase) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case roadmapphase.FieldDependsOn:
			values[i] = new([]byte)
		case roadmapphase.FieldIsCurrent:
			values[i] = new(sql.NullBool)
		case roadmapphase.FieldPosition:
			values[i] = new(sql.NullInt64)
		case roadmapphase.FieldID, roadmapphase.FieldTitle, roadmapphase.FieldDescription, roadmapphase.FieldStatus, roadmapphase.FieldProvenance, roadmapphase.FieldBlockedReason, roadmapphase.FieldDecisions:
			values[i] = new(sql.NullString)
		case roadmapphase.FieldCreatedAt, roadmapphase.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case roadmapphase.ForeignKeys[0]: // project_roadmap_phases
			values[i] = new(sql.NullString)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the RoadmapPhase fields.
func (_m *RoadmapPhase) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case roadmapphase.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case roadmapphase.FieldTitle:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field title", values[i])
			} else if value.Valid {
				_m.Title = value.String
			}
		case roadmapphase.FieldDescription:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field description", values[i])
			} else if value.Valid {
				_m.Description = value.String
			}
		case roadmapphase.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case roadmapphase.FieldPosition:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field position", values[i])
			} else if value.Valid {
				_m.Position = int(value.Int64)
			}
		case roadmapphase.FieldIsCurrent:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field is_current", values[i])
			} else if value.Valid {
				_m.IsCurrent = value.Bool
			}
		case roadmapphase.FieldProvenance:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field provenance", values[i])
			} else if value.Valid {
				_m.Provenance = value.String
			}
		case roadmapphase.FieldBlockedReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field blocked_reason", values[i])
			} else if value.Valid {
				_m.BlockedReason = value.String
			}
		case roadmapphase.FieldDecisions:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field decisions", values[i])
			} else if value.Valid {
				_m.Decisions = value.String
			}
		case roadmapphase.FieldDependsOn:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field depends_on", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.DependsOn); err != nil {
					return fmt.Errorf("unmarshal field depends_on: %w", err)
				}
			}
		case roadmapphase.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case roadmapphase.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case roadmapphase.ForeignKeys[0]:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field project_roadmap_phases", values[i])
			} else if value.Valid {
				_m.project_roadmap_phases = new(string)
				*_m.project_roadmap_phases = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the RoadmapPhase.
// This includes values selected through modifiers, order, etc.
func (_m *RoadmapPhase) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryProject queries the "project" edge of the RoadmapPhase entity.
func (_m *RoadmapPhase) QueryProject() *ProjectQuery {
	return NewRoadmapPhaseClient(_m.config).QueryProject(_m)
}

// QueryItems queries the "items" edge of the RoadmapPhase entity.
func (_m *RoadmapPhase) QueryItems() *RoadmapItemQuery {
	return NewRoadmapPhaseClient(_m.config).QueryItems(_m)
}

// Update returns a builder for updating this RoadmapPhase.
// Note that you need to call RoadmapPhase.Unwrap() before calling this method if this RoadmapPhase
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *RoadmapPhase) Update() *RoadmapPhaseUpdateOne {
	return NewRoadmapPhaseClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the RoadmapPhase entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *RoadmapPhase) Unwrap() *RoadmapPhase {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: RoadmapPhase is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *RoadmapPhase) String() string {
	var builder strings.Builder
	builder.WriteString("RoadmapPhase(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("title=")
	builder.WriteString(_m.Title)
	builder.WriteString(", ")
	builder.WriteString("description=")
	builder.WriteString(_m.Description)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("position=")
	builder.WriteString(fmt.Sprintf("%v", _m.Position))
	builder.WriteString(", ")
	builder.WriteString("is_current=")
	builder.WriteString(fmt.Sprintf("%v", _m.IsCurrent))
	builder.WriteString(", ")
	builder.WriteString("provenance=")
	builder.WriteString(_m.Provenance)
	builder.WriteString(", ")
	builder.WriteString("blocked_reason=")
	builder.WriteString(_m.BlockedReason)
	builder.WriteString(", ")
	builder.WriteString("decisions=")
	builder.WriteString(_m.Decisions)
	builder.WriteString(", ")
	builder.WriteString("depends_on=")
	builder.WriteString(fmt.Sprintf("%v", _m.DependsOn))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// RoadmapPhases is a parsable slice of RoadmapPhase.
type RoadmapPhases []*RoadmapPhase
