// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/roadmapphase"
)

// RoadmapPhaseDelete is the builder for deleting a RoadmapPhase entity.
type RoadmapPhaseDelete struct {
	config
	hooks    []Hook
	mutation *RoadmapPhaseMutation
}

// Where appends a list predicates to the RoadmapPhaseDelete builder.
func (_d *RoadmapPhaseDelete) Where(ps ...predicate.RoadmapPhase) *RoadmapPhaseDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *RoadmapPhaseDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RoadmapPhaseDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *RoadmapPhaseDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(roadmapphase.Table, sqlgraph.NewFieldSpec(roadmapphase.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// RoadmapPhaseDeleteOne is the builder for deleting a single RoadmapPhase entity.
type RoadmapPhaseDeleteOne struct {
	_d *RoadmapPhaseDelete
}

// Where appends a list predicates to the RoadmapPhaseDelete builder.
func (_d *RoadmapPhaseDeleteOne) Where(ps ...predicate.RoadmapPhase) *RoadmapPhaseDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *RoadmapPhaseDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{roadmapphase.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *RoadmapPhaseDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
