// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/project"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/roadmapitem"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/roadmapphase"
)

// RoadmapPhaseQuery is the builder for querying RoadmapPhase entities.
type RoadmapPhaseQuery struct {
	config
	ctx         *QueryContext
	order       []roadmapphase.OrderOption
	inters      []Interceptor
	predicates  []predicate.RoadmapPhase
	withProject *ProjectQuery
	withItems   *RoadmapItemQuery
	withFKs     bool
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the RoadmapPhaseQuery builder.
func (_q *RoadmapPhaseQuery) Where(ps ...predicate.RoadmapPhase) *RoadmapPhaseQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *RoadmapPhaseQuery) Limit(limit int) *RoadmapPhaseQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *RoadmapPhaseQuery) Offset(offset int) *RoadmapPhaseQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *RoadmapPhaseQuery) Unique(unique bool) *RoadmapPhaseQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *RoadmapPhaseQuery) Order(o ...roadmapphase.OrderOption) *RoadmapPhaseQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryProject chains the current query on the "project" edge.
func (_q *RoadmapPhaseQuery) QueryProject() *ProjectQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roadmapphase.Table, roadmapphase.FieldID, selector),
			sqlgraph.To(project.Table, project.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, roadmapphase.ProjectTable, roadmapphase.ProjectColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryItems chains the current query on the "items" edge.
func (_q *RoadmapPhaseQuery) QueryItems() *RoadmapItemQuery {
	query := (&RoadmapItemClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(roadmapphase.Table, roadmapphase.FieldID, selector),
			sqlgraph.To(roadmapitem.Table, roadmapitem.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, roadmapphase.ItemsTable, roadmapphase.ItemsColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first RoadmapPhase entity from the query.
// Returns a *NotFoundError when no RoadmapPhase was found.
func (_q *RoadmapPhaseQuery) First(ctx context.Context) (*RoadmapPhase, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{roadmapphase.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *RoadmapPhaseQuery) FirstX(ctx context.Context) *RoadmapPhase {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first RoadmapPhase ID from the query.
// Returns a *NotFoundError when no RoadmapPhase ID was found.
func (_q *RoadmapPhaseQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{roadmapphase.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *RoadmapPhaseQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single RoadmapPhase entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one RoadmapPhase entity is found.
// Returns a *NotFoundError when no RoadmapPhase entities are found.
func (_q *RoadmapPhaseQuery) Only(ctx context.Context) (*RoadmapPhase, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{roadmapphase.Label}
	default:
		return nil, &NotSingularError{roadmapphase.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *RoadmapPhaseQuery) OnlyX(ctx context.Context) *RoadmapPhase {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only RoadmapPhase ID in the query.
// Returns a *NotSingularError when more than one RoadmapPhase ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *RoadmapPhaseQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{roadmapphase.Label}
	default:
		err = &NotSingularError{roadmapphase.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *RoadmapPhaseQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of RoadmapPhases.
func (_q *RoadmapPhaseQuery) All(ctx context.Context) ([]*RoadmapPhase, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*RoadmapPhase, *RoadmapPhaseQuery]()
	return withInterceptors[[]*RoadmapPhase](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *RoadmapPhaseQuery) AllX(ctx context.Context) []*RoadmapPhase {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of RoadmapPhase IDs.
func (_q *RoadmapPhaseQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(roadmapphase.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *RoadmapPhaseQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *RoadmapPhaseQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*RoadmapPhaseQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *RoadmapPhaseQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *RoadmapPhaseQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *RoadmapPhaseQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the RoadmapPhaseQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *RoadmapPhaseQuery) Clone() *RoadmapPhaseQuery {
	if _q == nil {
		return nil
	}
	return &RoadmapPhaseQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]roadmapphase.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.RoadmapPhase{}, _q.predicates...),
		withProject: _q.withProject.Clone(),
		withItems:   _q.withItems.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithProject tells the query-builder to eager-load the nodes that are connected to
// the "project" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RoadmapPhaseQuery) WithProject(opts ...func(*ProjectQuery)) *RoadmapPhaseQuery {
	query := (&ProjectClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProject = query
	return _q
}

// WithItems tells the query-builder to eager-load the nodes that are connected to
// the "items" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *RoadmapPhaseQuery) WithItems(opts ...func(*RoadmapItemQuery)) *RoadmapPhaseQuery {
	query := (&RoadmapItemClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withItems = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.RoadmapPhase.Query().
//		GroupBy(roadmapphase.FieldTitle).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *RoadmapPhaseQuery) GroupBy(field string, fields ...string) *RoadmapPhaseGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &RoadmapPhaseGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = roadmapphase.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Title string `json:"title,omitempty"`
//	}
//
//	client.RoadmapPhase.Query().
//		Select(roadmapphase.FieldTitle).
//		Scan(ctx, &v)
func (_q *RoadmapPhaseQuery) Select(fields ...string) *RoadmapPhaseSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &RoadmapPhaseSelect{RoadmapPhaseQuery: _q}
	sbuild.label = roadmapphase.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a RoadmapPhaseSelect configured with the given aggregations.
func (_q *RoadmapPhaseQuery) Aggregate(fns ...AggregateFunc) *RoadmapPhaseSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *RoadmapPhaseQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !roadmapphase.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *RoadmapPhaseQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*RoadmapPhase, error) {
	var (
		nodes       = []*RoadmapPhase{}
		withFKs     = _q.withFKs
		_spec       = _q.querySpec()
		loadedTypes = [2]bool{
			_q.withProject != nil,
			_q.withItems != nil,
		}
	)
	if _q.withProject != nil {
		withFKs = true
	}
	if withFKs {
		_spec.Node.Columns = append(_spec.Node.Columns, roadmapphase.ForeignKeys...)
	}
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*RoadmapPhase).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &RoadmapPhase{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withProject; query != nil {
		if err := _q.loadProject(ctx, query, nodes, nil,
			func(n *RoadmapPhase, e *Project) { n.Edges.Project = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withItems; query != nil {
		if err := _q.loadItems(ctx, query, nodes,
			func(n *RoadmapPhase) { n.Edges.Items = []*RoadmapItem{} },
			func(n *RoadmapPhase, e *RoadmapItem) { n.Edges.Items = append(n.Edges.Items, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *RoadmapPhaseQuery) loadProject(ctx context.Context, query *ProjectQuery, nodes []*RoadmapPhase, init func(*RoadmapPhase), assign func(*RoadmapPhase, *Project)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*RoadmapPhase)
	for i := range nodes {
		if nodes[i].project_roadmap_phases == nil {
			continue
		}
		fk := *nodes[i].project_roadmap_phases
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(project.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "project_roadmap_phases" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *RoadmapPhaseQuery) loadItems(ctx context.Context, query *RoadmapItemQuery, nodes []*RoadmapPhase, init func(*RoadmapPhase), assign func(*RoadmapPhase, *RoadmapItem)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*RoadmapPhase)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	query.withFKs = true
	query.Where(predicate.RoadmapItem(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(roadmapphase.ItemsColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.roadmap_phase_items
		if fk == nil {
			return fmt.Errorf(`foreign-key "roadmap_phase_items" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "roadmap_phase_items" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *RoadmapPhaseQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *RoadmapPhaseQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(roadmapphase.Table, roadmapphase.Columns, sqlgraph.NewFieldSpec(roadmapphase.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roadmapphase.FieldID)
		for i := range fields {
			if fields[i] != roadmapphase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *RoadmapPhaseQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(roadmapphase.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = roadmapphase.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// RoadmapPhaseGroupBy is the group-by builder for RoadmapPhase entities.
type RoadmapPhaseGroupBy struct {
	selector
	build *RoadmapPhaseQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *RoadmapPhaseGroupBy) Aggregate(fns ...AggregateFunc) *RoadmapPhaseGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *RoadmapPhaseGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoadmapPhaseQuery, *RoadmapPhaseGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *RoadmapPhaseGroupBy) sqlScan(ctx context.Context, root *RoadmapPhaseQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// RoadmapPhaseSelect is the builder for selecting fields of RoadmapPhase entities.
type RoadmapPhaseSelect struct {
	*RoadmapPhaseQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *RoadmapPhaseSelect) Aggregate(fns ...AggregateFunc) *RoadmapPhaseSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *RoadmapPhaseSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*RoadmapPhaseQuery, *RoadmapPhaseSelect](ctx, _s.RoadmapPhaseQuery, _s, _s.inters, v)
}

func (_s *RoadmapPhaseSelect) sqlScan(ctx context.Context, root *RoadmapPhaseQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
