// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/project"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/roadmapitem"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/roadmapphase"
)

// RoadmapPhaseUpdate is the builder for updating RoadmapPhase entities.
type RoadmapPhaseUpdate struct {
	config
	hooks    []Hook
	mutation *RoadmapPhaseMutation
}

// Where appends a list predicates to the RoadmapPhaseUpdate builder.
func (_u *RoadmapPhaseUpdate) Where(ps ...predicate.RoadmapPhase) *RoadmapPhaseUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTitle sets the "title" field.
func (_u *RoadmapPhaseUpdate) SetTitle(v string) *RoadmapPhaseUpdate {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *RoadmapPhaseUpdate) SetNillableTitle(v *string) *RoadmapPhaseUpdate {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RoadmapPhaseUpdate) SetDescription(v string) *RoadmapPhaseUpdate {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RoadmapPhaseUpdate) SetNillableDescription(v *string) *RoadmapPhaseUpdate {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RoadmapPhaseUpdate) SetStatus(v string) *RoadmapPhaseUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RoadmapPhaseUpdate) SetNillableStatus(v *string) *RoadmapPhaseUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *RoadmapPhaseUpdate) SetPosition(v int) *RoadmapPhaseUpdate {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *RoadmapPhaseUpdate) SetNillablePosition(v *int) *RoadmapPhaseUpdate {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *RoadmapPhaseUpdate) AddPosition(v int) *RoadmapPhaseUpdate {
	_u.mutation.AddPosition(v)
	return _u
}

// SetIsCurrent sets the "is_current" field.
func (_u *RoadmapPhaseUpdate) SetIsCurrent(v bool) *RoadmapPhaseUpdate {
	_u.mutation.SetIsCurrent(v)
	return _u
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (_u *RoadmapPhaseUpdate) SetNillableIsCurrent(v *bool) *RoadmapPhaseUpdate {
	if v != nil {
		_u.SetIsCurrent(*v)
	}
	return _u
}

// SetProvenance sets the "provenance" field.
func (_u *RoadmapPhaseUpdate) SetProvenance(v string) *RoadmapPhaseUpdate {
	_u.mutation.SetProvenance(v)
	return _u
}

// SetNillableProvenance sets the "provenance" field if the given value is not nil.
func (_u *RoadmapPhaseUpdate) SetNillableProvenance(v *string) *RoadmapPhaseUpdate {
	if v != nil {
		_u.SetProvenance(*v)
	}
	return _u
}

// SetBlockedReason sets the "blocked_reason" field.
func (_u *RoadmapPhaseUpdate) SetBlockedReason(v string) *RoadmapPhaseUpdate {
	_u.mutation.SetBlockedReason(v)
	return _u
}

// SetNillableBlockedReason sets the "blocked_reason" field if the given value is not nil.
func (_u *RoadmapPhaseUpdate) SetNillableBlockedReason(v *string) *RoadmapPhaseUpdate {
	if v != nil {
		_u.SetBlockedReason(*v)
	}
	return _u
}

// SetDecisions sets the "decisions" field.
func (_u *RoadmapPhaseUpdate) SetDecisions(v string) *RoadmapPhaseUpdate {
	_u.mutation.SetDecisions(v)
	return _u
}

// SetNillableDecisions sets the "decisions" field if the given value is not nil.
func (_u *RoadmapPhaseUpdate) SetNillableDecisions(v *string) *RoadmapPhaseUpdate {
	if v != nil {
		_u.SetDecisions(*v)
	}
	return _u
}

// SetDependsOn sets the "depends_on" field.
func (_u *RoadmapPhaseUpdate) SetDependsOn(v []string) *RoadmapPhaseUpdate {
	_u.mutation.SetDependsOn(v)
	return _u
}

// AppendDependsOn appends value to the "depends_on" field.
func (_u *RoadmapPhaseUpdate) AppendDependsOn(v []string) *RoadmapPhaseUpdate {
	_u.mutation.AppendDependsOn(v)
	return _u
}

// ClearDependsOn clears the value of the "depends_on" field.
func (_u *RoadmapPhaseUpdate) ClearDependsOn() *RoadmapPhaseUpdate {
	_u.mutation.ClearDependsOn()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoadmapPhaseUpdate) SetUpdatedAt(v time.Time) *RoadmapPhaseUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *RoadmapPhaseUpdate) SetProjectID(id string) *RoadmapPhaseUpdate {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *RoadmapPhaseUpdate) SetProject(v *Project) *RoadmapPhaseUpdate {
	return _u.SetProjectID(v.ID)
}

// AddItemIDs adds the "items" edge to the RoadmapItem entity by IDs.
func (_u *RoadmapPhaseUpdate) AddItemIDs(ids ...string) *RoadmapPhaseUpdate {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the RoadmapItem entity.
func (_u *RoadmapPhaseUpdate) AddItems(v ...*RoadmapItem) *RoadmapPhaseUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the RoadmapPhaseMutation object of the builder.
func (_u *RoadmapPhaseUpdate) Mutation() *RoadmapPhaseMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *RoadmapPhaseUpdate) ClearProject() *RoadmapPhaseUpdate {
	_u.mutation.ClearProject()
	return _u
}

// ClearItems clears all "items" edges to the RoadmapItem entity.
func (_u *RoadmapPhaseUpdate) ClearItems() *RoadmapPhaseUpdate {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to RoadmapItem entities by IDs.
func (_u *RoadmapPhaseUpdate) RemoveItemIDs(ids ...string) *RoadmapPhaseUpdate {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to RoadmapItem entities.
func (_u *RoadmapPhaseUpdate) RemoveItems(v ...*RoadmapItem) *RoadmapPhaseUpdate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoadmapPhaseUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoadmapPhaseUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoadmapPhaseUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoadmapPhaseUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoadmapPhaseUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := roadmapphase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoadmapPhaseUpdate) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := roadmapphase.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "RoadmapPhase.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := roadmapphase.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RoadmapPhase.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BlockedReason(); ok {
		if err := roadmapphase.BlockedReasonValidator(v); err != nil {
			return &ValidationError{Name: "blocked_reason", err: fmt.Errorf(`ent: validator failed for field "RoadmapPhase.blocked_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Decisions(); ok {
		if err := roadmapphase.DecisionsValidator(v); err != nil {
			return &ValidationError{Name: "decisions", err: fmt.Errorf(`ent: validator failed for field "RoadmapPhase.decisions": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoadmapPhase.project"`)
	}
	return nil
}

func (_u *RoadmapPhaseUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(roadmapphase.Table, roadmapphase.Columns, sqlgraph.NewFieldSpec(roadmapphase.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(roadmapphase.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(roadmapphase.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(roadmapphase.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(roadmapphase.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(roadmapphase.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsCurrent(); ok {
		_spec.SetField(roadmapphase.FieldIsCurrent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Provenance(); ok {
		_spec.SetField(roadmapphase.FieldProvenance, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlockedReason(); ok {
		_spec.SetField(roadmapphase.FieldBlockedReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Decisions(); ok {
		_spec.SetField(roadmapphase.FieldDecisions, field.TypeString, value)
	}
	if value, ok := _u.mutation.DependsOn(); ok {
		_spec.SetField(roadmapphase.FieldDependsOn, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDependsOn(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, roadmapphase.FieldDependsOn, value)
		})
	}
	if _u.mutation.DependsOnCleared() {
		_spec.ClearField(roadmapphase.FieldDependsOn, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(roadmapphase.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roadmapphase.ProjectTable,
			Columns: []string{roadmapphase.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roadmapphase.ProjectTable,
			Columns: []string{roadmapphase.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roadmapphase.ItemsTable,
			Columns: []string{roadmapphase.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roadmapitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roadmapphase.ItemsTable,
			Columns: []string{roadmapphase.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roadmapitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roadmapphase.ItemsTable,
			Columns: []string{roadmapphase.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roadmapitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roadmapphase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoadmapPhaseUpdateOne is the builder for updating a single RoadmapPhase entity.
type RoadmapPhaseUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoadmapPhaseMutation
}

// SetTitle sets the "title" field.
func (_u *RoadmapPhaseUpdateOne) SetTitle(v string) *RoadmapPhaseUpdateOne {
	_u.mutation.SetTitle(v)
	return _u
}

// SetNillableTitle sets the "title" field if the given value is not nil.
func (_u *RoadmapPhaseUpdateOne) SetNillableTitle(v *string) *RoadmapPhaseUpdateOne {
	if v != nil {
		_u.SetTitle(*v)
	}
	return _u
}

// SetDescription sets the "description" field.
func (_u *RoadmapPhaseUpdateOne) SetDescription(v string) *RoadmapPhaseUpdateOne {
	_u.mutation.SetDescription(v)
	return _u
}

// SetNillableDescription sets the "description" field if the given value is not nil.
func (_u *RoadmapPhaseUpdateOne) SetNillableDescription(v *string) *RoadmapPhaseUpdateOne {
	if v != nil {
		_u.SetDescription(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *RoadmapPhaseUpdateOne) SetStatus(v string) *RoadmapPhaseUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *RoadmapPhaseUpdateOne) SetNillableStatus(v *string) *RoadmapPhaseUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetPosition sets the "position" field.
func (_u *RoadmapPhaseUpdateOne) SetPosition(v int) *RoadmapPhaseUpdateOne {
	_u.mutation.ResetPosition()
	_u.mutation.SetPosition(v)
	return _u
}

// SetNillablePosition sets the "position" field if the given value is not nil.
func (_u *RoadmapPhaseUpdateOne) SetNillablePosition(v *int) *RoadmapPhaseUpdateOne {
	if v != nil {
		_u.SetPosition(*v)
	}
	return _u
}

// AddPosition adds value to the "position" field.
func (_u *RoadmapPhaseUpdateOne) AddPosition(v int) *RoadmapPhaseUpdateOne {
	_u.mutation.AddPosition(v)
	return _u
}

// SetIsCurrent sets the "is_current" field.
func (_u *RoadmapPhaseUpdateOne) SetIsCurrent(v bool) *RoadmapPhaseUpdateOne {
	_u.mutation.SetIsCurrent(v)
	return _u
}

// SetNillableIsCurrent sets the "is_current" field if the given value is not nil.
func (_u *RoadmapPhaseUpdateOne) SetNillableIsCurrent(v *bool) *RoadmapPhaseUpdateOne {
	if v != nil {
		_u.SetIsCurrent(*v)
	}
	return _u
}

// SetProvenance sets the "provenance" field.
func (_u *RoadmapPhaseUpdateOne) SetProvenance(v string) *RoadmapPhaseUpdateOne {
	_u.mutation.SetProvenance(v)
	return _u
}

// SetNillableProvenance sets the "provenance" field if the given value is not nil.
func (_u *RoadmapPhaseUpdateOne) SetNillableProvenance(v *string) *RoadmapPhaseUpdateOne {
	if v != nil {
		_u.SetProvenance(*v)
	}
	return _u
}

// SetBlockedReason sets the "blocked_reason" field.
func (_u *RoadmapPhaseUpdateOne) SetBlockedReason(v string) *RoadmapPhaseUpdateOne {
	_u.mutation.SetBlockedReason(v)
	return _u
}

// SetNillableBlockedReason sets the "blocked_reason" field if the given value is not nil.
func (_u *RoadmapPhaseUpdateOne) SetNillableBlockedReason(v *string) *RoadmapPhaseUpdateOne {
	if v != nil {
		_u.SetBlockedReason(*v)
	}
	return _u
}

// SetDecisions sets the "decisions" field.
func (_u *RoadmapPhaseUpdateOne) SetDecisions(v string) *RoadmapPhaseUpdateOne {
	_u.mutation.SetDecisions(v)
	return _u
}

// SetNillableDecisions sets the "decisions" field if the given value is not nil.
func (_u *RoadmapPhaseUpdateOne) SetNillableDecisions(v *string) *RoadmapPhaseUpdateOne {
	if v != nil {
		_u.SetDecisions(*v)
	}
	return _u
}

// SetDependsOn sets the "depends_on" field.
func (_u *RoadmapPhaseUpdateOne) SetDependsOn(v []string) *RoadmapPhaseUpdateOne {
	_u.mutation.SetDependsOn(v)
	return _u
}

// AppendDependsOn appends value to the "depends_on" field.
func (_u *RoadmapPhaseUpdateOne) AppendDependsOn(v []string) *RoadmapPhaseUpdateOne {
	_u.mutation.AppendDependsOn(v)
	return _u
}

// ClearDependsOn clears the value of the "depends_on" field.
func (_u *RoadmapPhaseUpdateOne) ClearDependsOn() *RoadmapPhaseUpdateOne {
	_u.mutation.ClearDependsOn()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoadmapPhaseUpdateOne) SetUpdatedAt(v time.Time) *RoadmapPhaseUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetProjectID sets the "project" edge to the Project entity by ID.
func (_u *RoadmapPhaseUpdateOne) SetProjectID(id string) *RoadmapPhaseUpdateOne {
	_u.mutation.SetProjectID(id)
	return _u
}

// SetProject sets the "project" edge to the Project entity.
func (_u *RoadmapPhaseUpdateOne) SetProject(v *Project) *RoadmapPhaseUpdateOne {
	return _u.SetProjectID(v.ID)
}

// AddItemIDs adds the "items" edge to the RoadmapItem entity by IDs.
func (_u *RoadmapPhaseUpdateOne) AddItemIDs(ids ...string) *RoadmapPhaseUpdateOne {
	_u.mutation.AddItemIDs(ids...)
	return _u
}

// AddItems adds the "items" edges to the RoadmapItem entity.
func (_u *RoadmapPhaseUpdateOne) AddItems(v ...*RoadmapItem) *RoadmapPhaseUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddItemIDs(ids...)
}

// Mutation returns the RoadmapPhaseMutation object of the builder.
func (_u *RoadmapPhaseUpdateOne) Mutation() *RoadmapPhaseMutation {
	return _u.mutation
}

// ClearProject clears the "project" edge to the Project entity.
func (_u *RoadmapPhaseUpdateOne) ClearProject() *RoadmapPhaseUpdateOne {
	_u.mutation.ClearProject()
	return _u
}

// ClearItems clears all "items" edges to the RoadmapItem entity.
func (_u *RoadmapPhaseUpdateOne) ClearItems() *RoadmapPhaseUpdateOne {
	_u.mutation.ClearItems()
	return _u
}

// RemoveItemIDs removes the "items" edge to RoadmapItem entities by IDs.
func (_u *RoadmapPhaseUpdateOne) RemoveItemIDs(ids ...string) *RoadmapPhaseUpdateOne {
	_u.mutation.RemoveItemIDs(ids...)
	return _u
}

// RemoveItems removes "items" edges to RoadmapItem entities.
func (_u *RoadmapPhaseUpdateOne) RemoveItems(v ...*RoadmapItem) *RoadmapPhaseUpdateOne {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveItemIDs(ids...)
}

// Where appends a list predicates to the RoadmapPhaseUpdate builder.
func (_u *RoadmapPhaseUpdateOne) Where(ps ...predicate.RoadmapPhase) *RoadmapPhaseUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoadmapPhaseUpdateOne) Select(field string, fields ...string) *RoadmapPhaseUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated RoadmapPhase entity.
func (_u *RoadmapPhaseUpdateOne) Save(ctx context.Context) (*RoadmapPhase, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoadmapPhaseUpdateOne) SaveX(ctx context.Context) *RoadmapPhase {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoadmapPhaseUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoadmapPhaseUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoadmapPhaseUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := roadmapphase.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoadmapPhaseUpdateOne) check() error {
	if v, ok := _u.mutation.Title(); ok {
		if err := roadmapphase.TitleValidator(v); err != nil {
			return &ValidationError{Name: "title", err: fmt.Errorf(`ent: validator failed for field "RoadmapPhase.title": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Description(); ok {
		if err := roadmapphase.DescriptionValidator(v); err != nil {
			return &ValidationError{Name: "description", err: fmt.Errorf(`ent: validator failed for field "RoadmapPhase.description": %w`, err)}
		}
	}
	if v, ok := _u.mutation.BlockedReason(); ok {
		if err := roadmapphase.BlockedReasonValidator(v); err != nil {
			return &ValidationError{Name: "blocked_reason", err: fmt.Errorf(`ent: validator failed for field "RoadmapPhase.blocked_reason": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Decisions(); ok {
		if err := roadmapphase.DecisionsValidator(v); err != nil {
			return &ValidationError{Name: "decisions", err: fmt.Errorf(`ent: validator failed for field "RoadmapPhase.decisions": %w`, err)}
		}
	}
	if _u.mutation.ProjectCleared() && len(_u.mutation.ProjectIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "RoadmapPhase.project"`)
	}
	return nil
}

func (_u *RoadmapPhaseUpdateOne) sqlSave(ctx context.Context) (_node *RoadmapPhase, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(roadmapphase.Table, roadmapphase.Columns, sqlgraph.NewFieldSpec(roadmapphase.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "RoadmapPhase.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, roadmapphase.FieldID)
		for _, f := range fields {
			if !roadmapphase.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != roadmapphase.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Title(); ok {
		_spec.SetField(roadmapphase.FieldTitle, field.TypeString, value)
	}
	if value, ok := _u.mutation.Description(); ok {
		_spec.SetField(roadmapphase.FieldDescription, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(roadmapphase.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Position(); ok {
		_spec.SetField(roadmapphase.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedPosition(); ok {
		_spec.AddField(roadmapphase.FieldPosition, field.TypeInt, value)
	}
	if value, ok := _u.mutation.IsCurrent(); ok {
		_spec.SetField(roadmapphase.FieldIsCurrent, field.TypeBool, value)
	}
	if value, ok := _u.mutation.Provenance(); ok {
		_spec.SetField(roadmapphase.FieldProvenance, field.TypeString, value)
	}
	if value, ok := _u.mutation.BlockedReason(); ok {
		_spec.SetField(roadmapphase.FieldBlockedReason, field.TypeString, value)
	}
	if value, ok := _u.mutation.Decisions(); ok {
		_spec.SetField(roadmapphase.FieldDecisions, field.TypeString, value)
	}
	if value, ok := _u.mutation.DependsOn(); ok {
		_spec.SetField(roadmapphase.FieldDependsOn, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedDependsOn(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, roadmapphase.FieldDependsOn, value)
		})
	}
	if _u.mutation.DependsOnCleared() {
		_spec.ClearField(roadmapphase.FieldDependsOn, field.TypeJSON)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(roadmapphase.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.ProjectCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roadmapphase.ProjectTable,
			Columns: []string{roadmapphase.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   roadmapphase.ProjectTable,
			Columns: []string{roadmapphase.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(project.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roadmapphase.ItemsTable,
			Columns: []string{roadmapphase.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roadmapitem.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedItemsIDs(); len(nodes) > 0 && !_u.mutation.ItemsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roadmapphase.ItemsTable,
			Columns: []string{roadmapphase.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roadmapitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ItemsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   roadmapphase.ItemsTable,
			Columns: []string{roadmapphase.ItemsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(roadmapitem.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &RoadmapPhase{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{roadmapphase.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
