// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/agentcosttrend"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/apikey"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/appsetting"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/auditevent"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/capability"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/checkpoint"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/coordlock"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/driftalert"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/evalmetricsnapshot"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/grant"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/grantusage"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/materialization"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/memoryentry"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/memoryinjection"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/permissionrequest"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/pipelineconfig"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/plugin"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/pluginsetting"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/project"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/projectfolder"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/prompttemplate"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/providersetting"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/refinementturn"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/remoteregistration"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/resource"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/schema"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/scratchpad"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/skill"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/spawner"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/stagerun"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/systemprompt"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/task"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskdependency"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskpermission"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/taskschedule"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/user"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	agentcosttrendFields := schema.AgentCostTrend{}.Fields()
	_ = agentcosttrendFields
	// agentcosttrendDescRecordedAt is the schema descriptor for recorded_at field.
	agentcosttrendDescRecordedAt := agentcosttrendFields[6].Descriptor()
	// agentcosttrend.DefaultRecordedAt holds the default value on creation for the recorded_at field.
	agentcosttrend.DefaultRecordedAt = agentcosttrendDescRecordedAt.Default.(func() time.Time)
	// agentcosttrendDescCwd is the schema descriptor for cwd field.
	agentcosttrendDescCwd := agentcosttrendFields[7].Descriptor()
	// agentcosttrend.DefaultCwd holds the default value on creation for the cwd field.
	agentcosttrend.DefaultCwd = agentcosttrendDescCwd.Default.(string)
	// agentcosttrendDescProjectPath is the schema descriptor for project_path field.
	agentcosttrendDescProjectPath := agentcosttrendFields[8].Descriptor()
	// agentcosttrend.DefaultProjectPath holds the default value on creation for the project_path field.
	agentcosttrend.DefaultProjectPath = agentcosttrendDescProjectPath.Default.(string)
	// agentcosttrendDescProjectName is the schema descriptor for project_name field.
	agentcosttrendDescProjectName := agentcosttrendFields[9].Descriptor()
	// agentcosttrend.DefaultProjectName holds the default value on creation for the project_name field.
	agentcosttrend.DefaultProjectName = agentcosttrendDescProjectName.Default.(string)
	// agentcosttrendDescSourceMtime is the schema descriptor for source_mtime field.
	agentcosttrendDescSourceMtime := agentcosttrendFields[10].Descriptor()
	// agentcosttrend.DefaultSourceMtime holds the default value on creation for the source_mtime field.
	agentcosttrend.DefaultSourceMtime = agentcosttrendDescSourceMtime.Default.(int64)
	apikeyFields := schema.ApiKey{}.Fields()
	_ = apikeyFields
	// apikeyDescScopes is the schema descriptor for scopes field.
	apikeyDescScopes := apikeyFields[3].Descriptor()
	// apikey.DefaultScopes holds the default value on creation for the scopes field.
	apikey.DefaultScopes = apikeyDescScopes.Default.([]string)
	// apikeyDescActive is the schema descriptor for active field.
	apikeyDescActive := apikeyFields[4].Descriptor()
	// apikey.DefaultActive holds the default value on creation for the active field.
	apikey.DefaultActive = apikeyDescActive.Default.(bool)
	// apikeyDescKind is the schema descriptor for kind field.
	apikeyDescKind := apikeyFields[5].Descriptor()
	// apikey.DefaultKind holds the default value on creation for the kind field.
	apikey.DefaultKind = apikeyDescKind.Default.(string)
	// apikeyDescStageRunID is the schema descriptor for stage_run_id field.
	apikeyDescStageRunID := apikeyFields[6].Descriptor()
	// apikey.DefaultStageRunID holds the default value on creation for the stage_run_id field.
	apikey.DefaultStageRunID = apikeyDescStageRunID.Default.(string)
	// apikeyDescCreatedAt is the schema descriptor for created_at field.
	apikeyDescCreatedAt := apikeyFields[8].Descriptor()
	// apikey.DefaultCreatedAt holds the default value on creation for the created_at field.
	apikey.DefaultCreatedAt = apikeyDescCreatedAt.Default.(func() time.Time)
	appsettingFields := schema.AppSetting{}.Fields()
	_ = appsettingFields
	// appsettingDescSecret is the schema descriptor for secret field.
	appsettingDescSecret := appsettingFields[3].Descriptor()
	// appsetting.DefaultSecret holds the default value on creation for the secret field.
	appsetting.DefaultSecret = appsettingDescSecret.Default.(bool)
	// appsettingDescNonce is the schema descriptor for nonce field.
	appsettingDescNonce := appsettingFields[4].Descriptor()
	// appsetting.DefaultNonce holds the default value on creation for the nonce field.
	appsetting.DefaultNonce = appsettingDescNonce.Default.(string)
	// appsettingDescCreatedAt is the schema descriptor for created_at field.
	appsettingDescCreatedAt := appsettingFields[5].Descriptor()
	// appsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	appsetting.DefaultCreatedAt = appsettingDescCreatedAt.Default.(func() time.Time)
	// appsettingDescUpdatedAt is the schema descriptor for updated_at field.
	appsettingDescUpdatedAt := appsettingFields[6].Descriptor()
	// appsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	appsetting.DefaultUpdatedAt = appsettingDescUpdatedAt.Default.(func() time.Time)
	// appsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	appsetting.UpdateDefaultUpdatedAt = appsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	auditeventFields := schema.AuditEvent{}.Fields()
	_ = auditeventFields
	// auditeventDescTs is the schema descriptor for ts field.
	auditeventDescTs := auditeventFields[1].Descriptor()
	// auditevent.DefaultTs holds the default value on creation for the ts field.
	auditevent.DefaultTs = auditeventDescTs.Default.(func() time.Time)
	capabilityMixin := schema.Capability{}.Mixin()
	capabilityMixinFields0 := capabilityMixin[0].Fields()
	_ = capabilityMixinFields0
	capabilityFields := schema.Capability{}.Fields()
	_ = capabilityFields
	// capabilityDescCreatedAt is the schema descriptor for created_at field.
	capabilityDescCreatedAt := capabilityMixinFields0[1].Descriptor()
	// capability.DefaultCreatedAt holds the default value on creation for the created_at field.
	capability.DefaultCreatedAt = capabilityDescCreatedAt.Default.(func() time.Time)
	// capabilityDescUpdatedAt is the schema descriptor for updated_at field.
	capabilityDescUpdatedAt := capabilityMixinFields0[2].Descriptor()
	// capability.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	capability.DefaultUpdatedAt = capabilityDescUpdatedAt.Default.(func() time.Time)
	// capability.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	capability.UpdateDefaultUpdatedAt = capabilityDescUpdatedAt.UpdateDefault.(func() time.Time)
	// capabilityDescEnforceableBy is the schema descriptor for enforceable_by field.
	capabilityDescEnforceableBy := capabilityFields[2].Descriptor()
	// capability.DefaultEnforceableBy holds the default value on creation for the enforceable_by field.
	capability.DefaultEnforceableBy = capabilityDescEnforceableBy.Default.([]string)
	// capabilityDescRequiresPattern is the schema descriptor for requires_pattern field.
	capabilityDescRequiresPattern := capabilityFields[3].Descriptor()
	// capability.DefaultRequiresPattern holds the default value on creation for the requires_pattern field.
	capability.DefaultRequiresPattern = capabilityDescRequiresPattern.Default.(bool)
	// capabilityDescReversible is the schema descriptor for reversible field.
	capabilityDescReversible := capabilityFields[4].Descriptor()
	// capability.DefaultReversible holds the default value on creation for the reversible field.
	capability.DefaultReversible = capabilityDescReversible.Default.(bool)
	// capabilityDescDescription is the schema descriptor for description field.
	capabilityDescDescription := capabilityFields[5].Descriptor()
	// capability.DefaultDescription holds the default value on creation for the description field.
	capability.DefaultDescription = capabilityDescDescription.Default.(string)
	checkpointFields := schema.Checkpoint{}.Fields()
	_ = checkpointFields
	// checkpointDescFilesChanged is the schema descriptor for files_changed field.
	checkpointDescFilesChanged := checkpointFields[6].Descriptor()
	// checkpoint.DefaultFilesChanged holds the default value on creation for the files_changed field.
	checkpoint.DefaultFilesChanged = checkpointDescFilesChanged.Default.(int)
	// checkpointDescPreRevert is the schema descriptor for pre_revert field.
	checkpointDescPreRevert := checkpointFields[7].Descriptor()
	// checkpoint.DefaultPreRevert holds the default value on creation for the pre_revert field.
	checkpoint.DefaultPreRevert = checkpointDescPreRevert.Default.(bool)
	// checkpointDescCreatedAt is the schema descriptor for created_at field.
	checkpointDescCreatedAt := checkpointFields[8].Descriptor()
	// checkpoint.DefaultCreatedAt holds the default value on creation for the created_at field.
	checkpoint.DefaultCreatedAt = checkpointDescCreatedAt.Default.(func() time.Time)
	coordlockFields := schema.CoordLock{}.Fields()
	_ = coordlockFields
	// coordlockDescAcquiredAt is the schema descriptor for acquired_at field.
	coordlockDescAcquiredAt := coordlockFields[4].Descriptor()
	// coordlock.DefaultAcquiredAt holds the default value on creation for the acquired_at field.
	coordlock.DefaultAcquiredAt = coordlockDescAcquiredAt.Default.(func() time.Time)
	driftalertFields := schema.DriftAlert{}.Fields()
	_ = driftalertFields
	// driftalertDescStatus is the schema descriptor for status field.
	driftalertDescStatus := driftalertFields[5].Descriptor()
	// driftalert.DefaultStatus holds the default value on creation for the status field.
	driftalert.DefaultStatus = driftalertDescStatus.Default.(string)
	// driftalertDescDetectedAt is the schema descriptor for detected_at field.
	driftalertDescDetectedAt := driftalertFields[12].Descriptor()
	// driftalert.DefaultDetectedAt holds the default value on creation for the detected_at field.
	driftalert.DefaultDetectedAt = driftalertDescDetectedAt.Default.(func() time.Time)
	evalmetricsnapshotFields := schema.EvalMetricSnapshot{}.Fields()
	_ = evalmetricsnapshotFields
	// evalmetricsnapshotDescRecordedAt is the schema descriptor for recorded_at field.
	evalmetricsnapshotDescRecordedAt := evalmetricsnapshotFields[9].Descriptor()
	// evalmetricsnapshot.DefaultRecordedAt holds the default value on creation for the recorded_at field.
	evalmetricsnapshot.DefaultRecordedAt = evalmetricsnapshotDescRecordedAt.Default.(func() time.Time)
	grantMixin := schema.Grant{}.Mixin()
	grantMixinFields0 := grantMixin[0].Fields()
	_ = grantMixinFields0
	grantFields := schema.Grant{}.Fields()
	_ = grantFields
	// grantDescCreatedAt is the schema descriptor for created_at field.
	grantDescCreatedAt := grantMixinFields0[1].Descriptor()
	// grant.DefaultCreatedAt holds the default value on creation for the created_at field.
	grant.DefaultCreatedAt = grantDescCreatedAt.Default.(func() time.Time)
	// grantDescUpdatedAt is the schema descriptor for updated_at field.
	grantDescUpdatedAt := grantMixinFields0[2].Descriptor()
	// grant.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	grant.DefaultUpdatedAt = grantDescUpdatedAt.Default.(func() time.Time)
	// grant.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	grant.UpdateDefaultUpdatedAt = grantDescUpdatedAt.UpdateDefault.(func() time.Time)
	// grantDescContextRef is the schema descriptor for context_ref field.
	grantDescContextRef := grantFields[2].Descriptor()
	// grant.DefaultContextRef holds the default value on creation for the context_ref field.
	grant.DefaultContextRef = grantDescContextRef.Default.(string)
	// grantDescPattern is the schema descriptor for pattern field.
	grantDescPattern := grantFields[3].Descriptor()
	// grant.DefaultPattern holds the default value on creation for the pattern field.
	grant.DefaultPattern = grantDescPattern.Default.(string)
	// grantDescLimitCount is the schema descriptor for limit_count field.
	grantDescLimitCount := grantFields[5].Descriptor()
	// grant.DefaultLimitCount holds the default value on creation for the limit_count field.
	grant.DefaultLimitCount = grantDescLimitCount.Default.(int)
	// grant.LimitCountValidator is a validator for the "limit_count" field. It is called by the builders before save.
	grant.LimitCountValidator = grantDescLimitCount.Validators[0].(func(int) error)
	// grantDescLimitWindowSeconds is the schema descriptor for limit_window_seconds field.
	grantDescLimitWindowSeconds := grantFields[6].Descriptor()
	// grant.DefaultLimitWindowSeconds holds the default value on creation for the limit_window_seconds field.
	grant.DefaultLimitWindowSeconds = grantDescLimitWindowSeconds.Default.(int)
	// grantDescGrantedAt is the schema descriptor for granted_at field.
	grantDescGrantedAt := grantFields[9].Descriptor()
	// grant.DefaultGrantedAt holds the default value on creation for the granted_at field.
	grant.DefaultGrantedAt = grantDescGrantedAt.Default.(func() time.Time)
	// grantDescRevokedBy is the schema descriptor for revoked_by field.
	grantDescRevokedBy := grantFields[11].Descriptor()
	// grant.DefaultRevokedBy holds the default value on creation for the revoked_by field.
	grant.DefaultRevokedBy = grantDescRevokedBy.Default.(string)
	// grantDescReason is the schema descriptor for reason field.
	grantDescReason := grantFields[12].Descriptor()
	// grant.DefaultReason holds the default value on creation for the reason field.
	grant.DefaultReason = grantDescReason.Default.(string)
	// grantDescNodeID is the schema descriptor for node_id field.
	grantDescNodeID := grantFields[13].Descriptor()
	// grant.DefaultNodeID holds the default value on creation for the node_id field.
	grant.DefaultNodeID = grantDescNodeID.Default.(string)
	grantusageMixin := schema.GrantUsage{}.Mixin()
	grantusageMixinFields0 := grantusageMixin[0].Fields()
	_ = grantusageMixinFields0
	grantusageFields := schema.GrantUsage{}.Fields()
	_ = grantusageFields
	// grantusageDescCreatedAt is the schema descriptor for created_at field.
	grantusageDescCreatedAt := grantusageMixinFields0[1].Descriptor()
	// grantusage.DefaultCreatedAt holds the default value on creation for the created_at field.
	grantusage.DefaultCreatedAt = grantusageDescCreatedAt.Default.(func() time.Time)
	// grantusageDescUpdatedAt is the schema descriptor for updated_at field.
	grantusageDescUpdatedAt := grantusageMixinFields0[2].Descriptor()
	// grantusage.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	grantusage.DefaultUpdatedAt = grantusageDescUpdatedAt.Default.(func() time.Time)
	// grantusage.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	grantusage.UpdateDefaultUpdatedAt = grantusageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// grantusageDescUsedAt is the schema descriptor for used_at field.
	grantusageDescUsedAt := grantusageFields[1].Descriptor()
	// grantusage.DefaultUsedAt holds the default value on creation for the used_at field.
	grantusage.DefaultUsedAt = grantusageDescUsedAt.Default.(func() time.Time)
	materializationMixin := schema.Materialization{}.Mixin()
	materializationMixinFields0 := materializationMixin[0].Fields()
	_ = materializationMixinFields0
	materializationFields := schema.Materialization{}.Fields()
	_ = materializationFields
	// materializationDescCreatedAt is the schema descriptor for created_at field.
	materializationDescCreatedAt := materializationMixinFields0[1].Descriptor()
	// materialization.DefaultCreatedAt holds the default value on creation for the created_at field.
	materialization.DefaultCreatedAt = materializationDescCreatedAt.Default.(func() time.Time)
	// materializationDescUpdatedAt is the schema descriptor for updated_at field.
	materializationDescUpdatedAt := materializationMixinFields0[2].Descriptor()
	// materialization.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	materialization.DefaultUpdatedAt = materializationDescUpdatedAt.Default.(func() time.Time)
	// materialization.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	materialization.UpdateDefaultUpdatedAt = materializationDescUpdatedAt.UpdateDefault.(func() time.Time)
	// materializationDescContentHash is the schema descriptor for content_hash field.
	materializationDescContentHash := materializationFields[3].Descriptor()
	// materialization.DefaultContentHash holds the default value on creation for the content_hash field.
	materialization.DefaultContentHash = materializationDescContentHash.Default.(string)
	// materializationDescOutcome is the schema descriptor for outcome field.
	materializationDescOutcome := materializationFields[4].Descriptor()
	// materialization.DefaultOutcome holds the default value on creation for the outcome field.
	materialization.DefaultOutcome = materializationDescOutcome.Default.(string)
	memoryentryMixin := schema.MemoryEntry{}.Mixin()
	memoryentryMixinFields0 := memoryentryMixin[0].Fields()
	_ = memoryentryMixinFields0
	memoryentryFields := schema.MemoryEntry{}.Fields()
	_ = memoryentryFields
	// memoryentryDescCreatedAt is the schema descriptor for created_at field.
	memoryentryDescCreatedAt := memoryentryMixinFields0[1].Descriptor()
	// memoryentry.DefaultCreatedAt holds the default value on creation for the created_at field.
	memoryentry.DefaultCreatedAt = memoryentryDescCreatedAt.Default.(func() time.Time)
	// memoryentryDescUpdatedAt is the schema descriptor for updated_at field.
	memoryentryDescUpdatedAt := memoryentryMixinFields0[2].Descriptor()
	// memoryentry.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	memoryentry.DefaultUpdatedAt = memoryentryDescUpdatedAt.Default.(func() time.Time)
	// memoryentry.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	memoryentry.UpdateDefaultUpdatedAt = memoryentryDescUpdatedAt.UpdateDefault.(func() time.Time)
	// memoryentryDescConfidence is the schema descriptor for confidence field.
	memoryentryDescConfidence := memoryentryFields[6].Descriptor()
	// memoryentry.ConfidenceValidator is a validator for the "confidence" field. It is called by the builders before save.
	memoryentry.ConfidenceValidator = func() func(float64) error {
		validators := memoryentryDescConfidence.Validators
		fns := [...]func(float64) error{
			validators[0].(func(float64) error),
			validators[1].(func(float64) error),
		}
		return func(confidence float64) error {
			for _, fn := range fns {
				if err := fn(confidence); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// memoryentryDescValidFrom is the schema descriptor for valid_from field.
	memoryentryDescValidFrom := memoryentryFields[7].Descriptor()
	// memoryentry.DefaultValidFrom holds the default value on creation for the valid_from field.
	memoryentry.DefaultValidFrom = memoryentryDescValidFrom.Default.(func() time.Time)
	memoryinjectionMixin := schema.MemoryInjection{}.Mixin()
	memoryinjectionMixinFields0 := memoryinjectionMixin[0].Fields()
	_ = memoryinjectionMixinFields0
	memoryinjectionFields := schema.MemoryInjection{}.Fields()
	_ = memoryinjectionFields
	// memoryinjectionDescCreatedAt is the schema descriptor for created_at field.
	memoryinjectionDescCreatedAt := memoryinjectionMixinFields0[1].Descriptor()
	// memoryinjection.DefaultCreatedAt holds the default value on creation for the created_at field.
	memoryinjection.DefaultCreatedAt = memoryinjectionDescCreatedAt.Default.(func() time.Time)
	// memoryinjectionDescUpdatedAt is the schema descriptor for updated_at field.
	memoryinjectionDescUpdatedAt := memoryinjectionMixinFields0[2].Descriptor()
	// memoryinjection.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	memoryinjection.DefaultUpdatedAt = memoryinjectionDescUpdatedAt.Default.(func() time.Time)
	// memoryinjection.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	memoryinjection.UpdateDefaultUpdatedAt = memoryinjectionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// memoryinjectionDescEntryIds is the schema descriptor for entry_ids field.
	memoryinjectionDescEntryIds := memoryinjectionFields[1].Descriptor()
	// memoryinjection.DefaultEntryIds holds the default value on creation for the entry_ids field.
	memoryinjection.DefaultEntryIds = memoryinjectionDescEntryIds.Default.([]string)
	permissionrequestFields := schema.PermissionRequest{}.Fields()
	_ = permissionrequestFields
	// permissionrequestDescRequestedAt is the schema descriptor for requested_at field.
	permissionrequestDescRequestedAt := permissionrequestFields[6].Descriptor()
	// permissionrequest.DefaultRequestedAt holds the default value on creation for the requested_at field.
	permissionrequest.DefaultRequestedAt = permissionrequestDescRequestedAt.Default.(func() time.Time)
	pipelineconfigFields := schema.PipelineConfig{}.Fields()
	_ = pipelineconfigFields
	// pipelineconfigDescProjectID is the schema descriptor for project_id field.
	pipelineconfigDescProjectID := pipelineconfigFields[2].Descriptor()
	// pipelineconfig.DefaultProjectID holds the default value on creation for the project_id field.
	pipelineconfig.DefaultProjectID = pipelineconfigDescProjectID.Default.(string)
	pluginFields := schema.Plugin{}.Fields()
	_ = pluginFields
	// pluginDescName is the schema descriptor for name field.
	pluginDescName := pluginFields[1].Descriptor()
	// plugin.DefaultName holds the default value on creation for the name field.
	plugin.DefaultName = pluginDescName.Default.(string)
	// pluginDescVersion is the schema descriptor for version field.
	pluginDescVersion := pluginFields[2].Descriptor()
	// plugin.DefaultVersion holds the default value on creation for the version field.
	plugin.DefaultVersion = pluginDescVersion.Default.(string)
	// pluginDescActive is the schema descriptor for active field.
	pluginDescActive := pluginFields[4].Descriptor()
	// plugin.DefaultActive holds the default value on creation for the active field.
	plugin.DefaultActive = pluginDescActive.Default.(bool)
	// pluginDescPath is the schema descriptor for path field.
	pluginDescPath := pluginFields[5].Descriptor()
	// plugin.DefaultPath holds the default value on creation for the path field.
	plugin.DefaultPath = pluginDescPath.Default.(string)
	// pluginDescManifestHash is the schema descriptor for manifest_hash field.
	pluginDescManifestHash := pluginFields[6].Descriptor()
	// plugin.DefaultManifestHash holds the default value on creation for the manifest_hash field.
	plugin.DefaultManifestHash = pluginDescManifestHash.Default.(string)
	// pluginDescResourceID is the schema descriptor for resource_id field.
	pluginDescResourceID := pluginFields[7].Descriptor()
	// plugin.DefaultResourceID holds the default value on creation for the resource_id field.
	plugin.DefaultResourceID = pluginDescResourceID.Default.(string)
	// pluginDescCreatedAt is the schema descriptor for created_at field.
	pluginDescCreatedAt := pluginFields[8].Descriptor()
	// plugin.DefaultCreatedAt holds the default value on creation for the created_at field.
	plugin.DefaultCreatedAt = pluginDescCreatedAt.Default.(func() time.Time)
	// pluginDescUpdatedAt is the schema descriptor for updated_at field.
	pluginDescUpdatedAt := pluginFields[9].Descriptor()
	// plugin.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	plugin.DefaultUpdatedAt = pluginDescUpdatedAt.Default.(func() time.Time)
	// plugin.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	plugin.UpdateDefaultUpdatedAt = pluginDescUpdatedAt.UpdateDefault.(func() time.Time)
	pluginsettingFields := schema.PluginSetting{}.Fields()
	_ = pluginsettingFields
	// pluginsettingDescValue is the schema descriptor for value field.
	pluginsettingDescValue := pluginsettingFields[3].Descriptor()
	// pluginsetting.DefaultValue holds the default value on creation for the value field.
	pluginsetting.DefaultValue = pluginsettingDescValue.Default.(string)
	// pluginsettingDescSecret is the schema descriptor for secret field.
	pluginsettingDescSecret := pluginsettingFields[4].Descriptor()
	// pluginsetting.DefaultSecret holds the default value on creation for the secret field.
	pluginsetting.DefaultSecret = pluginsettingDescSecret.Default.(bool)
	// pluginsettingDescNonce is the schema descriptor for nonce field.
	pluginsettingDescNonce := pluginsettingFields[5].Descriptor()
	// pluginsetting.DefaultNonce holds the default value on creation for the nonce field.
	pluginsetting.DefaultNonce = pluginsettingDescNonce.Default.(string)
	// pluginsettingDescCreatedAt is the schema descriptor for created_at field.
	pluginsettingDescCreatedAt := pluginsettingFields[6].Descriptor()
	// pluginsetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	pluginsetting.DefaultCreatedAt = pluginsettingDescCreatedAt.Default.(func() time.Time)
	// pluginsettingDescUpdatedAt is the schema descriptor for updated_at field.
	pluginsettingDescUpdatedAt := pluginsettingFields[7].Descriptor()
	// pluginsetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	pluginsetting.DefaultUpdatedAt = pluginsettingDescUpdatedAt.Default.(func() time.Time)
	// pluginsetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	pluginsetting.UpdateDefaultUpdatedAt = pluginsettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	projectFields := schema.Project{}.Fields()
	_ = projectFields
	// projectDescCreatedAt is the schema descriptor for created_at field.
	projectDescCreatedAt := projectFields[7].Descriptor()
	// project.DefaultCreatedAt holds the default value on creation for the created_at field.
	project.DefaultCreatedAt = projectDescCreatedAt.Default.(func() time.Time)
	// projectDescUpdatedAt is the schema descriptor for updated_at field.
	projectDescUpdatedAt := projectFields[8].Descriptor()
	// project.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	project.DefaultUpdatedAt = projectDescUpdatedAt.Default.(func() time.Time)
	// project.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	project.UpdateDefaultUpdatedAt = projectDescUpdatedAt.UpdateDefault.(func() time.Time)
	projectfolderFields := schema.ProjectFolder{}.Fields()
	_ = projectfolderFields
	// projectfolderDescPath is the schema descriptor for path field.
	projectfolderDescPath := projectfolderFields[1].Descriptor()
	// projectfolder.PathValidator is a validator for the "path" field. It is called by the builders before save.
	projectfolder.PathValidator = projectfolderDescPath.Validators[0].(func(string) error)
	// projectfolderDescIsDefault is the schema descriptor for is_default field.
	projectfolderDescIsDefault := projectfolderFields[3].Descriptor()
	// projectfolder.DefaultIsDefault holds the default value on creation for the is_default field.
	projectfolder.DefaultIsDefault = projectfolderDescIsDefault.Default.(bool)
	// projectfolderDescCreatedAt is the schema descriptor for created_at field.
	projectfolderDescCreatedAt := projectfolderFields[4].Descriptor()
	// projectfolder.DefaultCreatedAt holds the default value on creation for the created_at field.
	projectfolder.DefaultCreatedAt = projectfolderDescCreatedAt.Default.(func() time.Time)
	prompttemplateFields := schema.PromptTemplate{}.Fields()
	_ = prompttemplateFields
	// prompttemplateDescCreatedAt is the schema descriptor for created_at field.
	prompttemplateDescCreatedAt := prompttemplateFields[3].Descriptor()
	// prompttemplate.DefaultCreatedAt holds the default value on creation for the created_at field.
	prompttemplate.DefaultCreatedAt = prompttemplateDescCreatedAt.Default.(func() time.Time)
	providersettingFields := schema.ProviderSetting{}.Fields()
	_ = providersettingFields
	// providersettingDescEnabled is the schema descriptor for enabled field.
	providersettingDescEnabled := providersettingFields[2].Descriptor()
	// providersetting.DefaultEnabled holds the default value on creation for the enabled field.
	providersetting.DefaultEnabled = providersettingDescEnabled.Default.(bool)
	// providersettingDescCreatedAt is the schema descriptor for created_at field.
	providersettingDescCreatedAt := providersettingFields[3].Descriptor()
	// providersetting.DefaultCreatedAt holds the default value on creation for the created_at field.
	providersetting.DefaultCreatedAt = providersettingDescCreatedAt.Default.(func() time.Time)
	// providersettingDescUpdatedAt is the schema descriptor for updated_at field.
	providersettingDescUpdatedAt := providersettingFields[4].Descriptor()
	// providersetting.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	providersetting.DefaultUpdatedAt = providersettingDescUpdatedAt.Default.(func() time.Time)
	// providersetting.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	providersetting.UpdateDefaultUpdatedAt = providersettingDescUpdatedAt.UpdateDefault.(func() time.Time)
	refinementturnFields := schema.RefinementTurn{}.Fields()
	_ = refinementturnFields
	// refinementturnDescCreatedAt is the schema descriptor for created_at field.
	refinementturnDescCreatedAt := refinementturnFields[6].Descriptor()
	// refinementturn.DefaultCreatedAt holds the default value on creation for the created_at field.
	refinementturn.DefaultCreatedAt = refinementturnDescCreatedAt.Default.(func() time.Time)
	remoteregistrationFields := schema.RemoteRegistration{}.Fields()
	_ = remoteregistrationFields
	// remoteregistrationDescCreatedAt is the schema descriptor for created_at field.
	remoteregistrationDescCreatedAt := remoteregistrationFields[5].Descriptor()
	// remoteregistration.DefaultCreatedAt holds the default value on creation for the created_at field.
	remoteregistration.DefaultCreatedAt = remoteregistrationDescCreatedAt.Default.(func() time.Time)
	resourceMixin := schema.Resource{}.Mixin()
	resourceMixinFields0 := resourceMixin[0].Fields()
	_ = resourceMixinFields0
	resourceFields := schema.Resource{}.Fields()
	_ = resourceFields
	// resourceDescCreatedAt is the schema descriptor for created_at field.
	resourceDescCreatedAt := resourceMixinFields0[1].Descriptor()
	// resource.DefaultCreatedAt holds the default value on creation for the created_at field.
	resource.DefaultCreatedAt = resourceDescCreatedAt.Default.(func() time.Time)
	// resourceDescUpdatedAt is the schema descriptor for updated_at field.
	resourceDescUpdatedAt := resourceMixinFields0[2].Descriptor()
	// resource.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	resource.DefaultUpdatedAt = resourceDescUpdatedAt.Default.(func() time.Time)
	// resource.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	resource.UpdateDefaultUpdatedAt = resourceDescUpdatedAt.UpdateDefault.(func() time.Time)
	// resourceDescName is the schema descriptor for name field.
	resourceDescName := resourceFields[2].Descriptor()
	// resource.DefaultName holds the default value on creation for the name field.
	resource.DefaultName = resourceDescName.Default.(string)
	// resourceDescScopeKind is the schema descriptor for scope_kind field.
	resourceDescScopeKind := resourceFields[3].Descriptor()
	// resource.DefaultScopeKind holds the default value on creation for the scope_kind field.
	resource.DefaultScopeKind = resourceDescScopeKind.Default.(string)
	// resourceDescScopeRef is the schema descriptor for scope_ref field.
	resourceDescScopeRef := resourceFields[4].Descriptor()
	// resource.DefaultScopeRef holds the default value on creation for the scope_ref field.
	resource.DefaultScopeRef = resourceDescScopeRef.Default.(string)
	// resourceDescNodeID is the schema descriptor for node_id field.
	resourceDescNodeID := resourceFields[5].Descriptor()
	// resource.DefaultNodeID holds the default value on creation for the node_id field.
	resource.DefaultNodeID = resourceDescNodeID.Default.(string)
	// resourceDescState is the schema descriptor for state field.
	resourceDescState := resourceFields[6].Descriptor()
	// resource.DefaultState holds the default value on creation for the state field.
	resource.DefaultState = resourceDescState.Default.(string)
	// resourceDescVersion is the schema descriptor for version field.
	resourceDescVersion := resourceFields[7].Descriptor()
	// resource.DefaultVersion holds the default value on creation for the version field.
	resource.DefaultVersion = resourceDescVersion.Default.(string)
	// resourceDescOrigin is the schema descriptor for origin field.
	resourceDescOrigin := resourceFields[8].Descriptor()
	// resource.DefaultOrigin holds the default value on creation for the origin field.
	resource.DefaultOrigin = resourceDescOrigin.Default.(string)
	// resourceDescOriginRef is the schema descriptor for origin_ref field.
	resourceDescOriginRef := resourceFields[9].Descriptor()
	// resource.DefaultOriginRef holds the default value on creation for the origin_ref field.
	resource.DefaultOriginRef = resourceDescOriginRef.Default.(string)
	scratchpadFields := schema.Scratchpad{}.Fields()
	_ = scratchpadFields
	// scratchpadDescUpdatedAt is the schema descriptor for updated_at field.
	scratchpadDescUpdatedAt := scratchpadFields[4].Descriptor()
	// scratchpad.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	scratchpad.DefaultUpdatedAt = scratchpadDescUpdatedAt.Default.(func() time.Time)
	// scratchpad.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	scratchpad.UpdateDefaultUpdatedAt = scratchpadDescUpdatedAt.UpdateDefault.(func() time.Time)
	skillMixin := schema.Skill{}.Mixin()
	skillMixinFields0 := skillMixin[0].Fields()
	_ = skillMixinFields0
	skillFields := schema.Skill{}.Fields()
	_ = skillFields
	// skillDescCreatedAt is the schema descriptor for created_at field.
	skillDescCreatedAt := skillMixinFields0[1].Descriptor()
	// skill.DefaultCreatedAt holds the default value on creation for the created_at field.
	skill.DefaultCreatedAt = skillDescCreatedAt.Default.(func() time.Time)
	// skillDescUpdatedAt is the schema descriptor for updated_at field.
	skillDescUpdatedAt := skillMixinFields0[2].Descriptor()
	// skill.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	skill.DefaultUpdatedAt = skillDescUpdatedAt.Default.(func() time.Time)
	// skill.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	skill.UpdateDefaultUpdatedAt = skillDescUpdatedAt.UpdateDefault.(func() time.Time)
	// skillDescDescription is the schema descriptor for description field.
	skillDescDescription := skillFields[1].Descriptor()
	// skill.DefaultDescription holds the default value on creation for the description field.
	skill.DefaultDescription = skillDescDescription.Default.(string)
	// skillDescBody is the schema descriptor for body field.
	skillDescBody := skillFields[2].Descriptor()
	// skill.DefaultBody holds the default value on creation for the body field.
	skill.DefaultBody = skillDescBody.Default.(string)
	spawnerFields := schema.Spawner{}.Fields()
	_ = spawnerFields
	// spawnerDescArgs is the schema descriptor for args field.
	spawnerDescArgs := spawnerFields[4].Descriptor()
	// spawner.DefaultArgs holds the default value on creation for the args field.
	spawner.DefaultArgs = spawnerDescArgs.Default.([]string)
	// spawnerDescEnv is the schema descriptor for env field.
	spawnerDescEnv := spawnerFields[5].Descriptor()
	// spawner.DefaultEnv holds the default value on creation for the env field.
	spawner.DefaultEnv = spawnerDescEnv.Default.(map[string]string)
	// spawnerDescAdapterType is the schema descriptor for adapter_type field.
	spawnerDescAdapterType := spawnerFields[6].Descriptor()
	// spawner.DefaultAdapterType holds the default value on creation for the adapter_type field.
	spawner.DefaultAdapterType = spawnerDescAdapterType.Default.(string)
	// spawnerDescAdapterConfig is the schema descriptor for adapter_config field.
	spawnerDescAdapterConfig := spawnerFields[7].Descriptor()
	// spawner.DefaultAdapterConfig holds the default value on creation for the adapter_config field.
	spawner.DefaultAdapterConfig = spawnerDescAdapterConfig.Default.(map[string]string)
	// spawnerDescBuiltIn is the schema descriptor for built_in field.
	spawnerDescBuiltIn := spawnerFields[10].Descriptor()
	// spawner.DefaultBuiltIn holds the default value on creation for the built_in field.
	spawner.DefaultBuiltIn = spawnerDescBuiltIn.Default.(bool)
	// spawnerDescIsDefault is the schema descriptor for is_default field.
	spawnerDescIsDefault := spawnerFields[11].Descriptor()
	// spawner.DefaultIsDefault holds the default value on creation for the is_default field.
	spawner.DefaultIsDefault = spawnerDescIsDefault.Default.(bool)
	// spawnerDescCreatedAt is the schema descriptor for created_at field.
	spawnerDescCreatedAt := spawnerFields[12].Descriptor()
	// spawner.DefaultCreatedAt holds the default value on creation for the created_at field.
	spawner.DefaultCreatedAt = spawnerDescCreatedAt.Default.(func() time.Time)
	// spawnerDescUpdatedAt is the schema descriptor for updated_at field.
	spawnerDescUpdatedAt := spawnerFields[13].Descriptor()
	// spawner.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	spawner.DefaultUpdatedAt = spawnerDescUpdatedAt.Default.(func() time.Time)
	// spawner.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	spawner.UpdateDefaultUpdatedAt = spawnerDescUpdatedAt.UpdateDefault.(func() time.Time)
	stagerunFields := schema.StageRun{}.Fields()
	_ = stagerunFields
	// stagerunDescStatus is the schema descriptor for status field.
	stagerunDescStatus := stagerunFields[6].Descriptor()
	// stagerun.DefaultStatus holds the default value on creation for the status field.
	stagerun.DefaultStatus = stagerunDescStatus.Default.(string)
	// stagerunDescIteration is the schema descriptor for iteration field.
	stagerunDescIteration := stagerunFields[7].Descriptor()
	// stagerun.DefaultIteration holds the default value on creation for the iteration field.
	stagerun.DefaultIteration = stagerunDescIteration.Default.(int)
	// stagerunDescTokensUsed is the schema descriptor for tokens_used field.
	stagerunDescTokensUsed := stagerunFields[9].Descriptor()
	// stagerun.DefaultTokensUsed holds the default value on creation for the tokens_used field.
	stagerun.DefaultTokensUsed = stagerunDescTokensUsed.Default.(int)
	// stagerunDescCostCents is the schema descriptor for cost_cents field.
	stagerunDescCostCents := stagerunFields[10].Descriptor()
	// stagerun.DefaultCostCents holds the default value on creation for the cost_cents field.
	stagerun.DefaultCostCents = stagerunDescCostCents.Default.(int)
	// stagerunDescRetryCount is the schema descriptor for retry_count field.
	stagerunDescRetryCount := stagerunFields[14].Descriptor()
	// stagerun.DefaultRetryCount holds the default value on creation for the retry_count field.
	stagerun.DefaultRetryCount = stagerunDescRetryCount.Default.(int)
	// stagerunDescCreatedAt is the schema descriptor for created_at field.
	stagerunDescCreatedAt := stagerunFields[17].Descriptor()
	// stagerun.DefaultCreatedAt holds the default value on creation for the created_at field.
	stagerun.DefaultCreatedAt = stagerunDescCreatedAt.Default.(func() time.Time)
	systempromptFields := schema.SystemPrompt{}.Fields()
	_ = systempromptFields
	// systempromptDescScope is the schema descriptor for scope field.
	systempromptDescScope := systempromptFields[1].Descriptor()
	// systemprompt.DefaultScope holds the default value on creation for the scope field.
	systemprompt.DefaultScope = systempromptDescScope.Default.(string)
	// systempromptDescPriority is the schema descriptor for priority field.
	systempromptDescPriority := systempromptFields[4].Descriptor()
	// systemprompt.DefaultPriority holds the default value on creation for the priority field.
	systemprompt.DefaultPriority = systempromptDescPriority.Default.(int)
	// systempromptDescCreatedAt is the schema descriptor for created_at field.
	systempromptDescCreatedAt := systempromptFields[6].Descriptor()
	// systemprompt.DefaultCreatedAt holds the default value on creation for the created_at field.
	systemprompt.DefaultCreatedAt = systempromptDescCreatedAt.Default.(func() time.Time)
	// systempromptDescUpdatedAt is the schema descriptor for updated_at field.
	systempromptDescUpdatedAt := systempromptFields[7].Descriptor()
	// systemprompt.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	systemprompt.DefaultUpdatedAt = systempromptDescUpdatedAt.Default.(func() time.Time)
	// systemprompt.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	systemprompt.UpdateDefaultUpdatedAt = systempromptDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskFields := schema.Task{}.Fields()
	_ = taskFields
	// taskDescTitle is the schema descriptor for title field.
	taskDescTitle := taskFields[2].Descriptor()
	// task.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	task.TitleValidator = taskDescTitle.Validators[0].(func(string) error)
	// taskDescCwd is the schema descriptor for cwd field.
	taskDescCwd := taskFields[4].Descriptor()
	// task.CwdValidator is a validator for the "cwd" field. It is called by the builders before save.
	task.CwdValidator = taskDescCwd.Validators[0].(func(string) error)
	// taskDescCurrentStage is the schema descriptor for current_stage field.
	taskDescCurrentStage := taskFields[8].Descriptor()
	// task.DefaultCurrentStage holds the default value on creation for the current_stage field.
	task.DefaultCurrentStage = taskDescCurrentStage.Default.(string)
	// taskDescPriority is the schema descriptor for priority field.
	taskDescPriority := taskFields[9].Descriptor()
	// task.DefaultPriority holds the default value on creation for the priority field.
	task.DefaultPriority = taskDescPriority.Default.(string)
	// taskDescMaxIterations is the schema descriptor for max_iterations field.
	taskDescMaxIterations := taskFields[13].Descriptor()
	// task.DefaultMaxIterations holds the default value on creation for the max_iterations field.
	task.DefaultMaxIterations = taskDescMaxIterations.Default.(int)
	// taskDescStageTimeoutSeconds is the schema descriptor for stage_timeout_seconds field.
	taskDescStageTimeoutSeconds := taskFields[16].Descriptor()
	// task.DefaultStageTimeoutSeconds holds the default value on creation for the stage_timeout_seconds field.
	task.DefaultStageTimeoutSeconds = taskDescStageTimeoutSeconds.Default.(int)
	// taskDescSilverBullet is the schema descriptor for silver_bullet field.
	taskDescSilverBullet := taskFields[17].Descriptor()
	// task.DefaultSilverBullet holds the default value on creation for the silver_bullet field.
	task.DefaultSilverBullet = taskDescSilverBullet.Default.(bool)
	// taskDescPlanMode is the schema descriptor for plan_mode field.
	taskDescPlanMode := taskFields[18].Descriptor()
	// task.DefaultPlanMode holds the default value on creation for the plan_mode field.
	task.DefaultPlanMode = taskDescPlanMode.Default.(bool)
	// taskDescAutonomy is the schema descriptor for autonomy field.
	taskDescAutonomy := taskFields[19].Descriptor()
	// task.DefaultAutonomy holds the default value on creation for the autonomy field.
	task.DefaultAutonomy = taskDescAutonomy.Default.(string)
	// taskDescCreatedAt is the schema descriptor for created_at field.
	taskDescCreatedAt := taskFields[25].Descriptor()
	// task.DefaultCreatedAt holds the default value on creation for the created_at field.
	task.DefaultCreatedAt = taskDescCreatedAt.Default.(func() time.Time)
	// taskDescUpdatedAt is the schema descriptor for updated_at field.
	taskDescUpdatedAt := taskFields[26].Descriptor()
	// task.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	task.DefaultUpdatedAt = taskDescUpdatedAt.Default.(func() time.Time)
	// task.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	task.UpdateDefaultUpdatedAt = taskDescUpdatedAt.UpdateDefault.(func() time.Time)
	taskdependencyFields := schema.TaskDependency{}.Fields()
	_ = taskdependencyFields
	// taskdependencyDescRequiredStage is the schema descriptor for required_stage field.
	taskdependencyDescRequiredStage := taskdependencyFields[3].Descriptor()
	// taskdependency.DefaultRequiredStage holds the default value on creation for the required_stage field.
	taskdependency.DefaultRequiredStage = taskdependencyDescRequiredStage.Default.(string)
	// taskdependencyDescOnCancelAction is the schema descriptor for on_cancel_action field.
	taskdependencyDescOnCancelAction := taskdependencyFields[4].Descriptor()
	// taskdependency.DefaultOnCancelAction holds the default value on creation for the on_cancel_action field.
	taskdependency.DefaultOnCancelAction = taskdependencyDescOnCancelAction.Default.(string)
	taskpermissionFields := schema.TaskPermission{}.Fields()
	_ = taskpermissionFields
	// taskpermissionDescGranted is the schema descriptor for granted field.
	taskpermissionDescGranted := taskpermissionFields[4].Descriptor()
	// taskpermission.DefaultGranted holds the default value on creation for the granted field.
	taskpermission.DefaultGranted = taskpermissionDescGranted.Default.(bool)
	// taskpermissionDescManualOverride is the schema descriptor for manual_override field.
	taskpermissionDescManualOverride := taskpermissionFields[5].Descriptor()
	// taskpermission.DefaultManualOverride holds the default value on creation for the manual_override field.
	taskpermission.DefaultManualOverride = taskpermissionDescManualOverride.Default.(bool)
	// taskpermissionDescRequestedAt is the schema descriptor for requested_at field.
	taskpermissionDescRequestedAt := taskpermissionFields[7].Descriptor()
	// taskpermission.DefaultRequestedAt holds the default value on creation for the requested_at field.
	taskpermission.DefaultRequestedAt = taskpermissionDescRequestedAt.Default.(func() time.Time)
	taskscheduleFields := schema.TaskSchedule{}.Fields()
	_ = taskscheduleFields
	// taskscheduleDescName is the schema descriptor for name field.
	taskscheduleDescName := taskscheduleFields[1].Descriptor()
	// taskschedule.NameValidator is a validator for the "name" field. It is called by the builders before save.
	taskschedule.NameValidator = taskscheduleDescName.Validators[0].(func(string) error)
	// taskscheduleDescEnabled is the schema descriptor for enabled field.
	taskscheduleDescEnabled := taskscheduleFields[2].Descriptor()
	// taskschedule.DefaultEnabled holds the default value on creation for the enabled field.
	taskschedule.DefaultEnabled = taskscheduleDescEnabled.Default.(bool)
	// taskscheduleDescTimezone is the schema descriptor for timezone field.
	taskscheduleDescTimezone := taskscheduleFields[5].Descriptor()
	// taskschedule.DefaultTimezone holds the default value on creation for the timezone field.
	taskschedule.DefaultTimezone = taskscheduleDescTimezone.Default.(string)
	// taskscheduleDescCatchup is the schema descriptor for catchup field.
	taskscheduleDescCatchup := taskscheduleFields[6].Descriptor()
	// taskschedule.DefaultCatchup holds the default value on creation for the catchup field.
	taskschedule.DefaultCatchup = taskscheduleDescCatchup.Default.(string)
	// taskscheduleDescSlugPrefix is the schema descriptor for slug_prefix field.
	taskscheduleDescSlugPrefix := taskscheduleFields[7].Descriptor()
	// taskschedule.SlugPrefixValidator is a validator for the "slug_prefix" field. It is called by the builders before save.
	taskschedule.SlugPrefixValidator = taskscheduleDescSlugPrefix.Validators[0].(func(string) error)
	// taskscheduleDescTitle is the schema descriptor for title field.
	taskscheduleDescTitle := taskscheduleFields[8].Descriptor()
	// taskschedule.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	taskschedule.TitleValidator = taskscheduleDescTitle.Validators[0].(func(string) error)
	// taskscheduleDescCwd is the schema descriptor for cwd field.
	taskscheduleDescCwd := taskscheduleFields[10].Descriptor()
	// taskschedule.CwdValidator is a validator for the "cwd" field. It is called by the builders before save.
	taskschedule.CwdValidator = taskscheduleDescCwd.Validators[0].(func(string) error)
	// taskscheduleDescPriority is the schema descriptor for priority field.
	taskscheduleDescPriority := taskscheduleFields[13].Descriptor()
	// taskschedule.DefaultPriority holds the default value on creation for the priority field.
	taskschedule.DefaultPriority = taskscheduleDescPriority.Default.(string)
	// taskscheduleDescCurrentStage is the schema descriptor for current_stage field.
	taskscheduleDescCurrentStage := taskscheduleFields[14].Descriptor()
	// taskschedule.DefaultCurrentStage holds the default value on creation for the current_stage field.
	taskschedule.DefaultCurrentStage = taskscheduleDescCurrentStage.Default.(string)
	// taskscheduleDescMaxIterations is the schema descriptor for max_iterations field.
	taskscheduleDescMaxIterations := taskscheduleFields[15].Descriptor()
	// taskschedule.DefaultMaxIterations holds the default value on creation for the max_iterations field.
	taskschedule.DefaultMaxIterations = taskscheduleDescMaxIterations.Default.(int)
	// taskscheduleDescStageTimeoutSeconds is the schema descriptor for stage_timeout_seconds field.
	taskscheduleDescStageTimeoutSeconds := taskscheduleFields[18].Descriptor()
	// taskschedule.DefaultStageTimeoutSeconds holds the default value on creation for the stage_timeout_seconds field.
	taskschedule.DefaultStageTimeoutSeconds = taskscheduleDescStageTimeoutSeconds.Default.(int)
	// taskscheduleDescSilverBullet is the schema descriptor for silver_bullet field.
	taskscheduleDescSilverBullet := taskscheduleFields[19].Descriptor()
	// taskschedule.DefaultSilverBullet holds the default value on creation for the silver_bullet field.
	taskschedule.DefaultSilverBullet = taskscheduleDescSilverBullet.Default.(bool)
	// taskscheduleDescResourceID is the schema descriptor for resource_id field.
	taskscheduleDescResourceID := taskscheduleFields[27].Descriptor()
	// taskschedule.DefaultResourceID holds the default value on creation for the resource_id field.
	taskschedule.DefaultResourceID = taskscheduleDescResourceID.Default.(string)
	// taskscheduleDescCreatedAt is the schema descriptor for created_at field.
	taskscheduleDescCreatedAt := taskscheduleFields[29].Descriptor()
	// taskschedule.DefaultCreatedAt holds the default value on creation for the created_at field.
	taskschedule.DefaultCreatedAt = taskscheduleDescCreatedAt.Default.(func() time.Time)
	// taskscheduleDescUpdatedAt is the schema descriptor for updated_at field.
	taskscheduleDescUpdatedAt := taskscheduleFields[30].Descriptor()
	// taskschedule.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	taskschedule.DefaultUpdatedAt = taskscheduleDescUpdatedAt.Default.(func() time.Time)
	// taskschedule.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	taskschedule.UpdateDefaultUpdatedAt = taskscheduleDescUpdatedAt.UpdateDefault.(func() time.Time)
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescIsAdmin is the schema descriptor for is_admin field.
	userDescIsAdmin := userFields[4].Descriptor()
	// user.DefaultIsAdmin holds the default value on creation for the is_admin field.
	user.DefaultIsAdmin = userDescIsAdmin.Default.(bool)
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userFields[5].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
}
