// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/permissionrequest"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/stagerun"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/task"
)

// StageRunCreate is the builder for creating a StageRun entity.
type StageRunCreate struct {
	config
	mutation *StageRunMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetTaskID sets the "task_id" field.
func (_c *StageRunCreate) SetTaskID(v string) *StageRunCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetStage sets the "stage" field.
func (_c *StageRunCreate) SetStage(v string) *StageRunCreate {
	_c.mutation.SetStage(v)
	return _c
}

// SetSessionID sets the "session_id" field.
func (_c *StageRunCreate) SetSessionID(v string) *StageRunCreate {
	_c.mutation.SetSessionID(v)
	return _c
}

// SetNillableSessionID sets the "session_id" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableSessionID(v *string) *StageRunCreate {
	if v != nil {
		_c.SetSessionID(*v)
	}
	return _c
}

// SetSessionName sets the "session_name" field.
func (_c *StageRunCreate) SetSessionName(v string) *StageRunCreate {
	_c.mutation.SetSessionName(v)
	return _c
}

// SetNillableSessionName sets the "session_name" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableSessionName(v *string) *StageRunCreate {
	if v != nil {
		_c.SetSessionName(*v)
	}
	return _c
}

// SetPid sets the "pid" field.
func (_c *StageRunCreate) SetPid(v int) *StageRunCreate {
	_c.mutation.SetPid(v)
	return _c
}

// SetNillablePid sets the "pid" field if the given value is not nil.
func (_c *StageRunCreate) SetNillablePid(v *int) *StageRunCreate {
	if v != nil {
		_c.SetPid(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *StageRunCreate) SetStatus(v string) *StageRunCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableStatus(v *string) *StageRunCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetIteration sets the "iteration" field.
func (_c *StageRunCreate) SetIteration(v int) *StageRunCreate {
	_c.mutation.SetIteration(v)
	return _c
}

// SetNillableIteration sets the "iteration" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableIteration(v *int) *StageRunCreate {
	if v != nil {
		_c.SetIteration(*v)
	}
	return _c
}

// SetOutput sets the "output" field.
func (_c *StageRunCreate) SetOutput(v map[string]interface{}) *StageRunCreate {
	_c.mutation.SetOutput(v)
	return _c
}

// SetTokensUsed sets the "tokens_used" field.
func (_c *StageRunCreate) SetTokensUsed(v int) *StageRunCreate {
	_c.mutation.SetTokensUsed(v)
	return _c
}

// SetNillableTokensUsed sets the "tokens_used" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableTokensUsed(v *int) *StageRunCreate {
	if v != nil {
		_c.SetTokensUsed(*v)
	}
	return _c
}

// SetCostCents sets the "cost_cents" field.
func (_c *StageRunCreate) SetCostCents(v int) *StageRunCreate {
	_c.mutation.SetCostCents(v)
	return _c
}

// SetNillableCostCents sets the "cost_cents" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableCostCents(v *int) *StageRunCreate {
	if v != nil {
		_c.SetCostCents(*v)
	}
	return _c
}

// SetStartedAt sets the "started_at" field.
func (_c *StageRunCreate) SetStartedAt(v time.Time) *StageRunCreate {
	_c.mutation.SetStartedAt(v)
	return _c
}

// SetNillableStartedAt sets the "started_at" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableStartedAt(v *time.Time) *StageRunCreate {
	if v != nil {
		_c.SetStartedAt(*v)
	}
	return _c
}

// SetEndedAt sets the "ended_at" field.
func (_c *StageRunCreate) SetEndedAt(v time.Time) *StageRunCreate {
	_c.mutation.SetEndedAt(v)
	return _c
}

// SetNillableEndedAt sets the "ended_at" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableEndedAt(v *time.Time) *StageRunCreate {
	if v != nil {
		_c.SetEndedAt(*v)
	}
	return _c
}

// SetLastGrantAt sets the "last_grant_at" field.
func (_c *StageRunCreate) SetLastGrantAt(v time.Time) *StageRunCreate {
	_c.mutation.SetLastGrantAt(v)
	return _c
}

// SetNillableLastGrantAt sets the "last_grant_at" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableLastGrantAt(v *time.Time) *StageRunCreate {
	if v != nil {
		_c.SetLastGrantAt(*v)
	}
	return _c
}

// SetRetryCount sets the "retry_count" field.
func (_c *StageRunCreate) SetRetryCount(v int) *StageRunCreate {
	_c.mutation.SetRetryCount(v)
	return _c
}

// SetNillableRetryCount sets the "retry_count" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableRetryCount(v *int) *StageRunCreate {
	if v != nil {
		_c.SetRetryCount(*v)
	}
	return _c
}

// SetNextRetryAt sets the "next_retry_at" field.
func (_c *StageRunCreate) SetNextRetryAt(v time.Time) *StageRunCreate {
	_c.mutation.SetNextRetryAt(v)
	return _c
}

// SetNillableNextRetryAt sets the "next_retry_at" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableNextRetryAt(v *time.Time) *StageRunCreate {
	if v != nil {
		_c.SetNextRetryAt(*v)
	}
	return _c
}

// SetPendingUserPrompt sets the "pending_user_prompt" field.
func (_c *StageRunCreate) SetPendingUserPrompt(v string) *StageRunCreate {
	_c.mutation.SetPendingUserPrompt(v)
	return _c
}

// SetNillablePendingUserPrompt sets the "pending_user_prompt" field if the given value is not nil.
func (_c *StageRunCreate) SetNillablePendingUserPrompt(v *string) *StageRunCreate {
	if v != nil {
		_c.SetPendingUserPrompt(*v)
	}
	return _c
}

// SetFailureCategory sets the "failure_category" field.
func (_c *StageRunCreate) SetFailureCategory(v string) *StageRunCreate {
	_c.mutation.SetFailureCategory(v)
	return _c
}

// SetNillableFailureCategory sets the "failure_category" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableFailureCategory(v *string) *StageRunCreate {
	if v != nil {
		_c.SetFailureCategory(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *StageRunCreate) SetCreatedAt(v time.Time) *StageRunCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *StageRunCreate) SetNillableCreatedAt(v *time.Time) *StageRunCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *StageRunCreate) SetID(v string) *StageRunCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetTask sets the "task" edge to the Task entity.
func (_c *StageRunCreate) SetTask(v *Task) *StageRunCreate {
	return _c.SetTaskID(v.ID)
}

// AddPermissionRequestIDs adds the "permission_requests" edge to the PermissionRequest entity by IDs.
func (_c *StageRunCreate) AddPermissionRequestIDs(ids ...string) *StageRunCreate {
	_c.mutation.AddPermissionRequestIDs(ids...)
	return _c
}

// AddPermissionRequests adds the "permission_requests" edges to the PermissionRequest entity.
func (_c *StageRunCreate) AddPermissionRequests(v ...*PermissionRequest) *StageRunCreate {
	ids := make([]string, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddPermissionRequestIDs(ids...)
}

// Mutation returns the StageRunMutation object of the builder.
func (_c *StageRunCreate) Mutation() *StageRunMutation {
	return _c.mutation
}

// Save creates the StageRun in the database.
func (_c *StageRunCreate) Save(ctx context.Context) (*StageRun, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *StageRunCreate) SaveX(ctx context.Context) *StageRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StageRunCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StageRunCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *StageRunCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := stagerun.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.Iteration(); !ok {
		v := stagerun.DefaultIteration
		_c.mutation.SetIteration(v)
	}
	if _, ok := _c.mutation.TokensUsed(); !ok {
		v := stagerun.DefaultTokensUsed
		_c.mutation.SetTokensUsed(v)
	}
	if _, ok := _c.mutation.CostCents(); !ok {
		v := stagerun.DefaultCostCents
		_c.mutation.SetCostCents(v)
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		v := stagerun.DefaultRetryCount
		_c.mutation.SetRetryCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := stagerun.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *StageRunCreate) check() error {
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "StageRun.task_id"`)}
	}
	if _, ok := _c.mutation.Stage(); !ok {
		return &ValidationError{Name: "stage", err: errors.New(`ent: missing required field "StageRun.stage"`)}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "StageRun.status"`)}
	}
	if _, ok := _c.mutation.Iteration(); !ok {
		return &ValidationError{Name: "iteration", err: errors.New(`ent: missing required field "StageRun.iteration"`)}
	}
	if _, ok := _c.mutation.TokensUsed(); !ok {
		return &ValidationError{Name: "tokens_used", err: errors.New(`ent: missing required field "StageRun.tokens_used"`)}
	}
	if _, ok := _c.mutation.CostCents(); !ok {
		return &ValidationError{Name: "cost_cents", err: errors.New(`ent: missing required field "StageRun.cost_cents"`)}
	}
	if _, ok := _c.mutation.RetryCount(); !ok {
		return &ValidationError{Name: "retry_count", err: errors.New(`ent: missing required field "StageRun.retry_count"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "StageRun.created_at"`)}
	}
	if len(_c.mutation.TaskIDs()) == 0 {
		return &ValidationError{Name: "task", err: errors.New(`ent: missing required edge "StageRun.task"`)}
	}
	return nil
}

func (_c *StageRunCreate) sqlSave(ctx context.Context) (*StageRun, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected StageRun.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *StageRunCreate) createSpec() (*StageRun, *sqlgraph.CreateSpec) {
	var (
		_node = &StageRun{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(stagerun.Table, sqlgraph.NewFieldSpec(stagerun.FieldID, field.TypeString))
	)
	_spec.OnConflict = _c.conflict
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Stage(); ok {
		_spec.SetField(stagerun.FieldStage, field.TypeString, value)
		_node.Stage = value
	}
	if value, ok := _c.mutation.SessionID(); ok {
		_spec.SetField(stagerun.FieldSessionID, field.TypeString, value)
		_node.SessionID = &value
	}
	if value, ok := _c.mutation.SessionName(); ok {
		_spec.SetField(stagerun.FieldSessionName, field.TypeString, value)
		_node.SessionName = &value
	}
	if value, ok := _c.mutation.Pid(); ok {
		_spec.SetField(stagerun.FieldPid, field.TypeInt, value)
		_node.Pid = &value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(stagerun.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.Iteration(); ok {
		_spec.SetField(stagerun.FieldIteration, field.TypeInt, value)
		_node.Iteration = value
	}
	if value, ok := _c.mutation.Output(); ok {
		_spec.SetField(stagerun.FieldOutput, field.TypeJSON, value)
		_node.Output = value
	}
	if value, ok := _c.mutation.TokensUsed(); ok {
		_spec.SetField(stagerun.FieldTokensUsed, field.TypeInt, value)
		_node.TokensUsed = value
	}
	if value, ok := _c.mutation.CostCents(); ok {
		_spec.SetField(stagerun.FieldCostCents, field.TypeInt, value)
		_node.CostCents = value
	}
	if value, ok := _c.mutation.StartedAt(); ok {
		_spec.SetField(stagerun.FieldStartedAt, field.TypeTime, value)
		_node.StartedAt = &value
	}
	if value, ok := _c.mutation.EndedAt(); ok {
		_spec.SetField(stagerun.FieldEndedAt, field.TypeTime, value)
		_node.EndedAt = &value
	}
	if value, ok := _c.mutation.LastGrantAt(); ok {
		_spec.SetField(stagerun.FieldLastGrantAt, field.TypeTime, value)
		_node.LastGrantAt = &value
	}
	if value, ok := _c.mutation.RetryCount(); ok {
		_spec.SetField(stagerun.FieldRetryCount, field.TypeInt, value)
		_node.RetryCount = value
	}
	if value, ok := _c.mutation.NextRetryAt(); ok {
		_spec.SetField(stagerun.FieldNextRetryAt, field.TypeTime, value)
		_node.NextRetryAt = &value
	}
	if value, ok := _c.mutation.PendingUserPrompt(); ok {
		_spec.SetField(stagerun.FieldPendingUserPrompt, field.TypeString, value)
		_node.PendingUserPrompt = &value
	}
	if value, ok := _c.mutation.FailureCategory(); ok {
		_spec.SetField(stagerun.FieldFailureCategory, field.TypeString, value)
		_node.FailureCategory = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(stagerun.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.TaskIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   stagerun.TaskTable,
			Columns: []string{stagerun.TaskColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(task.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.TaskID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.PermissionRequestsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   stagerun.PermissionRequestsTable,
			Columns: []string{stagerun.PermissionRequestsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(permissionrequest.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StageRun.Create().
//		SetTaskID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StageRunUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *StageRunCreate) OnConflict(opts ...sql.ConflictOption) *StageRunUpsertOne {
	_c.conflict = opts
	return &StageRunUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StageRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StageRunCreate) OnConflictColumns(columns ...string) *StageRunUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StageRunUpsertOne{
		create: _c,
	}
}

type (
	// StageRunUpsertOne is the builder for "upsert"-ing
	//  one StageRun node.
	StageRunUpsertOne struct {
		create *StageRunCreate
	}

	// StageRunUpsert is the "OnConflict" setter.
	StageRunUpsert struct {
		*sql.UpdateSet
	}
)

// SetStage sets the "stage" field.
func (u *StageRunUpsert) SetStage(v string) *StageRunUpsert {
	u.Set(stagerun.FieldStage, v)
	return u
}

// UpdateStage sets the "stage" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateStage() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldStage)
	return u
}

// SetSessionID sets the "session_id" field.
func (u *StageRunUpsert) SetSessionID(v string) *StageRunUpsert {
	u.Set(stagerun.FieldSessionID, v)
	return u
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateSessionID() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldSessionID)
	return u
}

// ClearSessionID clears the value of the "session_id" field.
func (u *StageRunUpsert) ClearSessionID() *StageRunUpsert {
	u.SetNull(stagerun.FieldSessionID)
	return u
}

// SetSessionName sets the "session_name" field.
func (u *StageRunUpsert) SetSessionName(v string) *StageRunUpsert {
	u.Set(stagerun.FieldSessionName, v)
	return u
}

// UpdateSessionName sets the "session_name" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateSessionName() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldSessionName)
	return u
}

// ClearSessionName clears the value of the "session_name" field.
func (u *StageRunUpsert) ClearSessionName() *StageRunUpsert {
	u.SetNull(stagerun.FieldSessionName)
	return u
}

// SetPid sets the "pid" field.
func (u *StageRunUpsert) SetPid(v int) *StageRunUpsert {
	u.Set(stagerun.FieldPid, v)
	return u
}

// UpdatePid sets the "pid" field to the value that was provided on create.
func (u *StageRunUpsert) UpdatePid() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldPid)
	return u
}

// AddPid adds v to the "pid" field.
func (u *StageRunUpsert) AddPid(v int) *StageRunUpsert {
	u.Add(stagerun.FieldPid, v)
	return u
}

// ClearPid clears the value of the "pid" field.
func (u *StageRunUpsert) ClearPid() *StageRunUpsert {
	u.SetNull(stagerun.FieldPid)
	return u
}

// SetStatus sets the "status" field.
func (u *StageRunUpsert) SetStatus(v string) *StageRunUpsert {
	u.Set(stagerun.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateStatus() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldStatus)
	return u
}

// SetIteration sets the "iteration" field.
func (u *StageRunUpsert) SetIteration(v int) *StageRunUpsert {
	u.Set(stagerun.FieldIteration, v)
	return u
}

// UpdateIteration sets the "iteration" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateIteration() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldIteration)
	return u
}

// AddIteration adds v to the "iteration" field.
func (u *StageRunUpsert) AddIteration(v int) *StageRunUpsert {
	u.Add(stagerun.FieldIteration, v)
	return u
}

// SetOutput sets the "output" field.
func (u *StageRunUpsert) SetOutput(v map[string]interface{}) *StageRunUpsert {
	u.Set(stagerun.FieldOutput, v)
	return u
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateOutput() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldOutput)
	return u
}

// ClearOutput clears the value of the "output" field.
func (u *StageRunUpsert) ClearOutput() *StageRunUpsert {
	u.SetNull(stagerun.FieldOutput)
	return u
}

// SetTokensUsed sets the "tokens_used" field.
func (u *StageRunUpsert) SetTokensUsed(v int) *StageRunUpsert {
	u.Set(stagerun.FieldTokensUsed, v)
	return u
}

// UpdateTokensUsed sets the "tokens_used" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateTokensUsed() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldTokensUsed)
	return u
}

// AddTokensUsed adds v to the "tokens_used" field.
func (u *StageRunUpsert) AddTokensUsed(v int) *StageRunUpsert {
	u.Add(stagerun.FieldTokensUsed, v)
	return u
}

// SetCostCents sets the "cost_cents" field.
func (u *StageRunUpsert) SetCostCents(v int) *StageRunUpsert {
	u.Set(stagerun.FieldCostCents, v)
	return u
}

// UpdateCostCents sets the "cost_cents" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateCostCents() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldCostCents)
	return u
}

// AddCostCents adds v to the "cost_cents" field.
func (u *StageRunUpsert) AddCostCents(v int) *StageRunUpsert {
	u.Add(stagerun.FieldCostCents, v)
	return u
}

// SetStartedAt sets the "started_at" field.
func (u *StageRunUpsert) SetStartedAt(v time.Time) *StageRunUpsert {
	u.Set(stagerun.FieldStartedAt, v)
	return u
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateStartedAt() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldStartedAt)
	return u
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *StageRunUpsert) ClearStartedAt() *StageRunUpsert {
	u.SetNull(stagerun.FieldStartedAt)
	return u
}

// SetEndedAt sets the "ended_at" field.
func (u *StageRunUpsert) SetEndedAt(v time.Time) *StageRunUpsert {
	u.Set(stagerun.FieldEndedAt, v)
	return u
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateEndedAt() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldEndedAt)
	return u
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *StageRunUpsert) ClearEndedAt() *StageRunUpsert {
	u.SetNull(stagerun.FieldEndedAt)
	return u
}

// SetLastGrantAt sets the "last_grant_at" field.
func (u *StageRunUpsert) SetLastGrantAt(v time.Time) *StageRunUpsert {
	u.Set(stagerun.FieldLastGrantAt, v)
	return u
}

// UpdateLastGrantAt sets the "last_grant_at" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateLastGrantAt() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldLastGrantAt)
	return u
}

// ClearLastGrantAt clears the value of the "last_grant_at" field.
func (u *StageRunUpsert) ClearLastGrantAt() *StageRunUpsert {
	u.SetNull(stagerun.FieldLastGrantAt)
	return u
}

// SetRetryCount sets the "retry_count" field.
func (u *StageRunUpsert) SetRetryCount(v int) *StageRunUpsert {
	u.Set(stagerun.FieldRetryCount, v)
	return u
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateRetryCount() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldRetryCount)
	return u
}

// AddRetryCount adds v to the "retry_count" field.
func (u *StageRunUpsert) AddRetryCount(v int) *StageRunUpsert {
	u.Add(stagerun.FieldRetryCount, v)
	return u
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *StageRunUpsert) SetNextRetryAt(v time.Time) *StageRunUpsert {
	u.Set(stagerun.FieldNextRetryAt, v)
	return u
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateNextRetryAt() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldNextRetryAt)
	return u
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *StageRunUpsert) ClearNextRetryAt() *StageRunUpsert {
	u.SetNull(stagerun.FieldNextRetryAt)
	return u
}

// SetPendingUserPrompt sets the "pending_user_prompt" field.
func (u *StageRunUpsert) SetPendingUserPrompt(v string) *StageRunUpsert {
	u.Set(stagerun.FieldPendingUserPrompt, v)
	return u
}

// UpdatePendingUserPrompt sets the "pending_user_prompt" field to the value that was provided on create.
func (u *StageRunUpsert) UpdatePendingUserPrompt() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldPendingUserPrompt)
	return u
}

// ClearPendingUserPrompt clears the value of the "pending_user_prompt" field.
func (u *StageRunUpsert) ClearPendingUserPrompt() *StageRunUpsert {
	u.SetNull(stagerun.FieldPendingUserPrompt)
	return u
}

// SetFailureCategory sets the "failure_category" field.
func (u *StageRunUpsert) SetFailureCategory(v string) *StageRunUpsert {
	u.Set(stagerun.FieldFailureCategory, v)
	return u
}

// UpdateFailureCategory sets the "failure_category" field to the value that was provided on create.
func (u *StageRunUpsert) UpdateFailureCategory() *StageRunUpsert {
	u.SetExcluded(stagerun.FieldFailureCategory)
	return u
}

// ClearFailureCategory clears the value of the "failure_category" field.
func (u *StageRunUpsert) ClearFailureCategory() *StageRunUpsert {
	u.SetNull(stagerun.FieldFailureCategory)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create except the ID field.
// Using this option is equivalent to using:
//
//	client.StageRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(stagerun.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StageRunUpsertOne) UpdateNewValues() *StageRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.ID(); exists {
			s.SetIgnore(stagerun.FieldID)
		}
		if _, exists := u.create.mutation.TaskID(); exists {
			s.SetIgnore(stagerun.FieldTaskID)
		}
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(stagerun.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StageRun.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *StageRunUpsertOne) Ignore() *StageRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StageRunUpsertOne) DoNothing() *StageRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StageRunCreate.OnConflict
// documentation for more info.
func (u *StageRunUpsertOne) Update(set func(*StageRunUpsert)) *StageRunUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StageRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetStage sets the "stage" field.
func (u *StageRunUpsertOne) SetStage(v string) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetStage(v)
	})
}

// UpdateStage sets the "stage" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateStage() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateStage()
	})
}

// SetSessionID sets the "session_id" field.
func (u *StageRunUpsertOne) SetSessionID(v string) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateSessionID() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *StageRunUpsertOne) ClearSessionID() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearSessionID()
	})
}

// SetSessionName sets the "session_name" field.
func (u *StageRunUpsertOne) SetSessionName(v string) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetSessionName(v)
	})
}

// UpdateSessionName sets the "session_name" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateSessionName() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateSessionName()
	})
}

// ClearSessionName clears the value of the "session_name" field.
func (u *StageRunUpsertOne) ClearSessionName() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearSessionName()
	})
}

// SetPid sets the "pid" field.
func (u *StageRunUpsertOne) SetPid(v int) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetPid(v)
	})
}

// AddPid adds v to the "pid" field.
func (u *StageRunUpsertOne) AddPid(v int) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.AddPid(v)
	})
}

// UpdatePid sets the "pid" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdatePid() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdatePid()
	})
}

// ClearPid clears the value of the "pid" field.
func (u *StageRunUpsertOne) ClearPid() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearPid()
	})
}

// SetStatus sets the "status" field.
func (u *StageRunUpsertOne) SetStatus(v string) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateStatus() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateStatus()
	})
}

// SetIteration sets the "iteration" field.
func (u *StageRunUpsertOne) SetIteration(v int) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetIteration(v)
	})
}

// AddIteration adds v to the "iteration" field.
func (u *StageRunUpsertOne) AddIteration(v int) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.AddIteration(v)
	})
}

// UpdateIteration sets the "iteration" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateIteration() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateIteration()
	})
}

// SetOutput sets the "output" field.
func (u *StageRunUpsertOne) SetOutput(v map[string]interface{}) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetOutput(v)
	})
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateOutput() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateOutput()
	})
}

// ClearOutput clears the value of the "output" field.
func (u *StageRunUpsertOne) ClearOutput() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearOutput()
	})
}

// SetTokensUsed sets the "tokens_used" field.
func (u *StageRunUpsertOne) SetTokensUsed(v int) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetTokensUsed(v)
	})
}

// AddTokensUsed adds v to the "tokens_used" field.
func (u *StageRunUpsertOne) AddTokensUsed(v int) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.AddTokensUsed(v)
	})
}

// UpdateTokensUsed sets the "tokens_used" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateTokensUsed() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateTokensUsed()
	})
}

// SetCostCents sets the "cost_cents" field.
func (u *StageRunUpsertOne) SetCostCents(v int) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetCostCents(v)
	})
}

// AddCostCents adds v to the "cost_cents" field.
func (u *StageRunUpsertOne) AddCostCents(v int) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.AddCostCents(v)
	})
}

// UpdateCostCents sets the "cost_cents" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateCostCents() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateCostCents()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *StageRunUpsertOne) SetStartedAt(v time.Time) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateStartedAt() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *StageRunUpsertOne) ClearStartedAt() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *StageRunUpsertOne) SetEndedAt(v time.Time) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateEndedAt() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *StageRunUpsertOne) ClearEndedAt() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearEndedAt()
	})
}

// SetLastGrantAt sets the "last_grant_at" field.
func (u *StageRunUpsertOne) SetLastGrantAt(v time.Time) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetLastGrantAt(v)
	})
}

// UpdateLastGrantAt sets the "last_grant_at" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateLastGrantAt() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateLastGrantAt()
	})
}

// ClearLastGrantAt clears the value of the "last_grant_at" field.
func (u *StageRunUpsertOne) ClearLastGrantAt() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearLastGrantAt()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *StageRunUpsertOne) SetRetryCount(v int) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *StageRunUpsertOne) AddRetryCount(v int) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateRetryCount() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateRetryCount()
	})
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *StageRunUpsertOne) SetNextRetryAt(v time.Time) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetNextRetryAt(v)
	})
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateNextRetryAt() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateNextRetryAt()
	})
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *StageRunUpsertOne) ClearNextRetryAt() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearNextRetryAt()
	})
}

// SetPendingUserPrompt sets the "pending_user_prompt" field.
func (u *StageRunUpsertOne) SetPendingUserPrompt(v string) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetPendingUserPrompt(v)
	})
}

// UpdatePendingUserPrompt sets the "pending_user_prompt" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdatePendingUserPrompt() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdatePendingUserPrompt()
	})
}

// ClearPendingUserPrompt clears the value of the "pending_user_prompt" field.
func (u *StageRunUpsertOne) ClearPendingUserPrompt() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearPendingUserPrompt()
	})
}

// SetFailureCategory sets the "failure_category" field.
func (u *StageRunUpsertOne) SetFailureCategory(v string) *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.SetFailureCategory(v)
	})
}

// UpdateFailureCategory sets the "failure_category" field to the value that was provided on create.
func (u *StageRunUpsertOne) UpdateFailureCategory() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateFailureCategory()
	})
}

// ClearFailureCategory clears the value of the "failure_category" field.
func (u *StageRunUpsertOne) ClearFailureCategory() *StageRunUpsertOne {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearFailureCategory()
	})
}

// Exec executes the query.
func (u *StageRunUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StageRunCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StageRunUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *StageRunUpsertOne) ID(ctx context.Context) (id string, err error) {
	if u.create.driver.Dialect() == dialect.MySQL {
		// In case of "ON CONFLICT", there is no way to get back non-numeric ID
		// fields from the database since MySQL does not support the RETURNING clause.
		return id, errors.New("ent: StageRunUpsertOne.ID is not supported by MySQL driver. Use StageRunUpsertOne.Exec instead")
	}
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *StageRunUpsertOne) IDX(ctx context.Context) string {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// StageRunCreateBulk is the builder for creating many StageRun entities in bulk.
type StageRunCreateBulk struct {
	config
	err      error
	builders []*StageRunCreate
	conflict []sql.ConflictOption
}

// Save creates the StageRun entities in the database.
func (_c *StageRunCreateBulk) Save(ctx context.Context) ([]*StageRun, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*StageRun, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*StageRunMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *StageRunCreateBulk) SaveX(ctx context.Context) []*StageRun {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *StageRunCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *StageRunCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.StageRun.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.StageRunUpsert) {
//			SetTaskID(v+v).
//		}).
//		Exec(ctx)
func (_c *StageRunCreateBulk) OnConflict(opts ...sql.ConflictOption) *StageRunUpsertBulk {
	_c.conflict = opts
	return &StageRunUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.StageRun.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *StageRunCreateBulk) OnConflictColumns(columns ...string) *StageRunUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &StageRunUpsertBulk{
		create: _c,
	}
}

// StageRunUpsertBulk is the builder for "upsert"-ing
// a bulk of StageRun nodes.
type StageRunUpsertBulk struct {
	create *StageRunCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.StageRun.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//			sql.ResolveWith(func(u *sql.UpdateSet) {
//				u.SetIgnore(stagerun.FieldID)
//			}),
//		).
//		Exec(ctx)
func (u *StageRunUpsertBulk) UpdateNewValues() *StageRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.ID(); exists {
				s.SetIgnore(stagerun.FieldID)
			}
			if _, exists := b.mutation.TaskID(); exists {
				s.SetIgnore(stagerun.FieldTaskID)
			}
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(stagerun.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.StageRun.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *StageRunUpsertBulk) Ignore() *StageRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *StageRunUpsertBulk) DoNothing() *StageRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the StageRunCreateBulk.OnConflict
// documentation for more info.
func (u *StageRunUpsertBulk) Update(set func(*StageRunUpsert)) *StageRunUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&StageRunUpsert{UpdateSet: update})
	}))
	return u
}

// SetStage sets the "stage" field.
func (u *StageRunUpsertBulk) SetStage(v string) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetStage(v)
	})
}

// UpdateStage sets the "stage" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateStage() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateStage()
	})
}

// SetSessionID sets the "session_id" field.
func (u *StageRunUpsertBulk) SetSessionID(v string) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetSessionID(v)
	})
}

// UpdateSessionID sets the "session_id" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateSessionID() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateSessionID()
	})
}

// ClearSessionID clears the value of the "session_id" field.
func (u *StageRunUpsertBulk) ClearSessionID() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearSessionID()
	})
}

// SetSessionName sets the "session_name" field.
func (u *StageRunUpsertBulk) SetSessionName(v string) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetSessionName(v)
	})
}

// UpdateSessionName sets the "session_name" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateSessionName() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateSessionName()
	})
}

// ClearSessionName clears the value of the "session_name" field.
func (u *StageRunUpsertBulk) ClearSessionName() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearSessionName()
	})
}

// SetPid sets the "pid" field.
func (u *StageRunUpsertBulk) SetPid(v int) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetPid(v)
	})
}

// AddPid adds v to the "pid" field.
func (u *StageRunUpsertBulk) AddPid(v int) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.AddPid(v)
	})
}

// UpdatePid sets the "pid" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdatePid() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdatePid()
	})
}

// ClearPid clears the value of the "pid" field.
func (u *StageRunUpsertBulk) ClearPid() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearPid()
	})
}

// SetStatus sets the "status" field.
func (u *StageRunUpsertBulk) SetStatus(v string) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateStatus() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateStatus()
	})
}

// SetIteration sets the "iteration" field.
func (u *StageRunUpsertBulk) SetIteration(v int) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetIteration(v)
	})
}

// AddIteration adds v to the "iteration" field.
func (u *StageRunUpsertBulk) AddIteration(v int) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.AddIteration(v)
	})
}

// UpdateIteration sets the "iteration" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateIteration() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateIteration()
	})
}

// SetOutput sets the "output" field.
func (u *StageRunUpsertBulk) SetOutput(v map[string]interface{}) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetOutput(v)
	})
}

// UpdateOutput sets the "output" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateOutput() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateOutput()
	})
}

// ClearOutput clears the value of the "output" field.
func (u *StageRunUpsertBulk) ClearOutput() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearOutput()
	})
}

// SetTokensUsed sets the "tokens_used" field.
func (u *StageRunUpsertBulk) SetTokensUsed(v int) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetTokensUsed(v)
	})
}

// AddTokensUsed adds v to the "tokens_used" field.
func (u *StageRunUpsertBulk) AddTokensUsed(v int) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.AddTokensUsed(v)
	})
}

// UpdateTokensUsed sets the "tokens_used" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateTokensUsed() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateTokensUsed()
	})
}

// SetCostCents sets the "cost_cents" field.
func (u *StageRunUpsertBulk) SetCostCents(v int) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetCostCents(v)
	})
}

// AddCostCents adds v to the "cost_cents" field.
func (u *StageRunUpsertBulk) AddCostCents(v int) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.AddCostCents(v)
	})
}

// UpdateCostCents sets the "cost_cents" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateCostCents() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateCostCents()
	})
}

// SetStartedAt sets the "started_at" field.
func (u *StageRunUpsertBulk) SetStartedAt(v time.Time) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetStartedAt(v)
	})
}

// UpdateStartedAt sets the "started_at" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateStartedAt() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateStartedAt()
	})
}

// ClearStartedAt clears the value of the "started_at" field.
func (u *StageRunUpsertBulk) ClearStartedAt() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearStartedAt()
	})
}

// SetEndedAt sets the "ended_at" field.
func (u *StageRunUpsertBulk) SetEndedAt(v time.Time) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetEndedAt(v)
	})
}

// UpdateEndedAt sets the "ended_at" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateEndedAt() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateEndedAt()
	})
}

// ClearEndedAt clears the value of the "ended_at" field.
func (u *StageRunUpsertBulk) ClearEndedAt() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearEndedAt()
	})
}

// SetLastGrantAt sets the "last_grant_at" field.
func (u *StageRunUpsertBulk) SetLastGrantAt(v time.Time) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetLastGrantAt(v)
	})
}

// UpdateLastGrantAt sets the "last_grant_at" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateLastGrantAt() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateLastGrantAt()
	})
}

// ClearLastGrantAt clears the value of the "last_grant_at" field.
func (u *StageRunUpsertBulk) ClearLastGrantAt() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearLastGrantAt()
	})
}

// SetRetryCount sets the "retry_count" field.
func (u *StageRunUpsertBulk) SetRetryCount(v int) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetRetryCount(v)
	})
}

// AddRetryCount adds v to the "retry_count" field.
func (u *StageRunUpsertBulk) AddRetryCount(v int) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.AddRetryCount(v)
	})
}

// UpdateRetryCount sets the "retry_count" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateRetryCount() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateRetryCount()
	})
}

// SetNextRetryAt sets the "next_retry_at" field.
func (u *StageRunUpsertBulk) SetNextRetryAt(v time.Time) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetNextRetryAt(v)
	})
}

// UpdateNextRetryAt sets the "next_retry_at" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateNextRetryAt() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateNextRetryAt()
	})
}

// ClearNextRetryAt clears the value of the "next_retry_at" field.
func (u *StageRunUpsertBulk) ClearNextRetryAt() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearNextRetryAt()
	})
}

// SetPendingUserPrompt sets the "pending_user_prompt" field.
func (u *StageRunUpsertBulk) SetPendingUserPrompt(v string) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetPendingUserPrompt(v)
	})
}

// UpdatePendingUserPrompt sets the "pending_user_prompt" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdatePendingUserPrompt() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdatePendingUserPrompt()
	})
}

// ClearPendingUserPrompt clears the value of the "pending_user_prompt" field.
func (u *StageRunUpsertBulk) ClearPendingUserPrompt() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearPendingUserPrompt()
	})
}

// SetFailureCategory sets the "failure_category" field.
func (u *StageRunUpsertBulk) SetFailureCategory(v string) *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.SetFailureCategory(v)
	})
}

// UpdateFailureCategory sets the "failure_category" field to the value that was provided on create.
func (u *StageRunUpsertBulk) UpdateFailureCategory() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.UpdateFailureCategory()
	})
}

// ClearFailureCategory clears the value of the "failure_category" field.
func (u *StageRunUpsertBulk) ClearFailureCategory() *StageRunUpsertBulk {
	return u.Update(func(s *StageRunUpsert) {
		s.ClearFailureCategory()
	})
}

// Exec executes the query.
func (u *StageRunUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the StageRunCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for StageRunCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *StageRunUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
