// Code generated by tygo. DO NOT EDIT.

//////////
// source: types.go
/*
Package sdk provides shared types for the agent-dashboard modules.
*/

/**
 * TokenUsage mirrors the Claude Code session token counters.
 */
export interface TokenUsage {
  inputTokens: number
  outputTokens: number
  cacheCreationTokens: number
  cacheReadTokens: number
}
/**
 * SessionMeta is read from ~/.claude/usage-data/session-meta/{sessionId}.json
 */
export interface SessionMeta {
  inputTokens: number
  outputTokens: number
  linesAdded: number
  linesRemoved: number
  filesModified: number
  gitCommits: number
  toolErrors: number
  usesMcp: boolean
  firstPrompt: string
}
/**
 * SubAgentStatus is the lifecycle state of a spawned sub-agent.
 */
export const SubAgentStatusActive = 'active'
export const SubAgentStatusCompleted = 'completed'
export type SubAgentStatus = typeof SubAgentStatusActive | typeof SubAgentStatusCompleted
/**
 * SubAgent represents a sub-agent spawned by a parent Claude session.
 */
export interface SubAgent {
  id: string
  type: string
  status: SubAgentStatus
  currentAction: string
  sessionFile: string
  tokensUsed: number
  durationSeconds: number
  latestOutput: string
}
/**
 * TaskInfoStatus is the state of a TodoWrite-tracked task.
 */
export const TaskInfoStatusPending = 'pending'
export const TaskInfoStatusInProgress = 'in_progress'
export const TaskInfoStatusCompleted = 'completed'
export type TaskInfoStatus = typeof TaskInfoStatusPending | typeof TaskInfoStatusInProgress | typeof TaskInfoStatusCompleted
/**
 * TaskInfo is a task tracked by Claude Code's internal task list.
 */
export interface TaskInfo {
  id: string
  subject: string
  status: TaskInfoStatus
}
/**
 * AgentStatus is the computed activity state of an agent process.
 */
export const AgentStatusActive = 'active'
export const AgentStatusWaiting = 'waiting'
export const AgentStatusIdle = 'idle'
export const AgentStatusFinished = 'finished'
export type AgentStatus = typeof AgentStatusActive | typeof AgentStatusWaiting | typeof AgentStatusIdle | typeof AgentStatusFinished
/**
 * Entrypoint describes how the Claude Code process was launched.
 */
export const EntrypointCLI = 'cli'
export const EntrypointDesktop = 'desktop'
export const EntrypointUnknown = 'unknown'
export type Entrypoint = typeof EntrypointCLI | typeof EntrypointDesktop | typeof EntrypointUnknown
/**
 * Provider identifies which AI coding CLI an agent process belongs to.
 */
export const ProviderClaude = 'claude'
export const ProviderCodex = 'codex'
export const ProviderGemini = 'gemini'
export const ProviderJunie = 'junie'
export type Provider = typeof ProviderClaude | typeof ProviderCodex | typeof ProviderGemini | typeof ProviderJunie
/**
 * ErrorState describes a recognisable error condition seen in the session log.
 */
export const ErrorStateQuotaExhausted = 'quota_exhausted'
export const ErrorStateRateLimited = 'rate_limited'
export const ErrorStateAuthFailed = 'auth_failed'
export type ErrorState = typeof ErrorStateQuotaExhausted | typeof ErrorStateRateLimited | typeof ErrorStateAuthFailed
/**
 * SankeyNode is one node in the tool-call Sankey diagram. ID equals Name
 * today but is kept separate so collisions across distinct sources can
 * later be disambiguated.
 */
export interface SankeyNode {
  id: string
  name: string
}
/**
 * SankeyLink is one directed source→target flow with an aggregated count.
 */
export interface SankeyLink {
  source: string
  target: string
  value: number
}
/**
 * SankeyMeta carries summary counters for the Sankey response.
 */
export interface SankeyMeta {
  sessionCount: number
  callCount: number
}
/**
 * SankeyData is the response payload for GET /api/visualizations/sankey.
 */
export interface SankeyData {
  nodes: SankeyNode[]
  links: SankeyLink[]
  meta: SankeyMeta
}
/**
 * DAGNode is one node in the session DAG (tool call, assistant turn, or
 * user message). The DAG is per-session so IDs are line-local.
 */
export interface DAGNode {
  id: string
  type: string // "tool" | "assistant" | "user"
  label: string
  ts: string // RFC3339 timestamp, empty if absent
}
/**
 * DAGLink is one edge in the session DAG. Kind is "chrono" for time-
 * ordered succession or "result" for a tool_use → tool_result match.
 */
export interface DAGLink {
  source: string
  target: string
  kind: string
}
/**
 * DAGData is the response payload for GET /api/visualizations/dag.
 */
export interface DAGData {
  nodes: DAGNode[]
  links: DAGLink[]
}
/**
 * SpawnTreeNode is one session node in the spawn tree. Depth is computed
 * from the root via BFS. ToolCount and CostCents reflect the session,
 * not the cumulative subtree.
 */
export interface SpawnTreeNode {
  id: string
  label: string
  depth: number
  toolCount: number
  costCents: number
  project: string
  model: string
  firstPrompt: string
}
/**
 * SpawnTreeLink is a parent→child spawn relationship.
 */
export interface SpawnTreeLink {
  source: string
  target: string
}
/**
 * SpawnTreeData is the response payload for GET /api/visualizations/spawn-tree.
 */
export interface SpawnTreeData {
  roots: string[]
  nodes: SpawnTreeNode[]
  links: SpawnTreeLink[]
}
/**
 * CoOccurrenceMeta carries summary counters for the co-occurrence response.
 */
export interface CoOccurrenceMeta {
  sessionCount: number
  truncated: boolean
}
/**
 * CoOccurrenceData is the response payload for
 * GET /api/visualizations/co-occurrence. Matrix is square with side equal
 * to len(Tools); Matrix[i][j] = sessions containing both Tools[i] and
 * Tools[j] (diagonal = sessions containing the tool at all).
 * Lift is the same-dimension normalized lift score: Lift[i][j] =
 * (Matrix[i][j] × N) / (Matrix[i][i] × Matrix[j][j]), where N is the
 * total session count. Diagonal is 0 (self-lift is meaningless).
 */
export interface CoOccurrenceData {
  tools: string[]
  matrix: number /* int */[][]
  lift: number /* float64 */[][]
  meta: CoOccurrenceMeta
}
/**
 * BtwMessage is the last assistant text that appeared alongside tool calls.
 * Message is the text content; Response is reserved for future use.
 */
export interface BtwMessage {
  message: string
  response?: string
}
/**
 * WorktreeStatusDTO describes the live git state of a task's worktree.
 * Ahead and Behind are pointers so JSON null is preserved when the base
 * branch cannot be resolved on `origin` (e.g. local-only base).
 */
export interface WorktreeStatusDTO {
  branch: string
  ahead?: number
  behind?: number
  dirty: boolean
  fileCount: number
}
/**
 * PendingPermission is a permission request an orchestrated agent is currently
 * blocked on, surfaced on the agent so it can be resolved from the roster.
 */
export interface PendingPermission {
  id: string
  tool: string
  pattern?: string
  /**
   * PatternElided carries Pattern's cut count as its own field, mirroring
   * RecentTool.Elided, so a truncated Pattern cannot forge its own "…" next
   * to the Allow button.
   */
  patternElided?: number
  /**
   * DeniedBy is the user's own permissions.deny rule forbidding this call,
   * verbatim, or nil when no rule covers it. A hook "allow" short-circuits
   * Claude Code's own evaluation, so a dashboard approval would otherwise
   * release a restriction the user believes is absolute. The client offers no
   * Allow when this is set; the server refuses one regardless.
   */
  deniedBy?: string
  /**
   * DeniedByElided mirrors PatternElided, for DeniedBy.
   */
  deniedByElided?: number
  reason?: string
  requestedAt: string
}
/**
 * PendingCapabilityDecision is a capability decision waiting for a human at a
 * server enforcement point; unlike PendingPermission it names a capability
 * and scope, not a tool, and belongs to no Claude Code session.
 */
export interface PendingCapabilityDecision {
  id: string
  capability: string
  value: string
  /**
   * ValueElided/ContextElided carry the cut count as their own field, mirroring
   * RecentTool.Elided, so a truncated Value/Context cannot forge its own "…".
   */
  valueElided?: number
  context: string
  contextElided?: number
  reason: string
  requestedAt: string
}
/**
 * RecentTool is one entry of the recent-tool trail. Detail is the tool's own
 * human-readable argument -- a Bash command, an Edit/Write path -- and is
 * agent-authored text on its way to a UI: never interpolate it into a shell
 * command, a query or HTML without escaping at the point of use.
 * Elided is how many characters Detail was cut by, 0 when it was not cut. It is
 * a separate field rather than a suffix inside Detail so the payload cannot
 * forge a cut that never happened: the client renders it as its own element.
 */
export interface RecentTool {
  name: string
  detail?: string
  elided?: number
}
/**
 * PendingToolUse is the last assistant tool_use block that has no matching
 * tool_result yet. It indicates the agent is currently executing or blocked on
 * that tool call.
 * Pattern is the command string (Bash), file path (Edit/Write), or empty for
 * other tools. It is the grant identity: a permission preset is matched by
 * exact equality, so it is carried verbatim and must never be normalised.
 * PatternDisplay is the same value made safe to render -- deceptive runes
 * removed, whitespace collapsed, never truncated. Show PatternDisplay to a
 * human; send Pattern to the permission API.
 */
export interface PendingToolUse {
  id: string
  tool: string
  pattern: string
  patternDisplay: string
}
/**
 * HookEvent is one lifecycle-hook event recorded for a session when the opt-in
 * hook receiver is installed (POST /api/hooks/event). It adds per-event
 * granularity on top of the process/JSONL scan. Tool and Summary are truncated,
 * secret-safe projections of the raw hook payload — never the full tool_input or
 * tool_response.
 */
export interface HookEvent {
  type: string // hook type, e.g. "PreToolUse" | "PostToolUse" | "Stop"
  tool: string // tool name, empty for non-tool hooks
  at: string // RFC3339 timestamp the event was received
  summary: string // truncated, secret-safe payload preview
}
/**
 * DetectedOption is a single numbered option row of a parsed AskUserQuestion
 * modal.
 */
export interface DetectedOption {
  index: number
  label: string
  description?: string
}
/**
 * DetectedQuestion is a parsed AskUserQuestion modal, detected from a live
 * terminal's rendered rows by askq.DetectQuestion.
 * Invariant (ENFORCED, not merely typical): the real option rows are numbered
 * contiguously 1..n, and the two UI-injected meta-rows follow immediately, so
 * TypeSomethingIndex == len(Options)+1 and ChatAboutIndex == TypeSomethingIndex+1.
 */
export interface DetectedQuestion {
  /**
   * Header is a best-effort title line above the question. Bordered renders
   * carry a real one; borderless renders leave whatever scrolled above the
   * modal here (a prompt echo, the welcome box). Not UI-facing.
   */
  header: string
  question: string
  multiSelect: boolean
  options: DetectedOption[]
  typeSomethingIndex: number
  chatAboutIndex: number
}
/**
 * DetectedConfirm is the AskUserQuestion review/submit screen, detected from a
 * live terminal's rendered rows by askq.DetectConfirmScreen.
 * It is the screen a multi-question AskUserQuestion flow lands on after the
 * last question has been answered ("Ready to submit your answers?" plus a
 * Submit/Cancel choice). It carries no meta-rows, so it is not a
 * DetectedQuestion: there is nothing to type and nothing to chat about, only
 * two numbered options to pick from.
 */
export interface DetectedConfirm {
  question: string
  options: DetectedOption[]
}
/**
 * PendingScreen is whichever interactive AskUserQuestion screen is currently
 * open on a session's terminal. At most one field is non-nil; both are nil when
 * no such screen is open. Probing for both in one round-trip keeps the scan hot
 * path to a single capture per tick.
 */
export interface PendingScreen {
  question?: DetectedQuestion
  confirm?: DetectedConfirm
}
export const SpawnerSourceTask = 'task'
export const SpawnerSourceEnv = 'env'
/**
 * How an agent's spawner attribution was established: recorded from the pipeline
 * task the agent runs, or read back from the live process, which is how sessions
 * started outside the dashboard are placed.
 * These are untyped consts, so tygo emits no counterpart; the client mirrors
 * them by hand in src/types.ts (SPAWNER_SOURCE_TASK / SPAWNER_SOURCE_ENV).
 * Changing a value here means changing it there.
 */
export type SpawnerSource = typeof SpawnerSourceTask | typeof SpawnerSourceEnv
/**
 * RepositoryRef identifies one local git object store.
 */
export interface RepositoryRef {
  /**
   * ID is opaque and stable: two workspaces share it exactly when they share
   * a repository. Derived in server/internal/identity; see that package for
   * what it is and, explicitly, what it is not.
   */
  id: string
  /**
   * Name is the primary working tree's directory name, for display only.
   * Empty for a bare repository or a submodule, whose object store has no
   * working-tree parent. Never an identity — two clones share this string.
   */
  name: string
}
/**
 * WorkspaceKind is what a workspace is, which decides how it relates to others.
 */
/**
 * WorkspaceKindGitMain is a repository's primary working tree.
 */
export const WorkspaceKindGitMain = 'git-main'
/**
 * WorkspaceKindGitWorktree is a linked worktree: same repository, different
 * workspace.
 */
export const WorkspaceKindGitWorktree = 'git-worktree'
/**
 * WorkspaceKindPlain is a directory in no repository. Still a workspace —
 * agents run in such directories — but it has no Repository, and two of
 * them are never "the same project".
 */
export const WorkspaceKindPlain = 'plain'
export type WorkspaceKind = typeof WorkspaceKindGitMain | typeof WorkspaceKindGitWorktree | typeof WorkspaceKindPlain
/**
 * WorkspaceRef identifies one active checkout.
 */
export interface WorkspaceRef {
  /**
   * ID is opaque and stable. Two worktrees of one repository have different
   * IDs; the same checkout always has the same one.
   */
  id: string
  /**
   * Name is the workspace root's directory name, for display only.
   */
  name: string
  kind: WorkspaceKind
  /**
   * Branch is the checked-out branch, omitted when detached or unknown.
   */
  branch?: string
  /**
   * Detached distinguishes a detached HEAD — normal for a worktree opened on
   * a commit — from a branch that simply could not be read.
   */
  detached?: boolean
  /**
   * Repository is null exactly when Kind is plain.
   */
  repository?: RepositoryRef
}
/**
 * Agent is the unified view of a running Claude Code process.
 */
export interface Agent {
  pid: number
  sessionId: string
  provider: Provider
  projectPath: string
  projectName: string
  cwd: string
  /**
   * Workspace is the checkout this agent is running in, resolved from CWD by
   * server/internal/identity. Null when it could not be resolved — no cwd, a
   * deleted directory, git unavailable, or the resolver budget expiring.
   * Null means "not known" and never "no workspace": a caller must render it
   * as unknown rather than fall back to ProjectName, which is basename(cwd)
   * and collides across unrelated checkouts. Additive and read-only; it
   * replaces no existing field in this phase.
   */
  workspace?: WorkspaceRef
  /**
   * ClaudeConfigDir is the value of CLAUDE_CONFIG_DIR detected in the running
   * session's process env (empty when the session uses the default ~/.claude).
   * Lets the dashboard resolve which config root a session's slash commands /
   * skills / plugins are loaded from when enumerating per-session scope.
   */
  claudeConfigDir?: string
  entrypoint: Entrypoint
  status: AgentStatus
  uptime: number
  lastActivity: string
  currentAction?: string
  lastTools: RecentTool[]
  tasks: TaskInfo[]
  subagents: SubAgent[]
  tokenUsage: TokenUsage
  costEstimate: number
  cacheCreationCostEstimate: number
  cacheReadCostEstimate: number
  healthScore: number
  model?: string
  codeVersion?: string
  conversationTurns: number
  toolCounts: { [key: string]: number /* int */ }
  meta?: SessionMeta
  channelAvailable: boolean
  /**
   * Working is true when the agent is actively generating: it owes the next
   * step (open turn — a trailing user message or unmatched tool_use, via
   * parser.SessionData.TurnOpen) OR a live session emitted output within the
   * last few seconds (pty lastOutputAt / tmux window_activity).
   */
  working: boolean
  /**
   * PermissionsBypassed is true when the process runs with
   * --dangerously-skip-permissions or --permission-mode bypassPermissions, so it
   * never stops for a tool-permission prompt. An unresolved tool_use in such a
   * session means the tool is running, not that someone has to approve it.
   */
  permissionsBypassed: boolean
  /**
   * LiveInjectable is true when the dashboard can deliver a prompt to this
   * running interactive session as real keyboard input — either via the pty
   * broker (`agent-dashboard ptyhost`) or `tmux send-keys`. When false, sending
   * resumes the session as a new one (MCP log delivery does not drive it).
   */
  liveInjectable?: boolean
  /**
   * InternalProcess is true when this is Claude Code's own internal
   * daemon/spare-pool machinery (a grandchild of a real session, matched by
   * scanner.IsInternalProcess), not a session the user can address —
   * LiveInjectable is meaningless for it and no prompt can be sent to it.
   */
  internalProcess?: boolean
  /**
   * PendingQuestion is the AskUserQuestion modal currently detected on this
   * session's live terminal (render-sourced, via the pty broker's /question
   * endpoint or a tmux capture-pane snapshot), or nil when no modal is open.
   * Only ever set on injectable sessions.
   */
  pendingQuestion?: DetectedQuestion
  /**
   * PendingConfirm is the AskUserQuestion review/submit screen currently
   * detected on this session's live terminal, or nil. Mutually exclusive with
   * PendingQuestion: the TUI shows one or the other, never both. Only ever set
   * on injectable sessions.
   */
  pendingConfirm?: DetectedConfirm
  lastOutput?: string
  convergenceAlert: boolean
  convergenceToolName?: string
  errorState?: ErrorState
  pipelineTaskId?: string
  pipelineTaskTitle?: string
  /**
   * SpawnerID/SpawnerName name the configured spawner this session belongs to,
   * and SpawnerSource says how that was established (see SpawnerSource*).
   * Empty when no spawner could be attributed.
   */
  spawnerId?: string
  spawnerName?: string
  spawnerSource?: string
  /**
   * PendingPermissions are the approval requests this session is blocked on and
   * that can be answered from the dashboard: either a pipeline stage run's
   * stored requests, or a PreToolUse hook call the permission bridge is holding
   * open. Both are answerable; the client tells them apart by PipelineTaskID.
   */
  pendingPermissions?: PendingPermission[]
  /**
   * HeldPermissions are PreToolUse hook calls the permission bridge is holding
   * open for this session, in arrival order. Deliberately NOT merged into
   * PendingPermissions: those are database-backed pipeline stage-run rows that
   * resolve through a different endpoint, and sharing one slice let a hook id
   * ride along in the pipeline's bulk-resolve payload.
   */
  heldPermissions?: PendingPermission[]
  /**
   * PermissionBridgeArmed means the dashboard intercepts this session's
   * permission prompts. Off by default: PreToolUse fires before Claude Code
   * decides whether to prompt at all, so holding every call would stall every
   * session. A session is intercepted only after someone asked for it.
   */
  permissionBridgeArmed?: boolean
  /**
   * AwaitingTerminalPermission means the session is showing its own permission
   * prompt, which the dashboard can report but not answer -- the bridge either
   * lapsed before anyone decided, or the session is not armed. Set from the
   * Notification hook's typed notification_type, never from its prose.
   */
  awaitingTerminalPermission?: boolean
  /**
   * TerminalPermissionToolUseID names the tool call that terminal prompt is
   * about, when the bridge held that call and the hold lapsed. Empty for a
   * session the bridge never held, because the Notification payload carries no
   * tool id of its own. Without it a standing grant can only be offered for
   * PendingToolUse below, which is derived independently from the transcript
   * and can name a different call entirely -- so a notice that outlives its
   * prompt would put a grant button next to a tool nobody asked about.
   */
  terminalPermissionToolUseId?: string
  pendingToolUse?: PendingToolUse
  machine?: string
  lastBtw?: BtwMessage
  /**
   * CostUnknown is true when the provider does not expose token counts and
   * cost cannot be estimated. CostEstimate will be 0 in this case.
   */
  costUnknown?: boolean
  /**
   * CostLocal is true when the session runs a locally-served (Ollama) model,
   * whose cost is $0 rather than unknown. CostEstimate is 0 in this case.
   */
  costLocal?: boolean
  /**
   * RecentHookEvents carries per-event hook granularity for sessions where the
   * opt-in hook receiver holds events. Omitted entirely when no hook is
   * installed, so clients without hooks receive byte-identical payloads.
   */
  recentHookEvents?: HookEvent[]
}
