// Code generated by ent, DO NOT EDIT.

package managedagent

import (
	"time"

	"entgo.io/ent/dialect/sql"
)

const (
	// Label holds the string label denoting the managedagent type in the database.
	Label = "managed_agent"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "session_id"
	// FieldPid holds the string denoting the pid field in the database.
	FieldPid = "pid"
	// FieldCwd holds the string denoting the cwd field in the database.
	FieldCwd = "cwd"
	// FieldWorkspaceCreated holds the string denoting the workspace_created field in the database.
	FieldWorkspaceCreated = "workspace_created"
	// FieldAllowedFolder holds the string denoting the allowed_folder field in the database.
	FieldAllowedFolder = "allowed_folder"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// Table holds the table name of the managedagent in the database.
	Table = "managed_agents"
)

// Columns holds all SQL columns for managedagent fields.
var Columns = []string{
	FieldID,
	FieldPid,
	FieldCwd,
	FieldWorkspaceCreated,
	FieldAllowedFolder,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// PidValidator is a validator for the "pid" field. It is called by the builders before save.
	PidValidator func(int) error
	// DefaultCwd holds the default value on creation for the "cwd" field.
	DefaultCwd string
	// DefaultWorkspaceCreated holds the default value on creation for the "workspace_created" field.
	DefaultWorkspaceCreated bool
	// DefaultAllowedFolder holds the default value on creation for the "allowed_folder" field.
	DefaultAllowedFolder string
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// IDValidator is a validator for the "id" field. It is called by the builders before save.
	IDValidator func(string) error
)

// OrderOption defines the ordering options for the ManagedAgent queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByPid orders the results by the pid field.
func ByPid(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPid, opts...).ToFunc()
}

// ByCwd orders the results by the cwd field.
func ByCwd(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCwd, opts...).ToFunc()
}

// ByWorkspaceCreated orders the results by the workspace_created field.
func ByWorkspaceCreated(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWorkspaceCreated, opts...).ToFunc()
}

// ByAllowedFolder orders the results by the allowed_folder field.
func ByAllowedFolder(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAllowedFolder, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}
