// Code generated by ent, DO NOT EDIT.

package managedagent

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldContainsFold(FieldID, id))
}

// Pid applies equality check predicate on the "pid" field. It's identical to PidEQ.
func Pid(v int) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldPid, v))
}

// Cwd applies equality check predicate on the "cwd" field. It's identical to CwdEQ.
func Cwd(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldCwd, v))
}

// WorkspaceCreated applies equality check predicate on the "workspace_created" field. It's identical to WorkspaceCreatedEQ.
func WorkspaceCreated(v bool) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldWorkspaceCreated, v))
}

// AllowedFolder applies equality check predicate on the "allowed_folder" field. It's identical to AllowedFolderEQ.
func AllowedFolder(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldAllowedFolder, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldUpdatedAt, v))
}

// PidEQ applies the EQ predicate on the "pid" field.
func PidEQ(v int) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldPid, v))
}

// PidNEQ applies the NEQ predicate on the "pid" field.
func PidNEQ(v int) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNEQ(FieldPid, v))
}

// PidIn applies the In predicate on the "pid" field.
func PidIn(vs ...int) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldIn(FieldPid, vs...))
}

// PidNotIn applies the NotIn predicate on the "pid" field.
func PidNotIn(vs ...int) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNotIn(FieldPid, vs...))
}

// PidGT applies the GT predicate on the "pid" field.
func PidGT(v int) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGT(FieldPid, v))
}

// PidGTE applies the GTE predicate on the "pid" field.
func PidGTE(v int) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGTE(FieldPid, v))
}

// PidLT applies the LT predicate on the "pid" field.
func PidLT(v int) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLT(FieldPid, v))
}

// PidLTE applies the LTE predicate on the "pid" field.
func PidLTE(v int) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLTE(FieldPid, v))
}

// CwdEQ applies the EQ predicate on the "cwd" field.
func CwdEQ(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldCwd, v))
}

// CwdNEQ applies the NEQ predicate on the "cwd" field.
func CwdNEQ(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNEQ(FieldCwd, v))
}

// CwdIn applies the In predicate on the "cwd" field.
func CwdIn(vs ...string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldIn(FieldCwd, vs...))
}

// CwdNotIn applies the NotIn predicate on the "cwd" field.
func CwdNotIn(vs ...string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNotIn(FieldCwd, vs...))
}

// CwdGT applies the GT predicate on the "cwd" field.
func CwdGT(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGT(FieldCwd, v))
}

// CwdGTE applies the GTE predicate on the "cwd" field.
func CwdGTE(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGTE(FieldCwd, v))
}

// CwdLT applies the LT predicate on the "cwd" field.
func CwdLT(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLT(FieldCwd, v))
}

// CwdLTE applies the LTE predicate on the "cwd" field.
func CwdLTE(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLTE(FieldCwd, v))
}

// CwdContains applies the Contains predicate on the "cwd" field.
func CwdContains(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldContains(FieldCwd, v))
}

// CwdHasPrefix applies the HasPrefix predicate on the "cwd" field.
func CwdHasPrefix(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldHasPrefix(FieldCwd, v))
}

// CwdHasSuffix applies the HasSuffix predicate on the "cwd" field.
func CwdHasSuffix(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldHasSuffix(FieldCwd, v))
}

// CwdEqualFold applies the EqualFold predicate on the "cwd" field.
func CwdEqualFold(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEqualFold(FieldCwd, v))
}

// CwdContainsFold applies the ContainsFold predicate on the "cwd" field.
func CwdContainsFold(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldContainsFold(FieldCwd, v))
}

// WorkspaceCreatedEQ applies the EQ predicate on the "workspace_created" field.
func WorkspaceCreatedEQ(v bool) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldWorkspaceCreated, v))
}

// WorkspaceCreatedNEQ applies the NEQ predicate on the "workspace_created" field.
func WorkspaceCreatedNEQ(v bool) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNEQ(FieldWorkspaceCreated, v))
}

// AllowedFolderEQ applies the EQ predicate on the "allowed_folder" field.
func AllowedFolderEQ(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldAllowedFolder, v))
}

// AllowedFolderNEQ applies the NEQ predicate on the "allowed_folder" field.
func AllowedFolderNEQ(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNEQ(FieldAllowedFolder, v))
}

// AllowedFolderIn applies the In predicate on the "allowed_folder" field.
func AllowedFolderIn(vs ...string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldIn(FieldAllowedFolder, vs...))
}

// AllowedFolderNotIn applies the NotIn predicate on the "allowed_folder" field.
func AllowedFolderNotIn(vs ...string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNotIn(FieldAllowedFolder, vs...))
}

// AllowedFolderGT applies the GT predicate on the "allowed_folder" field.
func AllowedFolderGT(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGT(FieldAllowedFolder, v))
}

// AllowedFolderGTE applies the GTE predicate on the "allowed_folder" field.
func AllowedFolderGTE(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGTE(FieldAllowedFolder, v))
}

// AllowedFolderLT applies the LT predicate on the "allowed_folder" field.
func AllowedFolderLT(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLT(FieldAllowedFolder, v))
}

// AllowedFolderLTE applies the LTE predicate on the "allowed_folder" field.
func AllowedFolderLTE(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLTE(FieldAllowedFolder, v))
}

// AllowedFolderContains applies the Contains predicate on the "allowed_folder" field.
func AllowedFolderContains(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldContains(FieldAllowedFolder, v))
}

// AllowedFolderHasPrefix applies the HasPrefix predicate on the "allowed_folder" field.
func AllowedFolderHasPrefix(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldHasPrefix(FieldAllowedFolder, v))
}

// AllowedFolderHasSuffix applies the HasSuffix predicate on the "allowed_folder" field.
func AllowedFolderHasSuffix(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldHasSuffix(FieldAllowedFolder, v))
}

// AllowedFolderEqualFold applies the EqualFold predicate on the "allowed_folder" field.
func AllowedFolderEqualFold(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEqualFold(FieldAllowedFolder, v))
}

// AllowedFolderContainsFold applies the ContainsFold predicate on the "allowed_folder" field.
func AllowedFolderContainsFold(v string) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldContainsFold(FieldAllowedFolder, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.FieldLTE(FieldUpdatedAt, v))
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.ManagedAgent) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.ManagedAgent) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.ManagedAgent) predicate.ManagedAgent {
	return predicate.ManagedAgent(sql.NotPredicates(p))
}
