// Code generated by ent, DO NOT EDIT.

package roadmapphase

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/lx-wnk/agent-dashboard/server/internal/db/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContainsFold(FieldID, id))
}

// Title applies equality check predicate on the "title" field. It's identical to TitleEQ.
func Title(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldTitle, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldDescription, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldStatus, v))
}

// Position applies equality check predicate on the "position" field. It's identical to PositionEQ.
func Position(v int) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldPosition, v))
}

// IsCurrent applies equality check predicate on the "is_current" field. It's identical to IsCurrentEQ.
func IsCurrent(v bool) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldIsCurrent, v))
}

// Provenance applies equality check predicate on the "provenance" field. It's identical to ProvenanceEQ.
func Provenance(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldProvenance, v))
}

// BlockedReason applies equality check predicate on the "blocked_reason" field. It's identical to BlockedReasonEQ.
func BlockedReason(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldBlockedReason, v))
}

// Decisions applies equality check predicate on the "decisions" field. It's identical to DecisionsEQ.
func Decisions(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldDecisions, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldUpdatedAt, v))
}

// TitleEQ applies the EQ predicate on the "title" field.
func TitleEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldTitle, v))
}

// TitleNEQ applies the NEQ predicate on the "title" field.
func TitleNEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldTitle, v))
}

// TitleIn applies the In predicate on the "title" field.
func TitleIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIn(FieldTitle, vs...))
}

// TitleNotIn applies the NotIn predicate on the "title" field.
func TitleNotIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotIn(FieldTitle, vs...))
}

// TitleGT applies the GT predicate on the "title" field.
func TitleGT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGT(FieldTitle, v))
}

// TitleGTE applies the GTE predicate on the "title" field.
func TitleGTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGTE(FieldTitle, v))
}

// TitleLT applies the LT predicate on the "title" field.
func TitleLT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLT(FieldTitle, v))
}

// TitleLTE applies the LTE predicate on the "title" field.
func TitleLTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLTE(FieldTitle, v))
}

// TitleContains applies the Contains predicate on the "title" field.
func TitleContains(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContains(FieldTitle, v))
}

// TitleHasPrefix applies the HasPrefix predicate on the "title" field.
func TitleHasPrefix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasPrefix(FieldTitle, v))
}

// TitleHasSuffix applies the HasSuffix predicate on the "title" field.
func TitleHasSuffix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasSuffix(FieldTitle, v))
}

// TitleEqualFold applies the EqualFold predicate on the "title" field.
func TitleEqualFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEqualFold(FieldTitle, v))
}

// TitleContainsFold applies the ContainsFold predicate on the "title" field.
func TitleContainsFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContainsFold(FieldTitle, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContainsFold(FieldDescription, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContainsFold(FieldStatus, v))
}

// PositionEQ applies the EQ predicate on the "position" field.
func PositionEQ(v int) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldPosition, v))
}

// PositionNEQ applies the NEQ predicate on the "position" field.
func PositionNEQ(v int) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldPosition, v))
}

// PositionIn applies the In predicate on the "position" field.
func PositionIn(vs ...int) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIn(FieldPosition, vs...))
}

// PositionNotIn applies the NotIn predicate on the "position" field.
func PositionNotIn(vs ...int) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotIn(FieldPosition, vs...))
}

// PositionGT applies the GT predicate on the "position" field.
func PositionGT(v int) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGT(FieldPosition, v))
}

// PositionGTE applies the GTE predicate on the "position" field.
func PositionGTE(v int) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGTE(FieldPosition, v))
}

// PositionLT applies the LT predicate on the "position" field.
func PositionLT(v int) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLT(FieldPosition, v))
}

// PositionLTE applies the LTE predicate on the "position" field.
func PositionLTE(v int) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLTE(FieldPosition, v))
}

// IsCurrentEQ applies the EQ predicate on the "is_current" field.
func IsCurrentEQ(v bool) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldIsCurrent, v))
}

// IsCurrentNEQ applies the NEQ predicate on the "is_current" field.
func IsCurrentNEQ(v bool) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldIsCurrent, v))
}

// ProvenanceEQ applies the EQ predicate on the "provenance" field.
func ProvenanceEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldProvenance, v))
}

// ProvenanceNEQ applies the NEQ predicate on the "provenance" field.
func ProvenanceNEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldProvenance, v))
}

// ProvenanceIn applies the In predicate on the "provenance" field.
func ProvenanceIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIn(FieldProvenance, vs...))
}

// ProvenanceNotIn applies the NotIn predicate on the "provenance" field.
func ProvenanceNotIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotIn(FieldProvenance, vs...))
}

// ProvenanceGT applies the GT predicate on the "provenance" field.
func ProvenanceGT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGT(FieldProvenance, v))
}

// ProvenanceGTE applies the GTE predicate on the "provenance" field.
func ProvenanceGTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGTE(FieldProvenance, v))
}

// ProvenanceLT applies the LT predicate on the "provenance" field.
func ProvenanceLT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLT(FieldProvenance, v))
}

// ProvenanceLTE applies the LTE predicate on the "provenance" field.
func ProvenanceLTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLTE(FieldProvenance, v))
}

// ProvenanceContains applies the Contains predicate on the "provenance" field.
func ProvenanceContains(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContains(FieldProvenance, v))
}

// ProvenanceHasPrefix applies the HasPrefix predicate on the "provenance" field.
func ProvenanceHasPrefix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasPrefix(FieldProvenance, v))
}

// ProvenanceHasSuffix applies the HasSuffix predicate on the "provenance" field.
func ProvenanceHasSuffix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasSuffix(FieldProvenance, v))
}

// ProvenanceEqualFold applies the EqualFold predicate on the "provenance" field.
func ProvenanceEqualFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEqualFold(FieldProvenance, v))
}

// ProvenanceContainsFold applies the ContainsFold predicate on the "provenance" field.
func ProvenanceContainsFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContainsFold(FieldProvenance, v))
}

// BlockedReasonEQ applies the EQ predicate on the "blocked_reason" field.
func BlockedReasonEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldBlockedReason, v))
}

// BlockedReasonNEQ applies the NEQ predicate on the "blocked_reason" field.
func BlockedReasonNEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldBlockedReason, v))
}

// BlockedReasonIn applies the In predicate on the "blocked_reason" field.
func BlockedReasonIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIn(FieldBlockedReason, vs...))
}

// BlockedReasonNotIn applies the NotIn predicate on the "blocked_reason" field.
func BlockedReasonNotIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotIn(FieldBlockedReason, vs...))
}

// BlockedReasonGT applies the GT predicate on the "blocked_reason" field.
func BlockedReasonGT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGT(FieldBlockedReason, v))
}

// BlockedReasonGTE applies the GTE predicate on the "blocked_reason" field.
func BlockedReasonGTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGTE(FieldBlockedReason, v))
}

// BlockedReasonLT applies the LT predicate on the "blocked_reason" field.
func BlockedReasonLT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLT(FieldBlockedReason, v))
}

// BlockedReasonLTE applies the LTE predicate on the "blocked_reason" field.
func BlockedReasonLTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLTE(FieldBlockedReason, v))
}

// BlockedReasonContains applies the Contains predicate on the "blocked_reason" field.
func BlockedReasonContains(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContains(FieldBlockedReason, v))
}

// BlockedReasonHasPrefix applies the HasPrefix predicate on the "blocked_reason" field.
func BlockedReasonHasPrefix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasPrefix(FieldBlockedReason, v))
}

// BlockedReasonHasSuffix applies the HasSuffix predicate on the "blocked_reason" field.
func BlockedReasonHasSuffix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasSuffix(FieldBlockedReason, v))
}

// BlockedReasonEqualFold applies the EqualFold predicate on the "blocked_reason" field.
func BlockedReasonEqualFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEqualFold(FieldBlockedReason, v))
}

// BlockedReasonContainsFold applies the ContainsFold predicate on the "blocked_reason" field.
func BlockedReasonContainsFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContainsFold(FieldBlockedReason, v))
}

// DecisionsEQ applies the EQ predicate on the "decisions" field.
func DecisionsEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldDecisions, v))
}

// DecisionsNEQ applies the NEQ predicate on the "decisions" field.
func DecisionsNEQ(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldDecisions, v))
}

// DecisionsIn applies the In predicate on the "decisions" field.
func DecisionsIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIn(FieldDecisions, vs...))
}

// DecisionsNotIn applies the NotIn predicate on the "decisions" field.
func DecisionsNotIn(vs ...string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotIn(FieldDecisions, vs...))
}

// DecisionsGT applies the GT predicate on the "decisions" field.
func DecisionsGT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGT(FieldDecisions, v))
}

// DecisionsGTE applies the GTE predicate on the "decisions" field.
func DecisionsGTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGTE(FieldDecisions, v))
}

// DecisionsLT applies the LT predicate on the "decisions" field.
func DecisionsLT(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLT(FieldDecisions, v))
}

// DecisionsLTE applies the LTE predicate on the "decisions" field.
func DecisionsLTE(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLTE(FieldDecisions, v))
}

// DecisionsContains applies the Contains predicate on the "decisions" field.
func DecisionsContains(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContains(FieldDecisions, v))
}

// DecisionsHasPrefix applies the HasPrefix predicate on the "decisions" field.
func DecisionsHasPrefix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasPrefix(FieldDecisions, v))
}

// DecisionsHasSuffix applies the HasSuffix predicate on the "decisions" field.
func DecisionsHasSuffix(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldHasSuffix(FieldDecisions, v))
}

// DecisionsEqualFold applies the EqualFold predicate on the "decisions" field.
func DecisionsEqualFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEqualFold(FieldDecisions, v))
}

// DecisionsContainsFold applies the ContainsFold predicate on the "decisions" field.
func DecisionsContainsFold(v string) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldContainsFold(FieldDecisions, v))
}

// DependsOnIsNil applies the IsNil predicate on the "depends_on" field.
func DependsOnIsNil() predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIsNull(FieldDependsOn))
}

// DependsOnNotNil applies the NotNil predicate on the "depends_on" field.
func DependsOnNotNil() predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotNull(FieldDependsOn))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasProject applies the HasEdge predicate on the "project" edge.
func HasProject() predicate.RoadmapPhase {
	return predicate.RoadmapPhase(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, ProjectTable, ProjectColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasProjectWith applies the HasEdge predicate on the "project" edge with a given conditions (other predicates).
func HasProjectWith(preds ...predicate.Project) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(func(s *sql.Selector) {
		step := newProjectStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasItems applies the HasEdge predicate on the "items" edge.
func HasItems() predicate.RoadmapPhase {
	return predicate.RoadmapPhase(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, ItemsTable, ItemsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasItemsWith applies the HasEdge predicate on the "items" edge with a given conditions (other predicates).
func HasItemsWith(preds ...predicate.RoadmapItem) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(func(s *sql.Selector) {
		step := newItemsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.RoadmapPhase) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.RoadmapPhase) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.RoadmapPhase) predicate.RoadmapPhase {
	return predicate.RoadmapPhase(sql.NotPredicates(p))
}
